export const STORES_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "门店 · STORES",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 门店 · 运营",
    title: "你负责的",
    titleEm: "门店",
    titleSuffix: "。",
    lede: "查看你管理或参与运营的门店。选择一家，查看班次、岗位与当日要点。",
    countSingular: "家门店",
    countPlural: "家门店",
    listHeading: "列表",
    formTitleCreate: "新增门店",
    formTitleEdit: "编辑门店",
    nameLabel: "门店名称",
    namePlaceholder: "例如：ZHAO Paris Opéra",
    photoLabel: "图片 URL",
    photoPlaceholder: "可选，留空使用默认图",
    saveCreate: "新增",
    saveEdit: "保存",
    cancel: "取消",
    review: "进入审核",
    edit: "编辑",
    delete: "删除",
    deleteConfirm: "确认删除这家门店？如已有用户或订单关联，后端会拒绝删除。",
    formRequired: "门店名称和地址不能为空。",
    saveError: "门店保存失败。",
    deleteError: "门店删除失败，可能已有用户或订单关联。",
    back: "返回首页",
    codeLabel: "编号",
    addressLabel: "地址",
    statusOpen: "营业中",
    statusClosed: "已打烊",
    loading: "门店加载中...",
    loadError: "门店加载失败，请检查 restaurants 接口或数据库连接。",
    empty: "数据库里还没有门店。",
    approval: {
      topStage: "门店 · 审核",
      kicker: "ZHAO's · 员工审批",
      titlePrefix: "审核",
      titleSuffix: "的新员工。",
      lede: "这里会自动筛出这家门店等待审批的注册用户。通过后员工才能登录平台。",
      pendingHeading: "待审批",
      teamHeading: "当前团队",
      noPending: "这家门店暂时没有待审批员工。",
      noTeam: "这家门店还没有员工记录。",
      saveRole: "保存岗位",
      savingRole: "保存中",
      roleSaved: "岗位已更新。",
      roleSaveError: "岗位保存失败。",
      selectStore: "选择门店",
      selectJobRole: "选择岗位",
      storeLabel: "门店",
      loading: "审批队列加载中...",
      loadError: "审批队列加载失败，请检查 permissions 接口。",
      storeNotFound: "没有找到这家门店。",
      approve: "通过",
      reject: "拒绝",
      reviewing: "处理中",
      status: {
        pending: "待审批",
        approved: "已通过",
        rejected: "已拒绝",
      },
      table: {
        name: "姓名",
        email: "邮箱",
        store: "门店",
        jobRole: "岗位",
        status: "状态",
        action: "操作",
      },
      backToStores: "返回门店列表",
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "STORES · 门店",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · STORES · OPERATIONS",
    title: "Your ",
    titleEm: "stores",
    titleSuffix: ".",
    lede: "Stores you manage or work at. Pick one to see shifts, roles and today's focus.",
    countSingular: "store",
    countPlural: "stores",
    listHeading: "List",
    formTitleCreate: "Add store",
    formTitleEdit: "Edit store",
    nameLabel: "Store name",
    namePlaceholder: "Example: ZHAO Paris Opéra",
    photoLabel: "Photo URL",
    photoPlaceholder: "Optional, leave blank for default image",
    saveCreate: "Add",
    saveEdit: "Save",
    cancel: "Cancel",
    review: "Review",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this store? If users or orders are linked, the backend will reject it.",
    formRequired: "Store name and address are required.",
    saveError: "Failed to save store.",
    deleteError: "Failed to delete store. It may already be linked to users or orders.",
    back: "Back to home",
    codeLabel: "Code",
    addressLabel: "Address",
    statusOpen: "Open",
    statusClosed: "Closed",
    loading: "Loading stores...",
    loadError: "Failed to load stores. Check the restaurants API or database connection.",
    empty: "No stores are available in the database yet.",
    approval: {
      topStage: "STORES · APPROVAL",
      kicker: "ZHAO's · EMPLOYEE APPROVAL",
      titlePrefix: "Review new employees for ",
      titleSuffix: ".",
      lede: "This view filters pending registrations for the selected store. Approved employees can sign in afterwards.",
      pendingHeading: "Pending approval",
      teamHeading: "Current team",
      noPending: "No pending employees for this store.",
      noTeam: "No employee records for this store yet.",
      saveRole: "Save position",
      savingRole: "Saving",
      roleSaved: "Position updated.",
      roleSaveError: "Failed to save position.",
      selectStore: "Select store",
      selectJobRole: "Select position",
      storeLabel: "Store",
      loading: "Loading approval queue...",
      loadError: "Failed to load approvals. Check the permissions API.",
      storeNotFound: "Store not found.",
      approve: "Approve",
      reject: "Reject",
      reviewing: "Saving",
      status: {
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
      },
      table: {
        name: "Name",
        email: "Email",
        store: "Store",
        jobRole: "Position",
        status: "Status",
        action: "Action",
      },
      backToStores: "Back to stores",
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "BOUTIQUES · 门店",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · BOUTIQUES · OPÉRATIONS",
    title: "Vos ",
    titleEm: "boutiques",
    titleSuffix: ".",
    lede: "Boutiques que vous gérez ou dans lesquelles vous travaillez. Choisissez-en une pour voir plannings, postes et points du jour.",
    countSingular: "boutique",
    countPlural: "boutiques",
    listHeading: "Liste",
    formTitleCreate: "Ajouter une boutique",
    formTitleEdit: "Modifier la boutique",
    nameLabel: "Nom de la boutique",
    namePlaceholder: "Exemple : ZHAO Paris Opéra",
    photoLabel: "URL de la photo",
    photoPlaceholder: "Optionnel, vide pour l'image par défaut",
    saveCreate: "Ajouter",
    saveEdit: "Enregistrer",
    cancel: "Annuler",
    review: "Valider",
    edit: "Modifier",
    delete: "Supprimer",
    deleteConfirm:
      "Supprimer cette boutique ? Si des utilisateurs ou commandes sont liés, le backend refusera.",
    formRequired: "Le nom et l'adresse sont obligatoires.",
    saveError: "Échec de l'enregistrement de la boutique.",
    deleteError:
      "Échec de la suppression. La boutique est peut-être liée à des utilisateurs ou commandes.",
    back: "Retour à l'accueil",
    codeLabel: "Code",
    addressLabel: "Adresse",
    statusOpen: "Ouverte",
    statusClosed: "Fermée",
    loading: "Chargement des boutiques...",
    loadError:
      "Impossible de charger les boutiques. Vérifiez l'API restaurants ou la connexion base de données.",
    empty: "Aucune boutique n'est encore disponible en base.",
    approval: {
      topStage: "BOUTIQUES · VALIDATION",
      kicker: "ZHAO's · VALIDATION EMPLOYES",
      titlePrefix: "Valider les nouveaux employes de ",
      titleSuffix: ".",
      lede: "Cette page filtre les inscriptions en attente pour la boutique choisie. Une fois valide, l'employe peut se connecter.",
      pendingHeading: "En attente",
      teamHeading: "Equipe actuelle",
      noPending: "Aucun employe en attente pour cette boutique.",
      noTeam: "Aucun employe rattache a cette boutique pour le moment.",
      saveRole: "Enregistrer le poste",
      savingRole: "En cours",
      roleSaved: "Poste mis a jour.",
      roleSaveError: "Echec de l'enregistrement du poste.",
      selectStore: "Choisir la boutique",
      selectJobRole: "Choisir le poste",
      storeLabel: "Boutique",
      loading: "Chargement de la file de validation...",
      loadError: "Impossible de charger les validations. Verifiez l'API permissions.",
      storeNotFound: "Boutique introuvable.",
      approve: "Valider",
      reject: "Refuser",
      reviewing: "En cours",
      status: {
        pending: "En attente",
        approved: "Valide",
        rejected: "Refuse",
      },
      table: {
        name: "Nom",
        email: "Email",
        store: "Boutique",
        jobRole: "Poste",
        status: "Statut",
        action: "Action",
      },
      backToStores: "Retour aux boutiques",
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
};

export const STORE_JOB_ROLE_OPTIONS = {
  zh: [
    { value: "holding", label: "总部" },
    { value: "regional-manager", label: "区域经理" },
    { value: "store-manager", label: "店长" },
    { value: "front-manager", label: "前厅经理" },
    { value: "back-manager", label: "后厨经理" },
    { value: "front-assistant", label: "前厅助理" },
    { value: "back-assistant", label: "后厨助理" },
    { value: "front-of-house", label: "前厅" },
    { value: "front-host", label: "迎宾" },
    { value: "front-cashier", label: "收银" },
    { value: "front-server", label: "服务生" },
    { value: "front-packer", label: "打包" },
    { value: "front-bar", label: "吧台" },
    { value: "back-of-house", label: "后厨" },
    { value: "back-dishwasher", label: "洗碗" },
    { value: "back-noodle", label: "打面" },
    { value: "back-hot-appetizer", label: "热前菜" },
    { value: "back-cold-appetizer", label: "冷前菜" },
    { value: "back-rice", label: "饭" },
  ],
  en: [
    { value: "holding", label: "Holding" },
    { value: "regional-manager", label: "Regional manager" },
    { value: "store-manager", label: "Store manager" },
    { value: "front-manager", label: "Front manager" },
    { value: "back-manager", label: "Kitchen manager" },
    { value: "front-assistant", label: "Front assistant" },
    { value: "back-assistant", label: "Kitchen assistant" },
    { value: "front-of-house", label: "Front of house" },
    { value: "front-host", label: "Host" },
    { value: "front-cashier", label: "Cashier" },
    { value: "front-server", label: "Server" },
    { value: "front-packer", label: "Packing" },
    { value: "front-bar", label: "Bar" },
    { value: "back-of-house", label: "Kitchen" },
    { value: "back-dishwasher", label: "Dishwasher" },
    { value: "back-noodle", label: "Noodle station" },
    { value: "back-hot-appetizer", label: "Hot appetizers" },
    { value: "back-cold-appetizer", label: "Cold appetizers" },
    { value: "back-rice", label: "Rice station" },
  ],
  fr: [
    { value: "holding", label: "Holding" },
    { value: "regional-manager", label: "Manager regional" },
    { value: "store-manager", label: "Gerant" },
    { value: "front-manager", label: "Responsable salle" },
    { value: "back-manager", label: "Responsable cuisine" },
    { value: "front-assistant", label: "Assistant salle" },
    { value: "back-assistant", label: "Assistant cuisine" },
    { value: "front-of-house", label: "Salle" },
    { value: "front-host", label: "Accueil" },
    { value: "front-cashier", label: "Caisse" },
    { value: "front-server", label: "Serveur" },
    { value: "front-packer", label: "Emballage" },
    { value: "front-bar", label: "Bar" },
    { value: "back-of-house", label: "Cuisine" },
    { value: "back-dishwasher", label: "Plonge" },
    { value: "back-noodle", label: "Nouilles" },
    { value: "back-hot-appetizer", label: "Entrées chaudes" },
    { value: "back-cold-appetizer", label: "Entrées froides" },
    { value: "back-rice", label: "Riz" },
  ],
};

export const MOCK_STORES = [
  {
    id: "paris-opera",
    name: { zh: "巴黎·歌剧院店", en: "Paris — Opéra", fr: "Paris — Opéra" },
    city: { zh: "巴黎", en: "Paris", fr: "Paris" },
    role: { zh: "店长", en: "Store manager", fr: "Responsable de boutique" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "外卖", en: "Delivery", fr: "Livraison" },
    ],
  },
  {
    id: "paris-marais",
    name: { zh: "巴黎·玛黑店", en: "Paris — Marais", fr: "Paris — Marais" },
    city: { zh: "巴黎", en: "Paris", fr: "Paris" },
    role: { zh: "副店长", en: "Assistant manager", fr: "Adjoint·e de direction" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "堂食", en: "Dining", fr: "Salle" },
    ],
  },
  {
    id: "lyon-presquile",
    name: { zh: "里昂·半岛店", en: "Lyon — Presqu'île", fr: "Lyon — Presqu'île" },
    city: { zh: "里昂", en: "Lyon", fr: "Lyon" },
    role: { zh: "主厨", en: "Head chef", fr: "Chef de cuisine" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "培训", en: "Training", fr: "Formation" },
    ],
  },
  {
    id: "bordeaux-centre",
    name: { zh: "波尔多·市中心店", en: "Bordeaux — Centre", fr: "Bordeaux — Centre" },
    city: { zh: "波尔多", en: "Bordeaux", fr: "Bordeaux" },
    role: { zh: "领班", en: "Floor lead", fr: "Chef·fe de rang" },
    status: "closed",
    tags: [
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "活动", en: "Events", fr: "Événements" },
    ],
  },
  {
    id: "marseille-vieux-port",
    name: {
      zh: "马赛·老港店",
      en: "Marseille — Vieux-Port",
      fr: "Marseille — Vieux-Port",
    },
    city: { zh: "马赛", en: "Marseille", fr: "Marseille" },
    role: { zh: "储备干部", en: "Management trainee", fr: "Cadre en formation" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "外卖", en: "Delivery", fr: "Livraison" },
    ],
  },
  {
    id: "nice-promenade",
    name: {
      zh: "尼斯·英国人散步道店",
      en: "Nice — Promenade",
      fr: "Nice — Promenade",
    },
    city: { zh: "尼斯", en: "Nice", fr: "Nice" },
    role: { zh: "实习生", en: "Intern", fr: "Stagiaire" },
    status: "closed",
    tags: [
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "培训", en: "Training", fr: "Formation" },
    ],
  },
];
