export const STORES_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "门店 · STORES",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 门店 · 运营",
    title: "你负责的",
    titleEm: "门店",
    titleSuffix: "。",
    lede: "查看你管理或参与运营的门店。选择一家，查看班次、岗位与当日要点。",
    countSingular: "家门店",
    countPlural: "家门店",
    listHeading: "列表",
    back: "返回首页",
    codeLabel: "编号",
    addressLabel: "地址",
    statusOpen: "营业中",
    statusClosed: "已打烊",
    loading: "门店加载中...",
    loadError: "门店加载失败，请检查 restaurants 接口或数据库连接。",
    empty: "数据库里还没有门店。",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "STORES · 门店",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · STORES · OPERATIONS",
    title: "Your ",
    titleEm: "stores",
    titleSuffix: ".",
    lede: "Stores you manage or work at. Pick one to see shifts, roles and today's focus.",
    countSingular: "store",
    countPlural: "stores",
    listHeading: "List",
    back: "Back to home",
    codeLabel: "Code",
    addressLabel: "Address",
    statusOpen: "Open",
    statusClosed: "Closed",
    loading: "Loading stores...",
    loadError: "Failed to load stores. Check the restaurants API or database connection.",
    empty: "No stores are available in the database yet.",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "BOUTIQUES · 门店",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · BOUTIQUES · OPÉRATIONS",
    title: "Vos ",
    titleEm: "boutiques",
    titleSuffix: ".",
    lede: "Boutiques que vous gérez ou dans lesquelles vous travaillez. Choisissez-en une pour voir plannings, postes et points du jour.",
    countSingular: "boutique",
    countPlural: "boutiques",
    listHeading: "Liste",
    back: "Retour à l'accueil",
    codeLabel: "Code",
    addressLabel: "Adresse",
    statusOpen: "Ouverte",
    statusClosed: "Fermée",
    loading: "Chargement des boutiques...",
    loadError:
      "Impossible de charger les boutiques. Vérifiez l'API restaurants ou la connexion base de données.",
    empty: "Aucune boutique n'est encore disponible en base.",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
};

export const MOCK_STORES = [
  {
    id: "paris-opera",
    name: { zh: "巴黎·歌剧院店", en: "Paris — Opéra", fr: "Paris — Opéra" },
    city: { zh: "巴黎", en: "Paris", fr: "Paris" },
    role: { zh: "店长", en: "Store manager", fr: "Responsable de boutique" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "外卖", en: "Delivery", fr: "Livraison" },
    ],
  },
  {
    id: "paris-marais",
    name: { zh: "巴黎·玛黑店", en: "Paris — Marais", fr: "Paris — Marais" },
    city: { zh: "巴黎", en: "Paris", fr: "Paris" },
    role: { zh: "副店长", en: "Assistant manager", fr: "Adjoint·e de direction" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "堂食", en: "Dining", fr: "Salle" },
    ],
  },
  {
    id: "lyon-presquile",
    name: { zh: "里昂·半岛店", en: "Lyon — Presqu'île", fr: "Lyon — Presqu'île" },
    city: { zh: "里昂", en: "Lyon", fr: "Lyon" },
    role: { zh: "主厨", en: "Head chef", fr: "Chef de cuisine" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "培训", en: "Training", fr: "Formation" },
    ],
  },
  {
    id: "bordeaux-centre",
    name: { zh: "波尔多·市中心店", en: "Bordeaux — Centre", fr: "Bordeaux — Centre" },
    city: { zh: "波尔多", en: "Bordeaux", fr: "Bordeaux" },
    role: { zh: "领班", en: "Floor lead", fr: "Chef·fe de rang" },
    status: "closed",
    tags: [
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "活动", en: "Events", fr: "Événements" },
    ],
  },
  {
    id: "marseille-vieux-port",
    name: {
      zh: "马赛·老港店",
      en: "Marseille — Vieux-Port",
      fr: "Marseille — Vieux-Port",
    },
    city: { zh: "马赛", en: "Marseille", fr: "Marseille" },
    role: { zh: "储备干部", en: "Management trainee", fr: "Cadre en formation" },
    status: "open",
    tags: [
      { zh: "厨房", en: "Kitchen", fr: "Cuisine" },
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "外卖", en: "Delivery", fr: "Livraison" },
    ],
  },
  {
    id: "nice-promenade",
    name: {
      zh: "尼斯·英国人散步道店",
      en: "Nice — Promenade",
      fr: "Nice — Promenade",
    },
    city: { zh: "尼斯", en: "Nice", fr: "Nice" },
    role: { zh: "实习生", en: "Intern", fr: "Stagiaire" },
    status: "closed",
    tags: [
      { zh: "堂食", en: "Dining", fr: "Salle" },
      { zh: "培训", en: "Training", fr: "Formation" },
    ],
  },
];
