export const TRAINING_COURSES = {
  required: [
    {
      id: "m-safety-1",
      type: "VIDEO",
      req: true,
      title: "安全与卫生基础",
      en: "Safety & Hygiene 101",
      dur: "24 min",
      prog: 55,
      status: "in_progress",
      desc: "个人防护、交叉污染预防、意外处置。入职 7 天内完成。",
      tags: ["必修", "入职"],
    },
    {
      id: "m-greet-sop",
      type: "PDF",
      req: true,
      title: "客人迎接 SOP",
      en: "Greeting standard SOP",
      dur: "18 页",
      prog: 100,
      status: "completed",
      desc: "前厅 7 秒法则、领位原则与菜单呈递。",
      tags: ["必修", "SOP"],
    },
    {
      id: "m-menu-1",
      type: "VIDEO",
      req: true,
      title: "菜品知识 · 招牌篇",
      en: "Signature dishes walk-through",
      dur: "32 min",
      prog: 12,
      status: "in_progress",
      desc: "10 道招牌菜的故事、辣度、忌口与推荐搭配。",
      tags: ["必修", "菜单"],
    },
    {
      id: "m-pos-1",
      type: "VIDEO",
      req: true,
      title: "点单机 ZPOS 基础操作",
      en: "ZPOS basics",
      dur: "18 min",
      prog: 0,
      status: "not_started",
      desc: "开单、拆单、改单、退单的基础操作流程。",
      tags: ["必修", "系统"],
    },
    {
      id: "m-quiz-1",
      type: "QUIZ",
      req: true,
      title: "入职结业测验",
      en: "Onboarding final",
      dur: "20 题",
      prog: 0,
      status: "not_started",
      desc: "10 题必答,满分 100,≥ 85 颁发「基础认证」。",
      tags: ["考核"],
    },
    {
      id: "m-fire-1",
      type: "ARTICLE",
      req: true,
      title: "消防应急手册",
      en: "Fire emergency manual",
      dur: "12 min read",
      prog: 0,
      status: "not_started",
      desc: "灭火器位置、疏散路线与现场协作。",
      tags: ["必修", "安全"],
    },
  ],
  optional: [
    {
      id: "m-wine-1",
      type: "VIDEO",
      req: false,
      title: "中式佐餐酒搭配",
      en: "Chinese food & wine pairing",
      dur: "45 min",
      prog: 0,
      status: "not_started",
      desc: "黄酒、白酒、茶与招牌菜的口感映射。",
      tags: ["进阶", "品鉴"],
    },
    {
      id: "m-lang-1",
      type: "VIDEO",
      req: false,
      title: "客人英语速成 · 前厅",
      en: "Guest English for FOH",
      dur: "28 min",
      prog: 0,
      status: "not_started",
      desc: "50 句高频场景英语,含音频跟读。",
      tags: ["进阶", "英语"],
    },
    {
      id: "m-wine-2",
      type: "QUIZ",
      req: false,
      title: "酒品盲品小测",
      en: "Wine blind-taste quiz",
      dur: "10 题",
      prog: 0,
      status: "not_started",
      desc: "黄酒、米酒、精酿的风味辨识。",
      tags: ["进阶"],
    },
  ],
};

export const TRAINING_CERTIFICATIONS = {
  required: [
    {
      id: "CERT-FOH-0",
      code: "FOH-0",
      rank: "RANK 0",
      title: "前厅基础认证",
      en: "FOH Basic",
      desc: "安全、卫生、点单机基础操作的综合评估,入职 14 天内取得。",
      status: "active",
      granted: "2025-10-28",
      expire: "2027-10-28",
      by: "BJ-001 · 店长 周",
    },
    {
      id: "CERT-FOH-1",
      code: "FOH-1",
      rank: "RANK 1",
      title: "前厅进阶 · 服务礼仪",
      en: "FOH L1 · Etiquette",
      desc: "客人迎送、投诉处理、VIP 识别的闭卷 + 实操双考核。",
      status: "expiring",
      granted: "2024-11-02",
      expire: "2026-05-02",
      by: "BJ-001 · 店长 周",
    },
    {
      id: "CERT-MENU-A",
      code: "MENU-A",
      rank: "RANK 2",
      title: "菜品 A 级讲解员",
      en: "Menu Ambassador A",
      desc: "招牌 10 道 + 时令菜单的口述能力考核,含英文版本。",
      status: "available",
      by: "-",
    },
    {
      id: "CERT-WINE-B",
      code: "WINE-B",
      rank: "RANK 3",
      title: "佐餐酒 B 级",
      en: "Beverage Pairing B",
      desc: "黄酒与白酒基础 + 场景推荐话术,由区域经理级考官考核。",
      status: "locked",
      by: "需先取得 MENU-A",
    },
  ],
  optional: [
    {
      id: "CERT-LANG-EN",
      code: "LANG-EN",
      rank: "—",
      title: "涉外服务 · 英语",
      en: "Guest English",
      desc: "50 句场景英语实操,出境客/外宾接待加项。",
      status: "available",
      by: "-",
    },
    {
      id: "CERT-MGR-0",
      code: "MGR-0",
      rank: "—",
      title: "储备干部 · 入门",
      en: "Management Track 0",
      desc: "排班、报表、成本的入门测验,为店长路径的起点。",
      status: "locked",
      by: "需晋升为「资深前厅」",
    },
  ],
};

export const TRAINING_POSITIONS = [
  {
    id: "FOH",
    code: "POS-01",
    name: "前厅服务员",
    en: "Front of House",
    mine: true,
    desc: "客人接触、领位、点单、上菜全链路的岗位基线资料。",
  },
  {
    id: "BOH",
    code: "POS-02",
    name: "后厨 · 厨师线",
    en: "Back of House",
    mine: false,
    desc: "出餐线、卫生规范、招牌菜复刻的厨务资料。",
  },
  {
    id: "CASH",
    code: "POS-03",
    name: "收银 / 结账台",
    en: "Cashier",
    mine: false,
    desc: "开票、退单、支付异常、发票规范。",
  },
  {
    id: "SM",
    code: "POS-04",
    name: "店长 · 门店负责人",
    en: "Store Manager",
    mine: false,
    desc: "排班、成本、日结、现场决策的必备材料。",
  },
  {
    id: "RM",
    code: "POS-05",
    name: "区域经理",
    en: "Regional Manager",
    mine: false,
    desc: "多店督导、SOP 巡检、人才流动与汇报。",
    locked: true,
  },
  {
    id: "HOLDING",
    code: "POS-06",
    name: "总部 / Holding",
    en: "Holding",
    mine: false,
    desc: "最高管理、总部支持与跨门店治理资料。",
    locked: true,
  },
  {
    id: "ALL",
    code: "POS-00",
    name: "全岗通用",
    en: "All positions",
    mine: true,
    desc: "消防、安全、价值观、合规——每个 ZHAO 伙伴都需知晓。",
  },
];

export const TRAINING_MATERIALS = [
  { id: "M001", pos: "FOH", type: "VIDEO", req: true, sort: 1, title: "客人迎接标准 · 7 秒法则", sub: "24 min · 含分镜示范", upd: "2026-02-10", size: "142 MB" },
  { id: "M002", pos: "FOH", type: "PDF", req: true, sort: 2, title: "前厅 SOP 手册 v3.2", sub: "18 页 · 领位/菜单/上菜", upd: "2026-03-12", size: "2.1 MB" },
  { id: "M003", pos: "FOH", type: "VIDEO", req: true, sort: 3, title: "菜品知识 · 招牌 10 道", sub: "32 min · 故事/辣度/忌口", upd: "2026-02-02", size: "198 MB" },
  { id: "M004", pos: "FOH", type: "VIDEO", req: true, sort: 4, title: "ZPOS 前厅基础操作", sub: "18 min · 开/拆/改/退单", upd: "2025-12-18", size: "98 MB" },
  { id: "M007", pos: "FOH", type: "VIDEO", req: false, sort: 5, title: "佐餐酒搭配 · 进阶", sub: "45 min · 黄酒/白酒/茶", upd: "2025-09-30", size: "312 MB" },
  { id: "M008", pos: "FOH", type: "VIDEO", req: false, sort: 6, title: "英语速成 · 前厅场景", sub: "28 min · 50 句 + 跟读", upd: "2025-11-14", size: "168 MB" },
  { id: "M011", pos: "FOH", type: "QUIZ", req: false, sort: 7, title: "酒品盲品小测", sub: "10 题 · 风味辨识", upd: "2025-10-05", size: "—" },
  { id: "M101", pos: "BOH", type: "VIDEO", req: true, sort: 1, title: "后厨开线 · 开店前 20 分钟", sub: "15 min · 分工/检查表", upd: "2026-01-18", size: "88 MB" },
  { id: "M102", pos: "BOH", type: "PDF", req: true, sort: 2, title: "招牌菜复刻手册", sub: "36 页 · 分量/火候/摆盘", upd: "2026-02-22", size: "4.6 MB" },
  { id: "M103", pos: "BOH", type: "VIDEO", req: false, sort: 3, title: "刀工 · 常见切法", sub: "22 min · 直/滚/片/剁", upd: "2025-11-08", size: "120 MB" },
  { id: "M201", pos: "CASH", type: "VIDEO", req: true, sort: 1, title: "ZPOS 收银台操作", sub: "16 min · 结账/找零/对账", upd: "2025-12-20", size: "82 MB" },
  { id: "M202", pos: "CASH", type: "PDF", req: true, sort: 2, title: "发票与退款规范", sub: "8 页 · 异常处理手顺", upd: "2026-02-01", size: "0.8 MB" },
  { id: "M301", pos: "SM", type: "PDF", req: true, sort: 1, title: "排班与人力成本指南", sub: "28 页 · 算法/示例/红线", upd: "2026-02-28", size: "3.8 MB" },
  { id: "M302", pos: "SM", type: "VIDEO", req: true, sort: 2, title: "日结与周报流程", sub: "26 min · 报表模板逐项讲解", upd: "2026-03-01", size: "140 MB" },
  { id: "M303", pos: "SM", type: "PDF", req: false, sort: 3, title: "投诉处理剧本 · 12 场景", sub: "20 页 · 话术模板", upd: "2026-01-22", size: "1.4 MB" },
  { id: "M304", pos: "SM", type: "QUIZ", req: false, sort: 4, title: "店长资格模拟考", sub: "40 题 · 综合评估", upd: "2025-11-30", size: "—" },
  { id: "M401", pos: "RM", type: "PDF", req: true, sort: 1, title: "区域督导手册", sub: "52 页 · 巡店清单", upd: "2026-02-14", size: "6.2 MB" },
  { id: "M402", pos: "RM", type: "ARTICLE", req: false, sort: 2, title: "多店人才流动策略", sub: "12 min · 内部转岗", upd: "2025-10-28", size: "—" },
  { id: "M901", pos: "ALL", type: "VIDEO", req: true, sort: 1, title: "安全与卫生基础", sub: "24 min · 入职 7 天内", upd: "2026-02-10", size: "142 MB" },
  { id: "M902", pos: "ALL", type: "ARTICLE", req: true, sort: 2, title: "消防应急手册", sub: "12 min 读 · 疏散/协作", upd: "2025-10-20", size: "—" },
  { id: "M903", pos: "ALL", type: "QUIZ", req: true, sort: 3, title: "入职结业测验", sub: "20 题 · 满分 100", upd: "2025-11-01", size: "—" },
  { id: "M904", pos: "ALL", type: "ARTICLE", req: false, sort: 4, title: "ZHAO 价值观与历史", sub: "8 min · 自 2011", upd: "2025-09-01", size: "—" },
];

export const TRAINING_COPY = {
  zh: {
    shared: {
      topFamily: "FAMILY",
      topCycle: "WEEK 17 · 2026",
      footer: "Since 2011 — ZHAO's Family Holding",
      backHome: "返回首页",
      courseStatus: {
        in_progress: "进行中 · IN PROGRESS",
        not_started: "未开始 · NOT STARTED",
        completed: "已完成 · COMPLETED",
      },
      courseFilters: {
        all: "全部",
        in_progress: "进行中",
        not_started: "未开始",
        completed: "已完成",
      },
      certAction: {
        active: "查看证书 →",
        expiring: "立即复核 →",
        expired: "重新考核 →",
        available: "报名考核 →",
        locked: "查看条件 →",
        revoked: "查看原因 →",
      },
      certBadge: {
        active: "ACTIVE · 有效",
        expiring: "EXPIRING ≤ 30d · 即将到期",
        expired: "EXPIRED · 已过期",
        revoked: "REVOKED · 已撤销",
        available: "AVAILABLE · 可考核",
        locked: "LOCKED · 未解锁",
      },
      materialFilters: {
        all: "全部",
        req: "必修",
        VIDEO: "视频",
        PDF: "手册",
        QUIZ: "测验",
        ARTICLE: "文章",
        IMAGE: "图片",
        OTHER: "其他",
      },
      empty: "暂无匹配项",
      materialSearchPrefix: "在",
      materialSearchSuffix: "中搜索…",
      materialOpen: "查看资料 →",
      courseAction: {
        in_progress: "继续学习",
        not_started: "开始课程",
        completed: "重新学习",
      },
    },
    training: {
      topStage: "培训空间 · TRAINING",
      kicker: "ZHAO's · 培训 · 认证 · 资料",
      title: "培训",
      titleEm: "空间",
      titleSuffix: "。",
      lede: "你的学习路径由岗位自动生成。先完成必修,再选修深度课程。每学完一节都会留痕,用于认证评估。",
      stepLabel: "STEP 01",
      stepDetail: "ONBOARDING · 前厅服务员 · 入职 14 天",
      metrics: [
        { value: "4/12", label: "REQUIRED" },
        { value: "2.5h", label: "THIS WEEK" },
        { value: "33%", label: "OVERALL" },
      ],
      onboardingKicker: "NEW HIRE · 前 14 天 · 进度 33%",
      onboardingTitle: "先从「安全与卫生基础」开始 ↓",
      onboardingDesc: "这是系统为你推荐的下一步。用时约 24 分钟,完成后解锁「客人迎接 · 标准 SOP」。",
      onboardingAction: "立即继续",
      requiredHeading: "岗位必修",
      requiredEn: "Required by role",
      optionalHeading: "选修 · 深度课程",
      optionalEn: "Optional · deep-dive",
    },
    certifications: {
      topStage: "认证管理 · CERTIFICATIONS",
      kicker: "ZHAO's · 培训 · 认证 · 资料",
      title: "认证",
      titleEm: "管理",
      titleSuffix: "。",
      lede: "每张证书代表一项已验证的技能。从低阶到高阶逐级解锁,到期前 30 天系统会提醒复核。",
      stepLabel: "STEP 02",
      stepDetail: "CERTIFICATION LADDER · 你的技能阶梯",
      metrics: [
        { value: "2/6", label: "ACTIVE" },
        { value: "1", label: "EXPIRING ≤ 30d" },
        { value: "3", label: "AVAILABLE" },
      ],
      requiredHeading: "岗位必备认证",
      requiredEn: "Required by position",
      optionalHeading: "进阶 · 跨岗认证",
      optionalEn: "Cross-role advanced",
    },
    materials: {
      topStage: "学习资料 · MATERIALS",
      kicker: "ZHAO's · 培训 · 认证 · 资料",
      title: "学习",
      titleEm: "资料",
      titleSuffix: "。",
      lede: "资料按岗位分组——每个岗位有自己的必读清单、可选进阶和考核题库。切换上方的岗位标签,就像走进不同的「档案柜」。",
      stepLabel: "STEP 03",
      stepDetail: "LIBRARY · 按岗位组织 · BY JOB POSITION",
      metrics: [
        { value: "14", label: "我的岗位 · FOH" },
        { value: "27", label: "TOTAL ITEMS" },
        { value: "6", label: "POSITIONS" },
      ],
      reqLabel: "必修",
      totalLabel: "合计",
      mineLabel: "我的岗位 · HOME",
    },
    permissions: {
      topStage: "权限管理 · PERMISSIONS",
      kicker: "ZHAO's · 培训 · 权限 · 角色",
      title: "权限",
      titleEm: "管理",
      titleSuffix: "。",
      lede: "管理培训模块角色。第一版仅支持 training-admin、training-viewer 和无培训角色。",
      stepLabel: "STEP 04",
      stepDetail: "TRAINING ROLES · 仅培训管理员可见",
      metrics: [
        { value: "2", label: "ROLES" },
        { value: "3", label: "ACTIONS" },
        { value: "RBAC", label: "MODEL" },
      ],
    },
  },
  en: {
    shared: {
      topFamily: "FAMILY",
      topCycle: "WEEK 17 · 2026",
      footer: "Since 2011 — ZHAO's Family Holding",
      backHome: "Back to home",
      courseStatus: {
        in_progress: "IN PROGRESS",
        not_started: "NOT STARTED",
        completed: "COMPLETED",
      },
      courseFilters: {
        all: "All",
        in_progress: "In progress",
        not_started: "Not started",
        completed: "Completed",
      },
      certAction: {
        active: "View certificate →",
        expiring: "Renew now →",
        expired: "Retake exam →",
        available: "Register →",
        locked: "View requirements →",
        revoked: "View reason →",
      },
      certBadge: {
        active: "ACTIVE",
        expiring: "EXPIRING ≤ 30d",
        expired: "EXPIRED",
        revoked: "REVOKED",
        available: "AVAILABLE",
        locked: "LOCKED",
      },
      materialFilters: {
        all: "All",
        req: "Required",
        VIDEO: "Video",
        PDF: "Manual",
        QUIZ: "Quiz",
        ARTICLE: "Article",
        IMAGE: "Image",
        OTHER: "Other",
      },
      empty: "No items found",
      materialSearchPrefix: "Search in",
      materialSearchSuffix: "…",
      materialOpen: "Open →",
      courseAction: {
        in_progress: "Resume course",
        not_started: "Start course",
        completed: "Review again",
      },
    },
    training: {
      topStage: "Training space · TRAINING",
      kicker: "ZHAO's · Training · Certification · Resources",
      title: "Training",
      titleEm: "Space",
      titleSuffix: ".",
      lede: "Your learning path is generated from your role. Complete required courses first, then pick electives. Every session is logged for certification.",
      stepLabel: "STEP 01",
      stepDetail: "ONBOARDING · Front of House · First 14 days",
      metrics: [
        { value: "4/12", label: "REQUIRED" },
        { value: "2.5h", label: "THIS WEEK" },
        { value: "33%", label: "OVERALL" },
      ],
      onboardingKicker: "NEW HIRE · First 14 days · 33% progress",
      onboardingTitle: "Start with 'Safety & Hygiene 101' ↓",
      onboardingDesc: "This is your recommended next step. Takes about 24 minutes. Completing it unlocks the Greeting Standard SOP.",
      onboardingAction: "Continue now",
      requiredHeading: "Required by role",
      requiredEn: "Required by role",
      optionalHeading: "Electives · deep-dive",
      optionalEn: "Optional · deep-dive",
    },
    certifications: {
      topStage: "Certifications · CERTIFICATIONS",
      kicker: "ZHAO's · Training · Certification · Resources",
      title: "Certification",
      titleEm: "Manager",
      titleSuffix: ".",
      lede: "Each certificate represents a verified skill. Unlock them level by level. The system alerts you 30 days before expiry.",
      stepLabel: "STEP 02",
      stepDetail: "CERTIFICATION LADDER · Your skill ladder",
      metrics: [
        { value: "2/6", label: "ACTIVE" },
        { value: "1", label: "EXPIRING ≤ 30d" },
        { value: "3", label: "AVAILABLE" },
      ],
      requiredHeading: "Required by position",
      requiredEn: "Required by position",
      optionalHeading: "Advanced · cross-role",
      optionalEn: "Cross-role advanced",
    },
    materials: {
      topStage: "Learning materials · MATERIALS",
      kicker: "ZHAO's · Training · Certification · Resources",
      title: "Learning",
      titleEm: "Materials",
      titleSuffix: ".",
      lede: "Resources organised by role — each role has its required reading list, optional deep-dives, and quizzes. Switch the tab above to browse a different filing cabinet.",
      stepLabel: "STEP 03",
      stepDetail: "LIBRARY · Organised by job position",
      metrics: [
        { value: "14", label: "MY ROLE · FOH" },
        { value: "27", label: "TOTAL ITEMS" },
        { value: "6", label: "POSITIONS" },
      ],
      reqLabel: "Required",
      totalLabel: "Total",
      mineLabel: "MY ROLE · HOME",
    },
    permissions: {
      topStage: "Permissions · PERMISSIONS",
      kicker: "ZHAO's · Training · Permissions · Roles",
      title: "Permission",
      titleEm: "Manager",
      titleSuffix: ".",
      lede: "Manage training module roles. This first version supports training-admin, training-viewer, and no training role.",
      stepLabel: "STEP 04",
      stepDetail: "TRAINING ROLES · Admin only",
      metrics: [
        { value: "2", label: "ROLES" },
        { value: "3", label: "ACTIONS" },
        { value: "RBAC", label: "MODEL" },
      ],
    },
  },
  fr: {
    shared: {
      topFamily: "FAMILY",
      topCycle: "SEMAINE 17 · 2026",
      footer: "Since 2011 — ZHAO's Family Holding",
      backHome: "Retour à l'accueil",
      courseStatus: {
        in_progress: "EN COURS · IN PROGRESS",
        not_started: "NON COMMENCÉ · NOT STARTED",
        completed: "TERMINÉ · COMPLETED",
      },
      courseFilters: {
        all: "Tout",
        in_progress: "En cours",
        not_started: "Non commencé",
        completed: "Terminé",
      },
      certAction: {
        active: "Voir le certificat →",
        expiring: "Renouveler →",
        expired: "Repasser l'examen →",
        available: "S'inscrire →",
        locked: "Voir les conditions →",
        revoked: "Voir la raison →",
      },
      certBadge: {
        active: "ACTIF · ACTIVE",
        expiring: "EXPIRE ≤ 30j · EXPIRING",
        expired: "EXPIRÉ · EXPIRED",
        revoked: "RÉVOQUÉ · REVOKED",
        available: "DISPONIBLE · AVAILABLE",
        locked: "VERROUILLÉ · LOCKED",
      },
      materialFilters: {
        all: "Tout",
        req: "Obligatoire",
        VIDEO: "Vidéo",
        PDF: "Manuel",
        QUIZ: "Quiz",
        ARTICLE: "Article",
        IMAGE: "Image",
        OTHER: "Autre",
      },
      empty: "Aucun résultat",
      materialSearchPrefix: "Rechercher dans",
      materialSearchSuffix: "…",
      materialOpen: "Ouvrir →",
      courseAction: {
        in_progress: "Reprendre",
        not_started: "Commencer",
        completed: "Revoir",
      },
    },
    training: {
      topStage: "Espace formation · TRAINING",
      kicker: "ZHAO's · Formation · Certification · Ressources",
      title: "Espace",
      titleEm: "Formation",
      titleSuffix: ".",
      lede: "Votre parcours est généré depuis votre poste. Finissez d'abord les cours obligatoires, puis choisissez vos électifs. Chaque session est enregistrée pour les certifications.",
      stepLabel: "ÉTAPE 01",
      stepDetail: "ONBOARDING · Service en salle · 14 premiers jours",
      metrics: [
        { value: "4/12", label: "OBLIGATOIRES" },
        { value: "2.5h", label: "CETTE SEMAINE" },
        { value: "33%", label: "PROGRESSION" },
      ],
      onboardingKicker: "NOUVEL EMPLOYÉ · 14 premiers jours · 33% complété",
      onboardingTitle: "Commencez par « Sécurité & Hygiène » ↓",
      onboardingDesc: "C'est votre prochaine étape recommandée. Environ 24 minutes. Une fois terminé, vous débloquez le SOP d'accueil client.",
      onboardingAction: "Continuer",
      requiredHeading: "Cours obligatoires",
      requiredEn: "Required by role",
      optionalHeading: "Électifs · approfondissement",
      optionalEn: "Optional · deep-dive",
    },
    certifications: {
      topStage: "Certifications · CERTIFICATIONS",
      kicker: "ZHAO's · Formation · Certification · Ressources",
      title: "Gestion des",
      titleEm: "Certifications",
      titleSuffix: ".",
      lede: "Chaque certificat représente une compétence validée. Débloquez-les niveau par niveau. Le système vous alerte 30 jours avant expiration.",
      stepLabel: "ÉTAPE 02",
      stepDetail: "CERTIFICATION LADDER · Votre échelle de compétences",
      metrics: [
        { value: "2/6", label: "ACTIFS" },
        { value: "1", label: "EXPIRE ≤ 30j" },
        { value: "3", label: "DISPONIBLES" },
      ],
      requiredHeading: "Certifications requises",
      requiredEn: "Required by position",
      optionalHeading: "Avancé · inter-postes",
      optionalEn: "Cross-role advanced",
    },
    materials: {
      topStage: "Ressources · MATERIALS",
      kicker: "ZHAO's · Formation · Certification · Ressources",
      title: "Supports",
      titleEm: "Formation",
      titleSuffix: ".",
      lede: "Les ressources sont organisées par poste — chaque poste a sa liste obligatoire, ses électifs et ses quiz. Changez l'onglet ci-dessus pour parcourir un autre « classeur ».",
      stepLabel: "ÉTAPE 03",
      stepDetail: "BIBLIOTHÈQUE · Organisé par poste",
      metrics: [
        { value: "14", label: "MON POSTE · FOH" },
        { value: "27", label: "TOTAL ITEMS" },
        { value: "6", label: "POSTES" },
      ],
      reqLabel: "Obligatoire",
      totalLabel: "Total",
      mineLabel: "MON POSTE · HOME",
    },
    permissions: {
      topStage: "Permissions · PERMISSIONS",
      kicker: "ZHAO's · Formation · Permissions · Rôles",
      title: "Gestion des",
      titleEm: "Permissions",
      titleSuffix: ".",
      lede: "Gérez les rôles du module formation. Cette première version prend en charge training-admin, training-viewer et aucun rôle formation.",
      stepLabel: "ÉTAPE 04",
      stepDetail: "TRAINING ROLES · Admin uniquement",
      metrics: [
        { value: "2", label: "RÔLES" },
        { value: "3", label: "ACTIONS" },
        { value: "RBAC", label: "MODEL" },
      ],
    },
  },
};
