export const ABC_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "ABC 检查",
    topCycle: "等级评级后台",
    kicker: "ABC 门店等级评级",
    title: "门店 ",
    titleEm: "ABC",
    titleSuffix: " 检查管理",
    lede: "每次检查直接评定 A、B 或 C 级，记录改进重点并上传仅供总部及管理层查阅的检查报告。",
    cycleLabel: "当前周期",
    noCycle: "暂无检查周期，请先创建一个。",
    createCycle: "新建周期",
    createCyclePlaceholder: "周期名称，如 2026 年 6 月",
    create: "创建",
    cancel: "取消",
    loading: "加载中…",
    loadError: "加载失败，请稍后重试。",
    saveError: "保存失败，请重试。",
    progressInspections: "已完成检查",
    statusDraft: "填写中",
    statusPublished: "已发布",
    tableStore: "门店",
    tableReport: "检查报告",
    tableGrade: "评级",
    tableNotes: "改进重点",
    tableActions: "操作",
    gradeLabel: "评级 (A/B/C)",
    gradeNone: "未评级",
    gradeGroupLabel: (grade, count) => `${grade}级门店（${count} 家）`,
    notFilled: "未填写",
    edit: "填写",
    save: "保存",
    recordInspection: "记录检查结果",
    notes: "改进重点",
    notesPlaceholder: "填写需要持续改进的事项…",
    uploadReport: "上传报告",
    uploading: "上传中…",
    viewReport: "查看",
    preview: "预览未发布评级榜",
    previewTitle: "未发布评级榜预览",
    closePreview: "关闭预览",
    publish: "归档检查周期",
    publishConfirm: "确认归档该检查周期？归档后将不可再修改检查结果。",
    publishedHint: "该检查周期已归档，结果为只读。",
    deleteCycle: "删除周期",
    deleteConfirm: "确认删除该周期？将一并删除其全部检查结果与报告，且不可恢复。",
    publishSuccess: "检查周期已归档",
    deleteSuccess: "周期已删除",
    back: "返回控制台",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "ABC INSPECTIONS",
    topCycle: "GRADE ADMIN",
    kicker: "ABC STORE GRADES",
    title: "Store ",
    titleEm: "ABC",
    titleSuffix: " inspections",
    lede: "Each inspection assigns an A, B, or C grade, records improvement priorities, and keeps reports visible only to headquarters and management.",
    cycleLabel: "Current cycle",
    noCycle: "No inspection cycle yet — create one to start.",
    createCycle: "New cycle",
    createCyclePlaceholder: "Cycle name, e.g. June 2026",
    create: "Create",
    cancel: "Cancel",
    loading: "Loading…",
    loadError: "Failed to load. Please retry.",
    saveError: "Save failed. Please retry.",
    progressInspections: "Inspections completed",
    statusDraft: "In progress",
    statusPublished: "Published",
    tableStore: "Store",
    tableReport: "Inspection report",
    tableGrade: "Grade",
    tableNotes: "Improvement priorities",
    tableActions: "Actions",
    gradeLabel: "Grade (A/B/C)",
    gradeNone: "Ungraded",
    gradeGroupLabel: (grade, count) => `${grade} stores (${count})`,
    notFilled: "Not filled",
    edit: "Fill",
    save: "Save",
    recordInspection: "Record inspection",
    notes: "Improvement priorities",
    notesPlaceholder: "Items requiring continued improvement…",
    uploadReport: "Upload report",
    uploading: "Uploading…",
    viewReport: "View",
    preview: "Preview unpublished grades",
    previewTitle: "Unpublished grade preview",
    closePreview: "Close preview",
    publish: "Archive inspection cycle",
    publishConfirm: "Archive this inspection cycle? Results become read-only after archiving.",
    publishedHint: "This inspection cycle is archived — results are read-only.",
    deleteCycle: "Delete cycle",
    deleteConfirm:
      "Delete this cycle? All its inspection results and reports will be removed permanently.",
    publishSuccess: "Inspection cycle archived",
    deleteSuccess: "Cycle deleted",
    back: "Back to dashboard",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "INSPECTIONS ABC",
    topCycle: "ADMIN NIVEAUX",
    kicker: "NIVEAUX DES BOUTIQUES ABC",
    title: "Notation ",
    titleEm: "ABC",
    titleSuffix: " des boutiques",
    lede: "Chaque inspection attribue un niveau A, B ou C, consigne les axes d'amélioration et réserve les rapports au siège et à l'encadrement.",
    cycleLabel: "Cycle courant",
    noCycle: "Aucun cycle d'inspection — créez-en un pour commencer.",
    createCycle: "Nouveau cycle",
    createCyclePlaceholder: "Nom du cycle, ex. Juin 2026",
    create: "Créer",
    cancel: "Annuler",
    loading: "Chargement…",
    loadError: "Échec du chargement. Réessayez.",
    saveError: "Échec de l'enregistrement. Réessayez.",
    progressInspections: "Inspections terminées",
    statusDraft: "En cours",
    statusPublished: "Publié",
    tableStore: "Boutique",
    tableReport: "Rapport d'inspection",
    tableGrade: "Note",
    tableNotes: "Axes d'amélioration",
    tableActions: "Actions",
    gradeLabel: "Note (A/B/C)",
    gradeNone: "Non noté",
    gradeGroupLabel: (grade, count) => `Boutiques ${grade} (${count})`,
    notFilled: "Non saisi",
    edit: "Saisir",
    save: "Enregistrer",
    recordInspection: "Enregistrer l'inspection",
    notes: "Axes d'amélioration",
    notesPlaceholder: "Points à améliorer durablement…",
    uploadReport: "Téléverser le rapport",
    uploading: "Envoi…",
    viewReport: "Voir",
    preview: "Aperçu des niveaux non publiés",
    previewTitle: "Aperçu des niveaux non publiés",
    closePreview: "Fermer l'aperçu",
    publish: "Archiver le cycle d'inspection",
    publishConfirm:
      "Archiver ce cycle d'inspection ? Les résultats ne pourront plus être modifiés.",
    publishedHint: "Ce cycle d'inspection est archivé — résultats en lecture seule.",
    deleteCycle: "Supprimer le cycle",
    deleteConfirm:
      "Supprimer ce cycle ? Tous ses résultats d'inspection et rapports seront supprimés définitivement.",
    publishSuccess: "Cycle d'inspection archivé",
    deleteSuccess: "Cycle supprimé",
    back: "Retour au tableau de bord",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
};
