export const ABC_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "ABC 评分",
    topCycle: "排行榜后台",
    kicker: "ABC 评分排行榜",
    title: "门店 ",
    titleEm: "ABC",
    titleSuffix: " 评分管理",
    lede: "营销部依据 Google 评论与伙伴优秀案例打分，营运部填写稽核评分并上传报告。发布前可模拟预览排行榜。",
    cycleLabel: "当前周期",
    noCycle: "暂无评分周期，请先创建一个。",
    createCycle: "新建周期",
    createCyclePlaceholder: "周期名称，如 2026 年 6 月",
    create: "创建",
    cancel: "取消",
    loading: "加载中…",
    loadError: "加载失败，请稍后重试。",
    saveError: "保存失败，请重试。",
    progressMarketing: "营销部",
    progressOperations: "营运部",
    statusDraft: "填写中",
    statusPublished: "已发布",
    tableStore: "门店",
    tableMarketing: "营销分",
    tableOperations: "稽核分",
    tableReport: "评分报告",
    tableGrade: "评级",
    tableTotal: "总分",
    gradeLabel: "评级 (A/B/C)",
    gradeNone: "未评级",
    notFilled: "未填写",
    edit: "填写",
    save: "保存",
    score: "分数 (0-100)",
    notes: "备注",
    notesPlaceholder: "可填写评分依据…",
    uploadReport: "上传报告",
    uploading: "上传中…",
    viewReport: "查看",
    preview: "模拟预览排行榜",
    previewTitle: "排行榜预览（未发布）",
    closePreview: "关闭",
    rank: "排名",
    grade: "评级",
    publish: "发布排行榜",
    publishConfirm: "确认发布该周期排行榜？发布后将不可再修改分数。",
    publishedHint: "该周期已发布，分数为只读。",
    back: "返回控制台",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "ABC SCORING",
    topCycle: "LEADERBOARD ADMIN",
    kicker: "ABC SCORE LEADERBOARD",
    title: "Store ",
    titleEm: "ABC",
    titleSuffix: " scoring",
    lede: "Marketing scores from Google reviews and partner cases; Operations fills audit scores and uploads reports. Preview the leaderboard before publishing.",
    cycleLabel: "Current cycle",
    noCycle: "No scoring cycle yet — create one to start.",
    createCycle: "New cycle",
    createCyclePlaceholder: "Cycle name, e.g. June 2026",
    create: "Create",
    cancel: "Cancel",
    loading: "Loading…",
    loadError: "Failed to load. Please retry.",
    saveError: "Save failed. Please retry.",
    progressMarketing: "Marketing",
    progressOperations: "Operations",
    statusDraft: "In progress",
    statusPublished: "Published",
    tableStore: "Store",
    tableMarketing: "Marketing",
    tableOperations: "Audit",
    tableReport: "Report",
    tableGrade: "Grade",
    tableTotal: "Total",
    gradeLabel: "Grade (A/B/C)",
    gradeNone: "Ungraded",
    notFilled: "Not filled",
    edit: "Fill",
    save: "Save",
    score: "Score (0-100)",
    notes: "Notes",
    notesPlaceholder: "Scoring rationale…",
    uploadReport: "Upload report",
    uploading: "Uploading…",
    viewReport: "View",
    preview: "Preview leaderboard",
    previewTitle: "Leaderboard preview (unpublished)",
    closePreview: "Close",
    rank: "Rank",
    grade: "Grade",
    publish: "Publish leaderboard",
    publishConfirm:
      "Publish this cycle's leaderboard? Scores become read-only after publishing.",
    publishedHint: "This cycle is published — scores are read-only.",
    back: "Back to dashboard",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "NOTATION ABC",
    topCycle: "ADMIN CLASSEMENT",
    kicker: "CLASSEMENT ABC",
    title: "Notation ",
    titleEm: "ABC",
    titleSuffix: " des boutiques",
    lede: "Le marketing note selon les avis Google et les cas partenaires ; l'exploitation saisit l'audit et téléverse les rapports. Aperçu du classement avant publication.",
    cycleLabel: "Cycle courant",
    noCycle: "Aucun cycle de notation — créez-en un pour commencer.",
    createCycle: "Nouveau cycle",
    createCyclePlaceholder: "Nom du cycle, ex. Juin 2026",
    create: "Créer",
    cancel: "Annuler",
    loading: "Chargement…",
    loadError: "Échec du chargement. Réessayez.",
    saveError: "Échec de l'enregistrement. Réessayez.",
    progressMarketing: "Marketing",
    progressOperations: "Exploitation",
    statusDraft: "En cours",
    statusPublished: "Publié",
    tableStore: "Boutique",
    tableMarketing: "Marketing",
    tableOperations: "Audit",
    tableReport: "Rapport",
    tableGrade: "Note",
    tableTotal: "Total",
    gradeLabel: "Note (A/B/C)",
    gradeNone: "Non noté",
    notFilled: "Non saisi",
    edit: "Saisir",
    save: "Enregistrer",
    score: "Note (0-100)",
    notes: "Remarques",
    notesPlaceholder: "Justification de la note…",
    uploadReport: "Téléverser le rapport",
    uploading: "Envoi…",
    viewReport: "Voir",
    preview: "Aperçu du classement",
    previewTitle: "Aperçu du classement (non publié)",
    closePreview: "Fermer",
    rank: "Rang",
    grade: "Note",
    publish: "Publier le classement",
    publishConfirm:
      "Publier le classement de ce cycle ? Les notes deviennent non modifiables après publication.",
    publishedHint: "Ce cycle est publié — notes en lecture seule.",
    back: "Retour au tableau de bord",
    footer: "Since 2011 — ZHAO's Family Holding",
  },
};
