import { StyleSheet } from "react-native";
import { scaleStyles } from "@/lib/responsive";
import { authControlStyles } from "@/features/auth/AuthFormControls";

export const trainingStyles = StyleSheet.create(
  scaleStyles({
    card: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 10,
      padding: 14,
    },
    cardDescription: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
    },
    cardHeader: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 12,
      justifyContent: "space-between",
    },
    cardMeta: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    cardOpenText: {
      alignSelf: "flex-start",
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    cardProgressTrack: {
      backgroundColor: "rgba(10, 10, 10, 0.08)",
      height: 5,
      overflow: "hidden",
    },
    cardProgressValue: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    cardTitle: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 23,
    },
    container: {
      gap: 18,
      paddingTop: 22,
    },
    heroPanel: {
      backgroundColor: "#ffffff",
      borderColor: "rgba(193, 22, 22, 0.22)",
      borderWidth: 1,
      gap: 14,
      padding: 18,
    },
    heroPanelIntro: {
      backgroundColor: "rgba(193, 22, 22, 0.04)",
    },
    heroPanelCompleted: {
      backgroundColor: "rgba(193, 22, 22, 0.06)",
    },
    heroTopRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    heroSeal: {
      alignItems: "center",
      backgroundColor: "rgba(193, 22, 22, 0.08)",
      borderColor: "rgba(193, 22, 22, 0.28)",
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 34,
      minWidth: 72,
      paddingHorizontal: 10,
      transform: [{ rotate: "-4deg" }],
    },
    heroSealCompleted: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    heroSealText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    heroSealTextCompleted: {
      color: "#ffffff",
    },
    heroTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 28,
      fontWeight: "700",
      lineHeight: 34,
    },
    heroBody: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    heroProgressHeader: {
      alignItems: "baseline",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    heroProgressLabel: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    heroProgressValue: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 30,
      fontWeight: "700",
      lineHeight: 34,
    },
    heroProgressTrack: {
      backgroundColor: "rgba(193, 22, 22, 0.12)",
      height: 8,
      overflow: "hidden",
    },
    heroProgressFill: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    heroStatRow: {
      flexDirection: "row",
      gap: 10,
    },
    heroStatCard: {
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flex: 1,
      gap: 4,
      padding: 10,
    },
    heroStatLabel: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 9.5,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    heroStatValue: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
    },
    heroActionRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 12,
    },
    heroFootnote: {
      color: authControlStyles.colors.ink60,
      flex: 1,
      fontFamily: "serif",
      fontSize: 12,
      lineHeight: 18,
    },
    heroPrimaryButton: {
      alignItems: "center",
      backgroundColor: authControlStyles.colors.red,
      justifyContent: "center",
      minHeight: 46,
      paddingHorizontal: 16,
    },
    heroPrimaryButtonText: {
      color: "#ffffff",
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    viewerRoot: {
      backgroundColor: "#ffffff",
      flex: 1,
      position: "relative",
    },
    viewerHeader: {
      alignItems: "center",
      borderBottomColor: authControlStyles.colors.ink10,
      borderBottomWidth: 1,
      flexDirection: "row",
      gap: 12,
      justifyContent: "space-between",
      padding: 14,
    },
    viewerHeaderTitleGroup: {
      flex: 1,
      gap: 4,
    },
    viewerHeaderMeta: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    viewerHeaderTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 23,
    },
    viewerProgressBar: {
      backgroundColor: "rgba(193, 22, 22, 0.12)",
      height: 6,
      overflow: "hidden",
    },
    viewerProgressFill: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    viewerBody: {
      flex: 1,
    },
    viewerFooter: {
      borderTopColor: authControlStyles.colors.ink10,
      borderTopWidth: 1,
      gap: 10,
      padding: 16,
    },
    viewerFooterHint: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
      textAlign: "center",
    },
    viewerConfirmActions: {
      flexDirection: "row",
      gap: 12,
      justifyContent: "flex-end",
    },
    viewerConfirmBackdrop: {
      alignItems: "center",
      backgroundColor: "rgba(10, 10, 10, 0.52)",
      bottom: 0,
      justifyContent: "center",
      left: 0,
      padding: 24,
      position: "absolute",
      right: 0,
      top: 0,
      zIndex: 20,
    },
    viewerConfirmButton: {
      borderWidth: 1,
      minHeight: 40,
      justifyContent: "center",
      paddingHorizontal: 18,
    },
    viewerConfirmCancelButton: {
      backgroundColor: "#ffffff",
      borderColor: "rgba(10, 10, 10, 0.2)",
    },
    viewerConfirmCancelText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
    },
    viewerConfirmCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.red,
      borderWidth: 1,
      maxWidth: 420,
      padding: 22,
      width: "100%",
    },
    viewerConfirmMessage: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 20,
    },
    viewerConfirmOkButton: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    viewerConfirmOkText: {
      color: "#ffffff",
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    viewerConfirmTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 23,
      marginBottom: 8,
    },
    badgeUnlockBackdrop: {
      alignItems: "center",
      backgroundColor: "rgba(10, 10, 10, 0.56)",
      flex: 1,
      justifyContent: "center",
      padding: 24,
    },
    badgeUnlockCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 14,
      maxHeight: "82%",
      maxWidth: 460,
      padding: 24,
      width: "100%",
    },
    badgeUnlockKicker: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      textAlign: "center",
    },
    badgeUnlockTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 26,
      fontWeight: "700",
      lineHeight: 31,
      textAlign: "center",
    },
    badgeUnlockIntro: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 20,
      textAlign: "center",
    },
    badgeUnlockList: {
      gap: 14,
    },
    badgeUnlockItem: {
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
    },
    badgeUnlockName: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 21,
      fontWeight: "700",
      lineHeight: 24,
      textAlign: "center",
    },
    badgeUnlockDescription: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
      textAlign: "center",
    },
    badgeUnlockReason: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
      textAlign: "center",
    },
    badgeUnlockDetailsButton: {
      alignItems: "center",
      flexDirection: "row",
      gap: 4,
      minHeight: 36,
      paddingHorizontal: 8,
    },
    badgeUnlockDetailsText: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 13,
      fontWeight: "700",
    },
    badgeUnlockRequirements: {
      alignSelf: "stretch",
      backgroundColor: "rgba(10, 10, 10, 0.035)",
      gap: 6,
      padding: 12,
    },
    badgeUnlockRequirement: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
    },
    badgeUnlockCloseButton: {
      alignItems: "center",
      backgroundColor: authControlStyles.colors.red,
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: 16,
    },
    badgeUnlockCloseText: {
      color: "#ffffff",
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    viewerCompletedBadge: {
      alignItems: "center",
      backgroundColor: "rgba(25, 122, 61, 0.08)",
      borderColor: authControlStyles.colors.success,
      borderWidth: 1,
      gap: 6,
      padding: 12,
    },
    viewerCompletedText: {
      color: authControlStyles.colors.success,
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1,
      textAlign: "center",
      textTransform: "uppercase",
    },
    viewerLoadingOverlay: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.92)",
      bottom: 0,
      justifyContent: "center",
      left: 0,
      padding: 20,
      position: "absolute",
      right: 0,
      top: 0,
    },
    viewerErrorOverlay: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.96)",
      bottom: 0,
      gap: 12,
      justifyContent: "center",
      left: 0,
      padding: 20,
      position: "absolute",
      right: 0,
      top: 0,
    },
    positionsBoard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 10,
      padding: 14,
    },
    focusCard: {
      backgroundColor: "rgba(193, 22, 22, 0.04)",
      borderColor: "rgba(193, 22, 22, 0.22)",
      borderWidth: 1,
      gap: 10,
      padding: 16,
    },
    focusHeader: {
      alignItems: "baseline",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    focusStepLabel: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    focusTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 24,
      fontWeight: "700",
      lineHeight: 29,
    },
    focusDescription: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    focusMeta: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10.5,
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    focusHint: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 12,
      lineHeight: 18,
    },
    journeyGroups: {
      gap: 20,
    },
    journeyGroup: {
      gap: 12,
    },
    journeyGroupChevron: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 13,
      fontWeight: "700",
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    journeyGroupChevronExpanded: {
      color: authControlStyles.colors.red,
    },
    journeyGroupHeader: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderLeftColor: authControlStyles.colors.red,
      borderLeftWidth: 2,
      borderWidth: 1,
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    journeyGroupHeaderExpanded: {
      borderColor: authControlStyles.colors.red,
    },
    journeyGroupHeaderPressed: {
      backgroundColor: authControlStyles.colors.ink05,
    },
    journeyGroupHeaderRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      justifyContent: "space-between",
    },
    journeyGroupMetaRow: {
      alignItems: "center",
      flexDirection: "row",
      flexShrink: 0,
      gap: 8,
    },
    journeyGroupProgressTrack: {
      backgroundColor: authControlStyles.colors.ink10,
      height: 5,
      overflow: "hidden",
    },
    journeyGroupProgressValue: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    journeyGroupTitle: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1.2,
      textTransform: "uppercase",
    },
    journeyGroupCount: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 11,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    journeyList: {
      gap: 12,
    },
    journeyRow: {
      alignItems: "stretch",
      flexDirection: "row",
      gap: 12,
    },
    journeyRail: {
      alignItems: "center",
      width: 34,
    },
    journeyMarker: {
      alignItems: "center",
      backgroundColor: "#ffffff",
      borderColor: "rgba(193, 22, 22, 0.28)",
      borderRadius: 18,
      borderWidth: 1,
      height: 36,
      justifyContent: "center",
      width: 36,
    },
    journeyMarkerCurrent: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    journeyMarkerCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.12)",
      borderColor: authControlStyles.colors.success,
    },
    journeyMarkerLocked: {
      backgroundColor: authControlStyles.colors.ink05,
      borderColor: authControlStyles.colors.ink20,
    },
    journeyMarkerText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.8,
    },
    journeyMarkerTextCurrent: {
      color: "#ffffff",
    },
    journeyMarkerTextCompleted: {
      color: authControlStyles.colors.success,
    },
    journeyMarkerTextLocked: {
      color: authControlStyles.colors.ink40,
    },
    journeyLine: {
      backgroundColor: authControlStyles.colors.ink10,
      flex: 1,
      marginVertical: 4,
      width: 2,
    },
    journeyLineCompleted: {
      backgroundColor: authControlStyles.colors.success,
    },
    journeyLineLocked: {
      backgroundColor: authControlStyles.colors.ink10,
    },
    journeyCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flex: 1,
      gap: 9,
      padding: 14,
    },
    journeyCardCurrent: {
      backgroundColor: "rgba(193, 22, 22, 0.04)",
      borderColor: authControlStyles.colors.red,
    },
    journeyCardCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.05)",
      borderColor: authControlStyles.colors.success,
    },
    journeyCardLocked: {
      backgroundColor: authControlStyles.colors.ink05,
      opacity: 0.72,
    },
    journeyCardHeader: {
      gap: 8,
    },
    journeyBadgeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    journeyStatusPill: {
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    journeyStatusPillCurrent: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    journeyStatusPillCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.10)",
      borderColor: authControlStyles.colors.success,
    },
    journeyStatusPillLocked: {
      backgroundColor: authControlStyles.colors.ink05,
      borderColor: authControlStyles.colors.ink20,
    },
    journeyStatusText: {
      fontFamily: "monospace",
      fontSize: 9.5,
      fontWeight: "700",
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    journeyStatusTextCurrent: {
      color: "#ffffff",
    },
    journeyStatusTextCompleted: {
      color: authControlStyles.colors.success,
    },
    journeyStatusTextLocked: {
      color: authControlStyles.colors.ink40,
    },
    journeyTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 23,
    },
    journeyDescription: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
    },
    journeyMeta: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    journeyProgressTrack: {
      backgroundColor: "rgba(193, 22, 22, 0.12)",
      height: 6,
      overflow: "hidden",
    },
    journeyProgressValue: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    journeyFooter: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    journeyFooterLocked: {
      color: authControlStyles.colors.ink40,
    },
    libraryCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 10,
      padding: 14,
    },
    libraryCardHeader: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 12,
      justifyContent: "space-between",
    },
    libraryCardTitle: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 17,
      fontWeight: "700",
      lineHeight: 22,
    },
    libraryCardDescription: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
    },
    libraryCardMeta: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    libraryCardFooter: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    emptyText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    header: {
      gap: 9,
    },
    intro: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 15,
      lineHeight: 22,
    },
    list: {
      gap: 10,
    },
    message: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    pill: {
      borderColor: "rgba(193, 22, 22, 0.28)",
      borderWidth: 1,
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
    pillRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 7,
    },
    pillText: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 12,
    },
    filterPillActive: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    filterPillTextActive: {
      color: "#ffffff",
    },
    progressCard: {
      backgroundColor: "#ffffff",
      borderColor: "rgba(193, 22, 22, 0.28)",
      borderWidth: 1,
      gap: 14,
      padding: 16,
    },
    progressHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    progressLabel: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1.4,
      textTransform: "uppercase",
    },
    progressTrack: {
      backgroundColor: "rgba(193, 22, 22, 0.12)",
      height: 8,
      overflow: "hidden",
    },
    progressValue: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    progressNumber: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 44,
      fontWeight: "700",
      lineHeight: 48,
    },
    completedBadgeText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1,
      textAlign: "center",
      textTransform: "uppercase",
    },
    markCompleteButton: {
      alignItems: "center",
      backgroundColor: authControlStyles.colors.red,
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: 16,
    },
    markCompleteButtonDisabled: {
      opacity: 0.4,
    },
    markCompleteButtonText: {
      color: "#ffffff",
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    markCompleteHint: {
      color: authControlStyles.colors.ink40,
      fontFamily: "serif",
      fontSize: 12,
      lineHeight: 17,
      textAlign: "center",
    },
    previewBody: {
      flex: 1,
      position: "relative",
    },
    previewFooter: {
      borderTopColor: authControlStyles.colors.ink10,
      borderTopWidth: 1,
      gap: 8,
      padding: 14,
    },
    syncFailedText: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 12,
      lineHeight: 17,
      textAlign: "center",
    },
    previewCloseButton: {
      alignItems: "center",
      borderColor: authControlStyles.colors.red,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 36,
      paddingHorizontal: 10,
    },
    previewHeader: {
      alignItems: "center",
      borderBottomColor: authControlStyles.colors.ink10,
      borderBottomWidth: 1,
      flexDirection: "row",
      gap: 12,
      justifyContent: "space-between",
      padding: 14,
    },
    previewImage: {
      backgroundColor: "#ffffff",
      flex: 1,
      height: "100%",
      width: "100%",
    },
    previewModalRoot: {
      backgroundColor: "rgba(10, 10, 10, 0.22)",
      flex: 1,
      justifyContent: "flex-end",
    },
    previewOverlay: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.86)",
      bottom: 0,
      gap: 12,
      justifyContent: "center",
      left: 0,
      padding: 20,
      position: "absolute",
      right: 0,
      top: 0,
    },
    previewPanel: {
      backgroundColor: "#ffffff",
      borderColor: "rgba(193, 22, 22, 0.22)",
      borderTopWidth: 1,
      height: "88%",
      overflow: "hidden",
      width: "100%",
    },
    previewTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 23,
    },
    previewTitleGroup: {
      flex: 1,
      gap: 4,
    },
    previewWebView: {
      flex: 1,
    },
    refreshButton: {
      alignSelf: "flex-start",
      borderColor: authControlStyles.colors.red,
      borderWidth: 1,
      minHeight: 38,
      justifyContent: "center",
      paddingHorizontal: 12,
    },
    refreshButtonText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
    },
    section: {
      gap: 10,
    },
    sectionHeader: {
      alignItems: "baseline",
      flexDirection: "row",
      gap: 8,
      justifyContent: "space-between",
    },
    sectionTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 23,
      fontWeight: "700",
    },
    sectionCount: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 11,
    },
    statGrid: {
      flexDirection: "row",
      gap: 10,
    },
    statItem: {
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flex: 1,
      gap: 4,
      padding: 10,
    },
    statLabel: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 9.5,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    statValue: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
    },
    statusPill: {
      backgroundColor: "rgba(193, 22, 22, 0.08)",
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    statusText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 9.5,
      fontWeight: "700",
      letterSpacing: 0.8,
    },
    title: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 34,
      fontWeight: "700",
      lineHeight: 39,
    },
    typeText: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
    },
    segment: {
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flexDirection: "row",
    },
    segmentItem: {
      alignItems: "center",
      flex: 1,
      paddingVertical: 11,
    },
    segmentItemActive: {
      backgroundColor: authControlStyles.colors.red,
    },
    segmentText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    segmentTextActive: {
      color: "#ffffff",
    },
    sectionSubTitle: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1.2,
      textTransform: "uppercase",
    },
    quizScroll: {
      gap: 16,
      padding: 16,
    },
    quizLangRow: {
      flexDirection: "row",
      gap: 8,
    },
    quizLangChip: {
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    quizLangChipActive: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    quizLangChipText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      fontWeight: "700",
    },
    quizLangChipTextActive: {
      color: "#ffffff",
    },
    quizCenter: {
      alignItems: "center",
      flex: 1,
      gap: 14,
      justifyContent: "center",
      padding: 24,
    },
    quizIntro: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    quizQuestion: {
      gap: 8,
    },
    quizPrompt: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 23,
    },
    quizOption: {
      alignItems: "center",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flexDirection: "row",
      gap: 10,
      padding: 12,
    },
    quizOptionSelected: {
      borderColor: authControlStyles.colors.red,
    },
    quizOptionCorrect: {
      backgroundColor: "rgba(31,122,90,0.10)",
      borderColor: "#1f7a5a",
    },
    quizOptionWrong: {
      backgroundColor: "rgba(193,22,22,0.08)",
      borderColor: authControlStyles.colors.red,
    },
    quizRadio: {
      borderColor: authControlStyles.colors.ink40,
      borderRadius: 9,
      borderWidth: 2,
      height: 18,
      width: 18,
    },
    quizCheckbox: {
      borderColor: authControlStyles.colors.ink40,
      borderWidth: 2,
      height: 18,
      width: 18,
    },
    quizMarkSelected: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    quizOptionLabel: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 20,
    },
    quizExplanation: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      fontStyle: "italic",
      lineHeight: 19,
    },
    quizScoreCard: {
      alignItems: "center",
      borderWidth: 1,
      gap: 6,
      padding: 18,
    },
    quizScorePass: {
      backgroundColor: "rgba(31,122,90,0.08)",
      borderColor: "#1f7a5a",
    },
    quizScoreFail: {
      backgroundColor: "rgba(193,22,22,0.06)",
      borderColor: authControlStyles.colors.red,
    },
    quizScoreValue: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 40,
      fontWeight: "700",
      lineHeight: 44,
    },
    quizScoreLabel: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 11,
      letterSpacing: 0.6,
    },
    quizTitlesUnlocked: {
      alignItems: "center",
      gap: 8,
      marginTop: 8,
    },
    quizUnlockLabel: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.8,
    },
    achievementHeroBody: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    historyHeaderPanel: {
      backgroundColor: "#ffffff",
      borderBottomColor: authControlStyles.colors.ink10,
      borderBottomWidth: 1,
      gap: 12,
      padding: 16,
    },
    titleBadgeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    recordCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 6,
      padding: 12,
    },
    recordHeader: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 10,
      justifyContent: "space-between",
    },
    recordTitle: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 15,
      fontWeight: "700",
      lineHeight: 21,
    },
    recordScorePill: {
      backgroundColor: "rgba(31,122,90,0.10)",
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    recordScoreText: {
      color: "#1f7a5a",
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
    },
    recordScorePillFailed: {
      backgroundColor: "rgba(193,22,22,0.08)",
    },
    recordScoreTextFailed: {
      color: authControlStyles.colors.red,
    },
    recordDate: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 0.6,
    },
    recordBadgeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    recordStatusPillPassed: {
      backgroundColor: "rgba(31, 122, 90, 0.10)",
    },
    recordStatusPillFailed: {
      backgroundColor: "rgba(193, 22, 22, 0.08)",
    },
    recordStatusTextPassed: {
      color: authControlStyles.colors.success,
    },
    recordStatusTextFailed: {
      color: authControlStyles.colors.red,
    },
    recordAttemptPill: {
      backgroundColor: "rgba(10, 10, 10, 0.04)",
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    recordAttemptText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 9.5,
      fontWeight: "700",
      letterSpacing: 0.6,
    },

    // ── Map visual styles (three-layer gamified map) ──

    mapHeroPanel: {
      backgroundColor: "#ffffff",
      borderBottomColor: "rgba(193, 22, 22, 0.22)",
      borderBottomWidth: 1,
      borderTopColor: authControlStyles.colors.red,
      borderTopWidth: 3,
      gap: 16,
      padding: 18,
    },
    mapHeroHeader: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 14,
      justifyContent: "space-between",
    },
    mapHeroTitleGroup: {
      flex: 1,
      gap: 6,
    },
    mapHeroKicker: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1.2,
      textTransform: "uppercase",
    },
    mapHeroTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 30,
      fontWeight: "700",
      lineHeight: 35,
    },
    mapHeroIntro: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 14,
      lineHeight: 21,
    },
    mapHeroRefreshButton: {
      alignItems: "center",
      borderColor: "rgba(193, 22, 22, 0.32)",
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 34,
      paddingHorizontal: 12,
    },
    mapHeroRefreshText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapHeroProgressRow: {
      gap: 10,
    },
    mapHeroProgressCopy: {
      alignItems: "baseline",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    mapHeroProgressLabel: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapHeroProgressValue: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 34,
      fontWeight: "700",
      lineHeight: 38,
    },
    mapHeroProgressTrack: {
      backgroundColor: "rgba(193, 22, 22, 0.10)",
      height: 8,
      overflow: "hidden",
    },
    mapHeroProgressFill: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    mapFocusCard: {
      backgroundColor: "rgba(193, 22, 22, 0.045)",
      borderColor: "rgba(193, 22, 22, 0.24)",
      borderLeftColor: authControlStyles.colors.red,
      borderLeftWidth: 3,
      borderWidth: 1,
      gap: 8,
      padding: 14,
    },
    mapFocusCardCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.06)",
      borderColor: "rgba(25, 122, 61, 0.28)",
      borderLeftColor: authControlStyles.colors.success,
      borderLeftWidth: 3,
      borderWidth: 1,
      gap: 8,
      padding: 14,
    },
    mapFocusTopRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 10,
      justifyContent: "space-between",
    },
    mapFocusLabel: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapFocusLayer: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    mapFocusTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 21,
      fontWeight: "700",
      lineHeight: 26,
    },
    mapFocusMeta: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 18,
    },
    mapFocusAction: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapLayerSummaryRow: {
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flexDirection: "row",
    },
    mapLayerSummaryItem: {
      borderRightColor: authControlStyles.colors.ink10,
      borderRightWidth: 1,
      flex: 1,
      gap: 5,
      minHeight: 62,
      paddingHorizontal: 8,
      paddingVertical: 10,
    },
    mapLayerSummaryItemLocked: {
      backgroundColor: authControlStyles.colors.ink05,
    },
    mapLayerSummaryLabel: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase",
    },
    mapLayerSummaryLabelLocked: {
      color: authControlStyles.colors.ink40,
    },
    mapLayerSummaryValue: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 18,
      fontWeight: "700",
    },
    mapLayerSummaryValueLocked: {
      color: authControlStyles.colors.ink40,
    },
    mapContainer: {
      gap: 18,
    },
    mapLayerCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 14,
      overflow: "hidden",
      padding: 16,
    },
    mapLayerCardLocked: {
      backgroundColor: authControlStyles.colors.ink05,
      opacity: 0.78,
    },
    mapLayerHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    mapLayerTitle: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 20,
      fontWeight: "700",
      lineHeight: 25,
    },
    mapLayerTitleLocked: {
      color: authControlStyles.colors.ink40,
    },
    mapLayerBadge: {
      alignItems: "center",
      borderColor: authControlStyles.colors.red,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 26,
      paddingHorizontal: 8,
    },
    mapLayerBadgeDone: {
      backgroundColor: "rgba(25, 122, 61, 0.10)",
      borderColor: authControlStyles.colors.success,
    },
    mapLayerBadgeLocked: {
      borderColor: authControlStyles.colors.ink20,
    },
    mapLayerBadgeText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapLayerBadgeTextDone: {
      color: authControlStyles.colors.success,
    },
    mapLayerBadgeTextLocked: {
      color: authControlStyles.colors.ink40,
    },
    mapLayerBody: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 13,
      lineHeight: 19,
    },
    mapLayerBodyLocked: {
      color: authControlStyles.colors.ink40,
    },
    mapLayerUnlockHint: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      lineHeight: 16,
      textTransform: "uppercase",
    },
    mapLayerProgressTrack: {
      backgroundColor: "rgba(193, 22, 22, 0.12)",
      height: 6,
      overflow: "hidden",
    },
    mapLayerProgressFill: {
      backgroundColor: authControlStyles.colors.red,
      height: "100%",
    },
    mapLayerProgressLabel: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapLayerProgressStats: {
      color: authControlStyles.colors.ink,
      fontFamily: "serif",
      fontSize: 14,
      fontWeight: "700",
    },
    mapNodeList: {
      gap: 12,
      paddingTop: 2,
    },
    mapNodeRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      width: "100%",
    },
    mapNodeRowRight: {
      justifyContent: "flex-start",
    },
    mapNodeCheckpoint: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 11,
      width: "100%",
    },
    mapNodeCheckpointRight: {
      flexDirection: "row",
    },
    mapNodeSeal: {
      alignItems: "center",
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.red,
      borderWidth: 1,
      height: 42,
      justifyContent: "center",
      marginTop: 3,
      width: 42,
    },
    mapNodeSealCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.10)",
      borderColor: authControlStyles.colors.success,
    },
    mapNodeSealText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 1,
    },
    mapNodeSealTextCompleted: {
      color: authControlStyles.colors.success,
      fontSize: 18,
      letterSpacing: 0,
    },
    mapNodePanel: {
      backgroundColor: "#ffffff",
      borderColor: "rgba(10, 10, 10, 0.10)",
      borderLeftColor: authControlStyles.colors.red,
      borderLeftWidth: 3,
      borderWidth: 1,
      flex: 1,
      gap: 10,
      padding: 12,
    },
    mapNodePanelCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.04)",
      borderColor: "rgba(25, 122, 61, 0.30)",
      borderLeftColor: authControlStyles.colors.success,
    },
    mapNodeCard: {
      backgroundColor: "#ffffff",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      gap: 8,
      padding: 12,
    },
    mapNodeCardCompleted: {
      backgroundColor: "rgba(25, 122, 61, 0.04)",
      borderColor: authControlStyles.colors.success,
    },
    mapNodeCardLocked: {
      backgroundColor: authControlStyles.colors.ink05,
      opacity: 0.65,
    },
    mapNodeTitleRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: 10,
      justifyContent: "space-between",
    },
    mapNodeTitleGroup: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    mapNodeTitle: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 21,
    },
    mapNodeDescription: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 12,
      lineHeight: 17,
    },
    mapNodePillRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    mapNodeTypePill: {
      backgroundColor: "rgba(10, 10, 10, 0.04)",
      paddingHorizontal: 7,
      paddingVertical: 3,
    },
    mapNodeTypeText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase",
    },
    mapNodeQuizTag: {
      backgroundColor: "rgba(193, 22, 22, 0.08)",
      paddingHorizontal: 7,
      paddingVertical: 3,
    },
    mapNodeQuizText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 0.6,
    },
    mapNodeActionRow: {
      flexDirection: "row",
      gap: 8,
    },
    mapNodeActionButton: {
      alignItems: "center",
      borderColor: authControlStyles.colors.red,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 32,
      paddingHorizontal: 10,
    },
    mapNodeActionButtonDisabled: {
      opacity: 0.4,
    },
    mapNodeActionButtonDone: {
      backgroundColor: "rgba(25, 122, 61, 0.10)",
      borderColor: authControlStyles.colors.success,
    },
    mapNodeActionText: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 9.5,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapNodeActionTextDone: {
      color: authControlStyles.colors.success,
    },
    mapNodeDoneTag: {
      alignItems: "center",
      backgroundColor: "rgba(25, 122, 61, 0.10)",
      borderColor: authControlStyles.colors.success,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 28,
      paddingHorizontal: 10,
    },
    mapNodeDoneText: {
      color: authControlStyles.colors.success,
      fontFamily: "monospace",
      fontSize: 9.5,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    titleStamp: {
      alignItems: "center",
      borderWidth: 1,
      gap: 6,
      minWidth: 96,
      padding: 14,
    },
    titleStampIcon: {
      fontSize: 20,
    },
    titleStampName: {
      fontFamily: "serif",
      fontSize: 13,
      fontWeight: "700",
      textAlign: "center",
    },
    mapSealIcon: {
      alignItems: "center",
      borderColor: "rgba(193, 22, 22, 0.28)",
      borderWidth: 1,
      height: 34,
      justifyContent: "center",
      transform: [{ rotate: "-4deg" }],
      width: 34,
    },
    mapSealIconDone: {
      backgroundColor: authControlStyles.colors.red,
      borderColor: authControlStyles.colors.red,
    },
    mapSealIconText: {
      color: authControlStyles.colors.red,
      fontFamily: "serif",
      fontSize: 14,
      fontWeight: "700",
    },
    mapSealIconTextDone: {
      color: "#ffffff",
    },
    mapPositionGateHeader: {
      alignItems: "center",
      backgroundColor: "rgba(193, 22, 22, 0.04)",
      borderColor: "rgba(193, 22, 22, 0.28)",
      borderLeftColor: authControlStyles.colors.red,
      borderLeftWidth: 2,
      borderWidth: 1,
      flexDirection: "row",
      gap: 8,
      justifyContent: "space-between",
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    mapPositionGateTitle: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 15,
      fontWeight: "700",
      lineHeight: 20,
    },
    mapPositionGateProgress: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    mapLayerDivider: {
      backgroundColor: "rgba(193, 22, 22, 0.08)",
      height: 1,
      marginVertical: 4,
    },
  }),
);
