import { StyleSheet } from "react-native";
import { authControlStyles } from "@/features/auth/AuthFormControls";

export const trainingStyles = StyleSheet.create({
  card: {
    backgroundColor: "#ffffff",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  cardDescription: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 13,
    lineHeight: 19,
  },
  cardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  cardMeta: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  cardOpenText: {
    alignSelf: "flex-start",
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  cardProgressTrack: {
    backgroundColor: "rgba(10, 10, 10, 0.08)",
    height: 5,
    overflow: "hidden",
  },
  cardProgressValue: {
    backgroundColor: authControlStyles.colors.red,
    height: "100%",
  },
  cardTitle: {
    color: authControlStyles.colors.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 23,
  },
  container: {
    gap: 18,
    paddingTop: 22,
  },
  emptyText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  header: {
    gap: 9,
  },
  intro: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 15,
    lineHeight: 22,
  },
  list: {
    gap: 10,
  },
  message: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  pill: {
    borderColor: "rgba(193, 22, 22, 0.28)",
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  pillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  pillText: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 12,
  },
  progressCard: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(193, 22, 22, 0.28)",
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  progressHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  progressLabel: {
    color: authControlStyles.colors.ink60,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  progressTrack: {
    backgroundColor: "rgba(193, 22, 22, 0.12)",
    height: 8,
    overflow: "hidden",
  },
  progressValue: {
    backgroundColor: authControlStyles.colors.red,
    height: "100%",
  },
  progressNumber: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 44,
    fontWeight: "700",
    lineHeight: 48,
  },
  previewBody: {
    flex: 1,
    position: "relative",
  },
  previewCloseButton: {
    alignItems: "center",
    borderColor: authControlStyles.colors.red,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 10,
  },
  previewHeader: {
    alignItems: "center",
    borderBottomColor: authControlStyles.colors.ink10,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    padding: 14,
  },
  previewImage: {
    backgroundColor: "#ffffff",
    flex: 1,
    height: "100%",
    width: "100%",
  },
  previewModalRoot: {
    backgroundColor: "rgba(10, 10, 10, 0.22)",
    flex: 1,
    justifyContent: "flex-end",
  },
  previewOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    padding: 20,
    position: "absolute",
    right: 0,
    top: 0,
  },
  previewPanel: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(193, 22, 22, 0.22)",
    borderTopWidth: 1,
    height: "88%",
    overflow: "hidden",
    width: "100%",
  },
  previewTitle: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 23,
  },
  previewTitleGroup: {
    flex: 1,
    gap: 4,
  },
  previewWebView: {
    flex: 1,
  },
  refreshButton: {
    alignSelf: "flex-start",
    borderColor: authControlStyles.colors.red,
    borderWidth: 1,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  refreshButtonText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    alignItems: "baseline",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 23,
    fontWeight: "700",
  },
  sectionCount: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 11,
  },
  statGrid: {
    flexDirection: "row",
    gap: 10,
  },
  statItem: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    padding: 10,
  },
  statLabel: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 9.5,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  statValue: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "700",
  },
  statusPill: {
    backgroundColor: "rgba(193, 22, 22, 0.08)",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 9.5,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  title: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 34,
    fontWeight: "700",
    lineHeight: 39,
  },
  typeText: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 1,
  },
});
