import {
  HEADQUARTER_JOB_ROLES,
  MANAGEMENT_JOB_ROLES,
  STORE_MANAGEMENT_JOB_ROLES,
} from "@zhao/utils";

export const DASHBOARD_NAV = [
  {
    id: "menu",
    items: [
      {
        id: "home",
        href: "/dashboard",
        zh: "首页",
        en: "Home",
        fr: "Accueil",
      },
      {
        id: "profile",
        href: "/dashboard/profile",
        zh: "个人资料",
        en: "Profile",
        fr: "Profil",
      },
    ],
  },
  {
    id: "learning",
    items: [
      {
        id: "training-space",
        href: "/dashboard/training",
        zh: "培训空间",
        en: "Training space",
        fr: "Espace formation",
      },
      {
        id: "training-certifications",
        href: "/dashboard/training/certifications",
        zh: "认证管理",
        en: "Certifications",
        fr: "Certifications",
      },
      {
        id: "training-progress",
        href: "/dashboard/training/progress",
        zh: "培训进度",
        en: "Training progress",
        fr: "Progression formation",
        visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES,
      },
      {
        id: "training-materials",
        href: "/dashboard/training/materials",
        zh: "学习资料",
        en: "Learning materials",
        fr: "Ressources",
      },
    ],
  },
  {
    id: "orders",
    items: [
      {
        id: "new-order",
        href: "/dashboard/orders/new",
        zh: "下单",
        en: "Place order",
        fr: "Passer commande",
        visibleForJobRoles: MANAGEMENT_JOB_ROLES,
      },
      {
        id: "order-history",
        href: "/dashboard/orders",
        zh: "历史订单",
        en: "Order history",
        fr: "Historique",
        visibleForJobRoles: MANAGEMENT_JOB_ROLES,
      },
      {
        id: "order-stats",
        href: "/dashboard/orders/stats",
        zh: "商品统计",
        en: "Product stats",
        fr: "Stats produits",
        visibleForJobRoles: MANAGEMENT_JOB_ROLES,
      },
      {
        id: "suppliers",
        href: "/dashboard/suppliers",
        zh: "供应商管理",
        en: "Suppliers",
        fr: "Fournisseurs",
        visibleForJobRoles: ["holding"],
      },
    ],
  },
  {
    id: "people",
    items: [
      {
        id: "recruitment-requests",
        href: "/dashboard/recruitment-requests",
        zh: "招聘请求",
        en: "Recruitment requests",
        fr: "Demandes recrutement",
        requiredPermission: "recruitment.request.manage",
        // Store managers (by job role) also see the entry — the backend scopes
        // their list to their own store. They get the send view (submit + track
        // own requests); only `recruitment.request.manage` unlocks the HQ desk.
        visibleForJobRoles: ["store-manager"],
      },
    ],
  },
  {
    id: "management",
    items: [
      {
        id: "abc-scores",
        href: "/dashboard/abc-scores",
        zh: "ABC 评分排行榜",
        en: "ABC scoreboard",
        fr: "Classement ABC",
        requiredPermission: "abc.score.read",
        // 营销/运营账号靠权限可见；总部（holding/regional）靠岗位兜底，
        // 与「系统角色」入口同样的 OR 双条件。
        visibleForJobRoles: HEADQUARTER_JOB_ROLES,
      },
      {
        id: "case-shares-review",
        href: "/dashboard/case-shares-review",
        zh: "案例审核",
        en: "Case review",
        fr: "Validation des cas",
        requiredPermission: "case.share.review",
      },
      {
        id: "permissions",
        href: "/dashboard/permissions",
        zh: "系统角色",
        en: "System roles",
        fr: "Rôles système",
        requiredPermission: "system.permission.manage",
        visibleForJobRoles: ["holding"],
      },
      {
        id: "stores",
        href: "/dashboard/stores",
        zh: "门店管理",
        en: "Store management",
        fr: "Gestion des boutiques",
        // 仅 holding / regional-manager / store-manager 可见，与后端门店列表放行范围一致。
        visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES,
      },
      {
        id: "training-positions",
        href: "/dashboard/training/positions",
        zh: "岗位管理",
        en: "Positions",
        fr: "Postes",
        // 仅按权限判断：没有 training.position.manage 就隐藏入口，
        // 不再用总部岗位兜底（否则总部账号即使无权限也会看到入口并落到「无权限」页）。
        requiredPermission: "training.position.manage",
      },
      {
        id: "inventory-zhao-bureau",
        href: "/dashboard/inventory",
        zh: "ZHAO Bureau 库存",
        en: "ZHAO Bureau stock",
        fr: "Stock ZHAO Bureau",
        // 仅总部（holding）可见，区域经理等其他岗位不显示此入口。
        visibleForJobRoles: ["holding"],
      },
    ],
  },
];

export const DASHBOARD_NAV_GROUP_LABELS = {
  zh: {
    menu: "菜单模块",
    learning: "学习模块",
    orders: "订单模块",
    people: "人事模块",
    management: "管理模块",
  },
  en: {
    menu: "MENU MODULE",
    learning: "LEARNING MODULE",
    orders: "ORDER MODULE",
    people: "PEOPLE MODULE",
    management: "MANAGEMENT MODULE",
  },
  fr: {
    menu: "MODULE MENU",
    learning: "MODULE FORMATION",
    orders: "MODULE COMMANDES",
    people: "MODULE RH",
    management: "MODULE GESTION",
  },
};

export const DASHBOARD_MENU_LABELS = {
  zh: {
    open: "菜单",
    close: "关闭",
    title: "导航",
    hint: "选择一个模块开始。",
  },
  en: {
    open: "Menu",
    close: "Close",
    title: "Navigation",
    hint: "Pick a module to begin.",
  },
  fr: {
    open: "Menu",
    close: "Fermer",
    title: "Navigation",
    hint: "Choisissez un module pour commencer.",
  },
};

export const USER_CARD_LABELS = {
  zh: {
    kicker: "当前成员 · CURRENT MEMBER",
    storeLabel: "门店",
    roleLabel: "岗位",
    noStore: "尚未分配门店",
    noRole: "岗位待补充",
    noName: "ZHAO 伙伴",
  },
  en: {
    kicker: "CURRENT MEMBER",
    storeLabel: "Store",
    roleLabel: "Role",
    noStore: "No store assigned",
    noRole: "Role to be set",
    noName: "ZHAO partner",
  },
  fr: {
    kicker: "MEMBRE ACTUEL",
    storeLabel: "Boutique",
    roleLabel: "Poste",
    noStore: "Aucune boutique assignée",
    noRole: "Poste à compléter",
    noName: "Partenaire ZHAO",
  },
};

export const DASHBOARD_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "首页 · HOME",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · TODAY · HOME",
    greetingPrefix: "你好，",
    greetingFallback: "ZHAO 伙伴",
    greetingSuffix: "。",
    lede: "欢迎回到 ZHAO's Family。选择一个入口，开始今天的工作。",
    shortcutsHeading: "入口",
    shortcuts: [
      {
        id: "stores",
        index: "01",
        label: "门店",
        title: "门店运营",
        detail: "查看你负责的门店",
      },
      {
        id: "training",
        index: "02",
        label: "培训",
        title: "培训档案",
        detail: "最新课程、岗位标准与可执行的动作点。",
      },
      {
        id: "profile",
        index: "03",
        label: "档案",
        title: "个人档案",
        detail: "头像、岗位、联系方式与账号安全。",
      },
    ],
    newsModule: {
      kicker: "Internal Editorial · Newsroom",
      title: "今日动态",
      titleAccent: "内部资讯台",
      subtitle: "下方编辑部的信息流，用于浏览通知、表彰与运营提醒。",
      overviewLabel: "总览",
      stats: {
        total: "全局总数",
        news: "最新动态",
        congrats: "表彰快讯",
        issues: "运营提醒",
      },
      filters: {
        search: "搜索",
        searchPlaceholder: "搜索标题、作者、标签",
        category: "分类",
        visibility: "可见范围",
        sort: "排序",
        reset: "重置筛选",
      },
      categories: {
        all: "全部板块",
        news: "最新动态",
        congrats: "表彰快讯",
        issues: "运营提醒",
      },
      visibility: {
        all: "全部范围",
        public: "全员可见",
        management: "管理层",
      },
      sort: {
        newest: "最新优先",
        oldest: "最早优先",
        title: "标题排序",
      },
      columns: {
        news: {
          index: "01",
          title: "最新动态",
          subtitle: "门店节奏、内容发布与跨店同步。",
        },
        congrats: {
          index: "02",
          title: "表彰快讯",
          subtitle: "团队成绩、成长节点与门店亮点。",
        },
        issues: {
          index: "03",
          title: "运营提醒",
          subtitle: "需要跟进的事项、风险与执行点。",
        },
      },
      cardsLabel: "条目",
      loading: "正在加载动态...",
      empty: "当前筛选下暂无内容。",
      byLabel: "作者",
      dateLabel: "日期",
      attachmentLabel: "附件",
      openAttachment: "查看附件",
      publish: {
        title: "发布动态",
        subtitle: "写给全员或管理层阅读的真实内容，会保存到后台并出现在下方信息流。",
        titleLabel: "标题",
        titlePlaceholder: "例如：午高峰出品节奏更新",
        summaryLabel: "摘要",
        summaryPlaceholder: "用一句话说明这条动态为什么重要",
        bodyLabel: "正文",
        bodyPlaceholder: "填写具体背景、行动要求、负责人或阅读说明",
        tagsLabel: "标签",
        tagsPlaceholder: "用逗号分隔，例如 Service, Audit",
        attachmentLabel: "附件",
        attachmentHint: "可选，支持 PDF、图片、表格或文档。",
        bodyImageLabel: "插入图片",
        bodyImageHint: "图片会插入到正文光标位置。",
        bodyImageUploading: "图片上传中",
        bodyImageError: "正文图片上传失败，请稍后重试。",
        submit: "发布",
        submitting: "上传并发布中",
        success: "动态已发布。",
        required: "标题、摘要和正文都需要填写。",
        error: "发布失败，请稍后重试。",
      },
      reader: {
        title: "阅读全文",
        close: "关闭阅读",
        open: "阅读全文",
        delete: "删除",
        deleteConfirm: "确认删除这条动态？",
        deleteSuccess: "动态已删除。",
        deleteError: "删除失败，请稍后重试。",
        storeLabel: "门店",
      },
      notification: {
        title: "有新动态",
        subtitle: "你上次查看之后，内部资讯台发布了新的内容。",
        latestLabel: "最新",
        close: "我知道了",
        open: "查看",
      },
      loadError: "动态加载失败，请稍后重试。",
    },
    scoreLeaderboard: {
      kicker: "Store Score · Ranking",
      title: "门店评分排行榜",
      subtitle:
        "展示最新已发布周期每家门店的 A / B / C 等级与评分，点击门店可查看运营上传的评分报告。",
      summaryLabel: "等级统计",
      trackingLabel: "后续追踪",
      tieLabel: "并列",
      storeUnit: "家",
      auditLabel: "检查",
      reportLabel: "查看评分报告",
      placeLabel: "第 {rank} 名",
      columns: {
        rank: "排名",
        store: "门店",
        grade: "等级",
        score: "评分",
        trend: "趋势",
        focus: "关注点",
      },
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "HOME · 首页",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · TODAY · HOME",
    greetingPrefix: "Hello, ",
    greetingFallback: "ZHAO partner",
    greetingSuffix: ".",
    lede: "Welcome back to ZHAO's Family. Pick an entry to start your day.",
    shortcutsHeading: "Entries",
    shortcuts: [
      {
        id: "stores",
        index: "01",
        label: "Stores",
        title: "Store operations",
        detail: "Your stores, shifts, and today's focus points.",
      },
      {
        id: "training",
        index: "02",
        label: "Training",
        title: "Training library",
        detail: "Latest modules, role standards, and action points.",
      },
      {
        id: "profile",
        index: "03",
        label: "Profile",
        title: "Personal profile",
        detail: "Avatar, role, contact info and account security.",
      },
    ],
    newsModule: {
      kicker: "Internal Editorial · Newsroom",
      title: "Today",
      titleAccent: "internal bulletin",
      subtitle:
        "Keep the current dashboard entry points intact and extend the page with an editorial news flow for notices, recognition and operational follow-up.",
      overviewLabel: "Overview",
      stats: {
        total: "Total items",
        news: "Latest news",
        congrats: "Recognition",
        issues: "Operational alerts",
      },
      filters: {
        search: "Search",
        searchPlaceholder: "Search title, author, tags",
        category: "Category",
        visibility: "Visibility",
        sort: "Sort",
        reset: "Reset filters",
      },
      categories: {
        all: "All sections",
        news: "Latest news",
        congrats: "Recognition",
        issues: "Operational alerts",
      },
      visibility: {
        all: "All visibility",
        public: "All staff",
        management: "Managers",
      },
      sort: {
        newest: "Newest first",
        oldest: "Oldest first",
        title: "Title order",
      },
      columns: {
        news: {
          index: "01",
          title: "Latest news",
          subtitle: "Store rhythm, publishing cadence and cross-site updates.",
        },
        congrats: {
          index: "02",
          title: "Recognition",
          subtitle: "Team wins, growth milestones and store highlights.",
        },
        issues: {
          index: "03",
          title: "Operational alerts",
          subtitle: "Items to follow up, risks to control and actions to execute.",
        },
      },
      cardsLabel: "items",
      loading: "Loading updates...",
      empty: "No content matches the current filters.",
      byLabel: "By",
      dateLabel: "Date",
      attachmentLabel: "Attachment",
      openAttachment: "Open attachment",
      publish: {
        title: "Publish update",
        subtitle:
          "Write real content for all staff or managers. It is saved to the backend and appears below.",
        titleLabel: "Title",
        titlePlaceholder: "Example: Lunch rush production rhythm updated",
        summaryLabel: "Summary",
        summaryPlaceholder: "Explain why this update matters in one sentence",
        bodyLabel: "Body",
        bodyPlaceholder: "Add context, action required, owners or reading notes",
        tagsLabel: "Tags",
        tagsPlaceholder: "Comma separated, for example Service, Audit",
        attachmentLabel: "Attachment",
        attachmentHint: "Optional. PDF, image, spreadsheet or document.",
        bodyImageLabel: "Insert image",
        bodyImageHint: "The image is inserted at the body cursor.",
        bodyImageUploading: "Uploading image",
        bodyImageError: "Body image upload failed. Please try again.",
        submit: "Publish",
        submitting: "Uploading and publishing",
        success: "Update published.",
        required: "Title, summary and body are required.",
        error: "Publishing failed. Please try again.",
      },
      reader: {
        title: "Read update",
        close: "Close reader",
        open: "Read",
        delete: "Delete",
        deleteConfirm: "Delete this update?",
        deleteSuccess: "Update deleted.",
        deleteError: "Delete failed. Please try again.",
        storeLabel: "Store",
      },
      notification: {
        title: "New updates",
        subtitle: "New internal updates were published since your last visit.",
        latestLabel: "Latest",
        close: "Got it",
        open: "Read",
      },
      loadError: "Updates could not be loaded. Please try again.",
    },
    scoreLeaderboard: {
      kicker: "Store Score · Ranking",
      title: "Store score ranking",
      subtitle:
        "A / B / C grade and score for each store from the latest published cycle. Click a store to open the operations audit report.",
      summaryLabel: "Grade summary",
      trackingLabel: "Follow-up",
      tieLabel: "Tie",
      storeUnit: "stores",
      auditLabel: "Audit",
      reportLabel: "View audit report",
      placeLabel: "No. {rank}",
      columns: {
        rank: "Rank",
        store: "Store",
        grade: "Grade",
        score: "Score",
        trend: "Trend",
        focus: "Focus",
      },
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "ACCUEIL · 首页",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · AUJOURD'HUI · ACCUEIL",
    greetingPrefix: "Bonjour, ",
    greetingFallback: "partenaire ZHAO",
    greetingSuffix: ".",
    lede: "Bon retour chez ZHAO's Family. Choisissez une entrée pour commencer.",
    shortcutsHeading: "Entrées",
    shortcuts: [
      {
        id: "stores",
        index: "01",
        label: "Boutiques",
        title: "Opérations boutique",
        detail: "Vos boutiques, plannings et points du jour.",
      },
      {
        id: "training",
        index: "02",
        label: "Formation",
        title: "Espace formation",
        detail: "Derniers modules, standards de poste, actions concrètes.",
      },
      {
        id: "profile",
        index: "03",
        label: "Profil",
        title: "Profil personnel",
        detail: "Avatar, poste, coordonnées et sécurité du compte.",
      },
    ],
    newsModule: {
      kicker: "Internal Editorial · Newsroom",
      title: "Aujourd'hui",
      titleAccent: "actualites internes",
      subtitle:
        "La page dashboard conserve ses entrées actuelles et ajoute plus bas un flux editorial pour les annonces, les felicitations et les points d'attention operationnels.",
      overviewLabel: "Vue d'ensemble",
      stats: {
        total: "Total",
        news: "Nouvelles actualites",
        congrats: "Mises a l'honneur",
        issues: "Points de vigilance",
      },
      filters: {
        search: "Recherche",
        searchPlaceholder: "Titre, auteur, tags",
        category: "Categorie",
        visibility: "Visibilite",
        sort: "Tri",
        reset: "Reinitialiser",
      },
      categories: {
        all: "Toutes sections",
        news: "Nouvelles actualites",
        congrats: "Mises a l'honneur",
        issues: "Points de vigilance",
      },
      visibility: {
        all: "Toute visibilite",
        public: "Tous les employes",
        management: "Managers",
      },
      sort: {
        newest: "Plus recent",
        oldest: "Plus ancien",
        title: "Ordre alphabetique",
      },
      columns: {
        news: {
          index: "01",
          title: "Nouvelles actualites",
          subtitle: "Rythme des boutiques, cadence editoriale et synchronisation reseau.",
        },
        congrats: {
          index: "02",
          title: "Mises a l'honneur",
          subtitle: "Resultats d'equipe, capes franchis et points forts boutique.",
        },
        issues: {
          index: "03",
          title: "Points de vigilance",
          subtitle: "Sujets a traiter, risques a maitriser et actions a lancer.",
        },
      },
      cardsLabel: "elements",
      loading: "Chargement des actualites...",
      empty: "Aucun contenu ne correspond aux filtres actuels.",
      byLabel: "Par",
      dateLabel: "Date",
      attachmentLabel: "Piece jointe",
      openAttachment: "Voir la piece jointe",
      publish: {
        title: "Publier une actualite",
        subtitle:
          "Ecrivez un vrai contenu pour les equipes boutique. Il est enregistre et apparait ci-dessous.",
        titleLabel: "Titre",
        titlePlaceholder: "Exemple : rythme du service midi ajuste",
        summaryLabel: "Resume",
        summaryPlaceholder: "Expliquez en une phrase pourquoi c'est important",
        bodyLabel: "Texte",
        bodyPlaceholder: "Ajoutez contexte, actions attendues, responsables ou notes de lecture",
        tagsLabel: "Tags",
        tagsPlaceholder: "Separes par virgule, par exemple Service, Audit",
        attachmentLabel: "Piece jointe",
        attachmentHint: "Optionnel. PDF, image, tableur ou document.",
        bodyImageLabel: "Inserer image",
        bodyImageHint: "L'image est inseree a la position du curseur.",
        bodyImageUploading: "Image en cours d'envoi",
        bodyImageError: "Envoi de l'image impossible. Reessayez plus tard.",
        submit: "Publier",
        submitting: "Envoi et publication",
        success: "Actualite publiee.",
        required: "Titre, resume et texte sont obligatoires.",
        error: "Publication impossible. Reessayez plus tard.",
      },
      reader: {
        title: "Lire l'actualite",
        close: "Fermer",
        open: "Lire",
        delete: "Supprimer",
        deleteConfirm: "Supprimer cette actualite ?",
        deleteSuccess: "Actualite supprimee.",
        deleteError: "Suppression impossible. Reessayez plus tard.",
        storeLabel: "Boutique",
      },
      notification: {
        title: "Nouvelles actualites",
        subtitle: "De nouvelles actualites internes ont ete publiees depuis votre derniere visite.",
        latestLabel: "Plus recent",
        close: "Compris",
        open: "Lire",
      },
      loadError: "Les actualites n'ont pas pu charger. Reessayez plus tard.",
    },
    scoreLeaderboard: {
      kicker: "Store Score · Ranking",
      title: "Classement des boutiques",
      subtitle:
        "Niveaux A / B / C et notes de chaque boutique du dernier cycle publie. Cliquez sur une boutique pour ouvrir le rapport d'audit.",
      summaryLabel: "Synthese des notes",
      trackingLabel: "Suivi",
      tieLabel: "Ex aequo",
      storeUnit: "boutiques",
      auditLabel: "Audit",
      reportLabel: "Voir le rapport d'audit",
      placeLabel: "Rang {rank}",
      columns: {
        rank: "Rang",
        store: "Boutique",
        grade: "Niveau",
        score: "Score",
        trend: "Tendance",
        focus: "Point cle",
      },
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
};

export const DASHBOARD_LANGUAGES = [
  { value: "zh", label: "ZH" },
  { value: "en", label: "EN" },
  { value: "fr", label: "FR" },
];

export const DASHBOARD_SHORTCUT_HREFS = {
  stores: "/dashboard/stores",
  training: "/dashboard/training",
  profile: "/dashboard/profile",
};

// Visibilité des cartes raccourcis de l'accueil — alignée sur DASHBOARD_NAV.
// Une entrée absente = visible par tous.
export const DASHBOARD_SHORTCUT_RULES = {
  stores: { visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES },
};
