import {
  HEADQUARTER_JOB_ROLES,
  MANAGEMENT_JOB_ROLES,
  STORE_MANAGEMENT_JOB_ROLES,
} from "@zhao/utils";

export const DASHBOARD_NAV = [
  {
    id: "menu",
    items: [
      {
        id: "home",
        href: "/dashboard",
        zh: "首页",
        en: "Home",
        fr: "Accueil",
      },
      {
        id: "profile",
        href: "/dashboard/profile",
        zh: "个人资料",
        en: "Profile",
        fr: "Profil",
      },
    ],
  },
  {
    id: "learning",
    items: [
      {
        id: "training-space",
        href: "/dashboard/training",
        zh: "培训空间",
        en: "Training space",
        fr: "Espace formation",
      },
      {
        id: "training-certifications",
        href: "/dashboard/training/certifications",
        zh: "认证管理",
        en: "Certifications",
        fr: "Certifications",
      },
      {
        id: "training-titles",
        href: "/dashboard/training/titles",
        zh: "称号分发",
        en: "Title assignment",
        fr: "Attribution titres",
        visibleForPermissions: [
          "training.title.manage",
          "system.permission.manage",
          "training.badge.manage",
        ],
      },
      {
        id: "training-progress",
        href: "/dashboard/training/progress",
        zh: "培训进度",
        en: "Training progress",
        fr: "Progression formation",
        visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES,
      },
      {
        id: "training-monthly-report",
        href: "/dashboard/training/reports/monthly",
        zh: "培训月报",
        en: "Training report",
        fr: "Rapport formation",
        visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES,
      },
      {
        id: "training-materials",
        href: "/dashboard/training/materials",
        zh: "学习资料",
        en: "Learning materials",
        fr: "Ressources",
      },
    ],
  },
  {
    id: "orders",
    items: [
      {
        id: "new-order",
        href: "/dashboard/orders/new",
        zh: "下单",
        en: "Place order",
        fr: "Passer commande",
        visibleForJobRoles: MANAGEMENT_JOB_ROLES,
      },
      {
        id: "order-history",
        href: "/dashboard/orders",
        zh: "历史订单",
        en: "Order history",
        fr: "Historique",
        visibleForJobRoles: MANAGEMENT_JOB_ROLES,
      },
      {
        id: "order-stats",
        href: "/dashboard/orders/stats",
        zh: "商品统计",
        en: "Product stats",
        fr: "Stats produits",
        visibleForJobRoles: MANAGEMENT_JOB_ROLES,
      },
      {
        id: "suppliers",
        href: "/dashboard/suppliers",
        zh: "供应商管理",
        en: "Suppliers",
        fr: "Fournisseurs",
        visibleForJobRoles: ["holding"],
      },
    ],
  },
  {
    id: "people",
    items: [
      {
        id: "recruitment-requests",
        href: "/dashboard/recruitment-requests",
        zh: "招聘请求",
        en: "Recruitment requests",
        fr: "Demandes recrutement",
        requiredPermission: "recruitment.request.manage",
        // Store/regional management (by job role) see the entry and get the send
        // view (submit + track their own requests); the backend scopes their list
        // to their own store. Only `recruitment.request.manage` unlocks the HQ desk.
        visibleForJobRoles: ["regional-manager", "store-manager", "front-manager", "back-manager"],
      },
    ],
  },
  {
    id: "management",
    items: [
      {
        id: "abc-scores",
        href: "/dashboard/abc-scores",
        zh: "ABC 门店评级",
        en: "ABC store grades",
        fr: "Niveaux ABC",
        requiredPermission: "abc.inspection.read",
        // 营销/运营账号靠权限可见；总部（holding/regional）靠岗位兜底，
        // 与「系统角色」入口同样的 OR 双条件。
        visibleForJobRoles: HEADQUARTER_JOB_ROLES,
      },
      {
        id: "case-shares-review",
        href: "/dashboard/case-shares-review",
        zh: "案例审核",
        en: "Case review",
        fr: "Validation des cas",
        requiredPermission: "case.share.review",
      },
      {
        id: "permissions",
        href: "/dashboard/permissions",
        zh: "系统角色",
        en: "System roles",
        fr: "Rôles système",
        requiredPermission: "system.permission.manage",
        visibleForJobRoles: ["holding"],
      },
      {
        id: "stores",
        href: "/dashboard/stores",
        zh: "门店管理",
        en: "Store management",
        fr: "Gestion des boutiques",
        // 仅 holding / regional-manager / store-manager 可见，与后端门店列表放行范围一致。
        visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES,
      },
      {
        id: "training-positions",
        href: "/dashboard/training/positions",
        zh: "岗位管理",
        en: "Positions",
        fr: "Postes",
        // 仅按权限判断：没有 training.position.manage 就隐藏入口，
        // 不再用总部岗位兜底（否则总部账号即使无权限也会看到入口并落到「无权限」页）。
        requiredPermission: "training.position.manage",
      },
      {
        id: "screen-security",
        href: "/dashboard/screen-security",
        zh: "屏幕安全审计",
        en: "Screen security audit",
        fr: "Audit sécurité écran",
        requiredPermission: "screen_security.audit",
      },
      {
        id: "inventory-zhao-bureau",
        href: "/dashboard/inventory",
        zh: "ZHAO Bureau 库存",
        en: "ZHAO Bureau stock",
        fr: "Stock ZHAO Bureau",
        // 仅总部（holding）可见，区域经理等其他岗位不显示此入口。
        visibleForJobRoles: ["holding"],
      },
    ],
  },
];

export const DASHBOARD_NAV_GROUP_LABELS = {
  zh: {
    menu: "菜单模块",
    learning: "学习模块",
    orders: "订单模块",
    people: "人事模块",
    management: "管理模块",
  },
  en: {
    menu: "MENU MODULE",
    learning: "LEARNING MODULE",
    orders: "ORDER MODULE",
    people: "PEOPLE MODULE",
    management: "MANAGEMENT MODULE",
  },
  fr: {
    menu: "MODULE MENU",
    learning: "MODULE FORMATION",
    orders: "MODULE COMMANDES",
    people: "MODULE RH",
    management: "MODULE GESTION",
  },
};

export const DASHBOARD_MENU_LABELS = {
  zh: {
    open: "菜单",
    close: "关闭",
    title: "导航",
    hint: "选择一个模块开始。",
  },
  en: {
    open: "Menu",
    close: "Close",
    title: "Navigation",
    hint: "Pick a module to begin.",
  },
  fr: {
    open: "Menu",
    close: "Fermer",
    title: "Navigation",
    hint: "Choisissez un module pour commencer.",
  },
};

export const USER_CARD_LABELS = {
  zh: {
    kicker: "当前成员 · CURRENT MEMBER",
    storeLabel: "门店",
    roleLabel: "岗位",
    noStore: "尚未分配门店",
    noRole: "岗位待补充",
    noName: "ZHAO 伙伴",
  },
  en: {
    kicker: "CURRENT MEMBER",
    storeLabel: "Store",
    roleLabel: "Role",
    noStore: "No store assigned",
    noRole: "Role to be set",
    noName: "ZHAO partner",
  },
  fr: {
    kicker: "MEMBRE ACTUEL",
    storeLabel: "Boutique",
    roleLabel: "Poste",
    noStore: "Aucune boutique assignée",
    noRole: "Poste à compléter",
    noName: "Partenaire ZHAO",
  },
};

export const DASHBOARD_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "首页 · HOME",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · TODAY · HOME",
    greetingPrefix: "你好，",
    greetingFallback: "ZHAO 伙伴",
    greetingSuffix: "。",
    lede: "欢迎回到 ZHAO's Family。选择一个入口，开始今天的工作。",
    shortcutsHeading: "入口",
    shortcuts: [
      {
        id: "stores",
        index: "01",
        label: "门店",
        title: "门店运营",
        detail: "查看你负责的门店",
      },
      {
        id: "training",
        index: "02",
        label: "培训",
        title: "培训档案",
        detail: "最新课程、岗位标准与可执行的动作点。",
      },
      {
        id: "profile",
        index: "03",
        label: "档案",
        title: "个人档案",
        detail: "头像、岗位、联系方式与账号安全。",
      },
    ],
    gradeLeaderboard: {
      kicker: "ABC STORE GRADES",
      title: "门店 ABC 评级榜",
      subtitle: "展示最新已发布周期的 A、B、C 级门店；检查报告仅向总部及管理层开放。",
      cycleLabel: "检查周期",
      previousCycle: "查看较新周期",
      nextCycle: "查看较早周期",
      cyclePosition: (current, total) => `${current} / ${total}`,
    },
    newsModule: {
      kicker: "Internal Editorial · Newsroom",
      title: "今日动态",
      titleAccent: "内部资讯台",
      subtitle: "下方编辑部的信息流，用于浏览通知、表彰与批评。",
      boardLabel: "资讯栏目",
      tabs: {
        news: "资讯",
        congrats: "表彰",
        issues: "批评",
      },
      overviewLabel: "总览",
      stats: {
        total: "全局总数",
        news: "最新动态",
        congrats: "表彰快讯",
        issues: "批评",
      },
      filters: {
        search: "搜索",
        searchPlaceholder: "搜索标题、作者、标签",
        category: "分类",
        visibility: "可见范围",
        sort: "排序",
        reset: "重置筛选",
      },
      categories: {
        all: "全部板块",
        news: "最新动态",
        congrats: "表彰快讯",
        issues: "批评",
      },
      visibility: {
        all: "全部范围",
        public: "全员可见",
        management: "管理层",
      },
      sort: {
        newest: "最新优先",
        oldest: "最早优先",
        title: "标题排序",
      },
      columns: {
        news: {
          index: "01",
          title: "最新动态",
          subtitle: "门店节奏、内容发布与跨店同步。",
        },
        congrats: {
          index: "02",
          title: "表彰快讯",
          subtitle: "团队成绩、成长节点与门店亮点。",
        },
        issues: {
          index: "03",
          title: "批评",
          subtitle: "公开问题、明确责任并推动纠正。",
        },
      },
      cardsLabel: "条目",
      loading: "正在加载动态...",
      empty: "当前筛选下暂无内容。",
      byLabel: "作者",
      dateLabel: "日期",
      attachmentLabel: "附件",
      openAttachment: "查看附件",
      publish: {
        title: "发布动态",
        subtitle: "写给全员或管理层阅读的真实内容，会保存到后台并出现在下方信息流。",
        titleLabel: "标题",
        titlePlaceholder: "例如：午高峰出品节奏更新",
        summaryLabel: "摘要",
        summaryPlaceholder: "用一句话说明这条动态为什么重要",
        bodyLabel: "正文",
        bodyPlaceholder: "请输入动态正文，可以使用标题、列表、图片和链接组织内容……",
        tagsLabel: "标签",
        tagsPlaceholder: "输入标签并按 Enter，例如：服务、审核",
        tagsAdd: "继续添加标签",
        tagsLimit: "最多 8 个标签，已添加 {count} 个",
        tagsRemove: "删除标签",
        attachmentLabel: "附件",
        attachmentDropTitle: "拖拽文件到这里，或点击选择文件",
        attachmentHint: "支持 PDF、图片、视频、Excel、Word；单个文件最大 50 MB。",
        attachmentRemove: "移除",
        attachmentSizeError: "附件不能超过 50 MB。",
        optional: "（可选）",
        bodyImageLabel: "插入图片",
        bodyImageHint: "",
        bodyImageUploading: "图片上传中",
        bodyImageError: "正文图片上传失败，请稍后重试。",
        visibilityDescriptions: {
          public: "企业内所有成员均可阅读",
          management: "仅总部及管理层成员可阅读",
        },
        editor: {
          toolbar: "正文编辑工具",
          undo: "撤销",
          redo: "重做",
          blockStyle: "段落样式",
          paragraph: "正文",
          subheading: "小标题",
          heading: "大标题",
          quote: "引用",
          callout: "提示信息",
          bold: "粗体",
          italic: "斜体",
          underline: "下划线",
          bulletList: "项目列表",
          numberedList: "编号列表",
          link: "链接",
          linkPrompt: "请输入链接地址",
          image: "图片",
          imageTooltip: "上传图片并插入当前光标位置",
          divider: "分隔线",
          clearFormat: "清除格式",
        },
        cancel: "取消",
        saveDraft: "保存草稿",
        preview: "预览",
        previewLabel: "发布预览",
        previewVisibility: "可见范围",
        closePreview: "关闭预览",
        returnToEdit: "返回修改",
        confirmPublish: "确认发布",
        submit: "发布动态",
        submitting: "上传并发布中",
        success: "动态已发布。",
        required: "标题、摘要和正文都需要填写。",
        error: "发布失败，请稍后重试。",
        unsaved: "有未保存的修改",
        draftSaved: "草稿已保存在此设备。",
        draftSavedWithoutAttachment: "草稿已保存；出于安全考虑，附件需要重新选择。",
        draftRestored: "已恢复此设备上的草稿。",
        cancelTitle: "放弃当前编辑？",
        cancelConfirm: "当前填写的内容将被清空，已保存的本机草稿也会删除。",
        cancelConfirmAction: "放弃编辑",
        continueEditing: "继续编辑",
      },
      reader: {
        title: "阅读全文",
        close: "关闭阅读",
        open: "阅读全文",
        delete: "删除",
        deleteConfirm: "确认删除这条动态？",
        deleteSuccess: "动态已删除。",
        deleteError: "删除失败，请稍后重试。",
        storeLabel: "门店",
      },
      notification: {
        title: "有新动态",
        subtitle: "你上次查看之后，内部资讯台发布了新的内容。",
        latestLabel: "最新",
        close: "我知道了",
        open: "查看",
      },
      loadError: "动态加载失败，请稍后重试。",
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "HOME · 首页",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · TODAY · HOME",
    greetingPrefix: "Hello, ",
    greetingFallback: "ZHAO partner",
    greetingSuffix: ".",
    lede: "Welcome back to ZHAO's Family. Pick an entry to start your day.",
    shortcutsHeading: "Entries",
    shortcuts: [
      {
        id: "stores",
        index: "01",
        label: "Stores",
        title: "Store operations",
        detail: "Your stores, shifts, and today's focus points.",
      },
      {
        id: "training",
        index: "02",
        label: "Training",
        title: "Training library",
        detail: "Latest modules, role standards, and action points.",
      },
      {
        id: "profile",
        index: "03",
        label: "Profile",
        title: "Personal profile",
        detail: "Avatar, role, contact info and account security.",
      },
    ],
    gradeLeaderboard: {
      kicker: "ABC STORE GRADES",
      title: "ABC store grade board",
      subtitle:
        "A, B and C store grades from the latest published cycle. Inspection reports stay restricted to headquarters and management.",
      cycleLabel: "Inspection cycle",
      previousCycle: "View newer cycle",
      nextCycle: "View older cycle",
      cyclePosition: (current, total) => `${current} / ${total}`,
    },
    newsModule: {
      kicker: "Internal Editorial · Newsroom",
      title: "Today",
      titleAccent: "internal bulletin",
      subtitle:
        "Keep the current dashboard entry points intact and extend the page with an editorial news flow for notices, recognition and operational follow-up.",
      boardLabel: "News sections",
      tabs: {
        news: "News",
        congrats: "Recognition",
        issues: "Critique",
      },
      overviewLabel: "Overview",
      stats: {
        total: "Total items",
        news: "Latest news",
        congrats: "Recognition",
        issues: "Critique",
      },
      filters: {
        search: "Search",
        searchPlaceholder: "Search title, author, tags",
        category: "Category",
        visibility: "Visibility",
        sort: "Sort",
        reset: "Reset filters",
      },
      categories: {
        all: "All sections",
        news: "Latest news",
        congrats: "Recognition",
        issues: "Critique",
      },
      visibility: {
        all: "All visibility",
        public: "All staff",
        management: "Managers",
      },
      sort: {
        newest: "Newest first",
        oldest: "Oldest first",
        title: "Title order",
      },
      columns: {
        news: {
          index: "01",
          title: "Latest news",
          subtitle: "Store rhythm, publishing cadence and cross-site updates.",
        },
        congrats: {
          index: "02",
          title: "Recognition",
          subtitle: "Team wins, growth milestones and store highlights.",
        },
        issues: {
          index: "03",
          title: "Critique",
          subtitle: "Surface problems, clarify ownership and drive correction.",
        },
      },
      cardsLabel: "items",
      loading: "Loading updates...",
      empty: "No content matches the current filters.",
      byLabel: "By",
      dateLabel: "Date",
      attachmentLabel: "Attachment",
      openAttachment: "Open attachment",
      publish: {
        title: "Publish update",
        subtitle:
          "Write real content for all staff or managers. It is saved to the backend and appears below.",
        titleLabel: "Title",
        titlePlaceholder: "Example: Lunch rush production rhythm updated",
        summaryLabel: "Summary",
        summaryPlaceholder: "Explain why this update matters in one sentence",
        bodyLabel: "Body",
        bodyPlaceholder:
          "Write the update. Use headings, lists, images and links to organize it…",
        tagsLabel: "Tags",
        tagsPlaceholder: "Enter a tag and press Enter, e.g. Service",
        tagsAdd: "Add another tag",
        tagsLimit: "Up to 8 tags · {count} added",
        tagsRemove: "Remove tag",
        attachmentLabel: "Attachment",
        attachmentDropTitle: "Drop a file here, or click to choose",
        attachmentHint:
          "PDF, image, video, Excel or Word · one file up to 50 MB.",
        attachmentRemove: "Remove",
        attachmentSizeError: "The attachment must be 50 MB or smaller.",
        optional: "(optional)",
        bodyImageLabel: "Insert image",
        bodyImageHint: "",
        bodyImageUploading: "Uploading image",
        bodyImageError: "Body image upload failed. Please try again.",
        visibilityDescriptions: {
          public: "Every member of the company can read this update",
          management: "Only headquarters and management can read this update",
        },
        editor: {
          toolbar: "Body editing tools",
          undo: "Undo",
          redo: "Redo",
          blockStyle: "Block style",
          paragraph: "Paragraph",
          subheading: "Subheading",
          heading: "Large heading",
          quote: "Quote",
          callout: "Callout",
          bold: "Bold",
          italic: "Italic",
          underline: "Underline",
          bulletList: "Bullet list",
          numberedList: "Numbered list",
          link: "Link",
          linkPrompt: "Enter a link address",
          image: "Image",
          imageTooltip: "Upload an image at the current cursor position",
          divider: "Divider",
          clearFormat: "Clear formatting",
        },
        cancel: "Cancel",
        saveDraft: "Save draft",
        preview: "Preview",
        previewLabel: "Publish preview",
        previewVisibility: "Visibility",
        closePreview: "Close preview",
        returnToEdit: "Return to edit",
        confirmPublish: "Confirm publish",
        submit: "Publish update",
        submitting: "Uploading and publishing",
        success: "Update published.",
        required: "Title, summary and body are required.",
        error: "Publishing failed. Please try again.",
        unsaved: "Unsaved changes",
        draftSaved: "Draft saved on this device.",
        draftSavedWithoutAttachment:
          "Draft saved. For security, choose the attachment again later.",
        draftRestored: "Draft restored from this device.",
        cancelTitle: "Discard this update?",
        cancelConfirm:
          "The current content and the draft saved on this device will be cleared.",
        cancelConfirmAction: "Discard update",
        continueEditing: "Keep editing",
      },
      reader: {
        title: "Read update",
        close: "Close reader",
        open: "Read",
        delete: "Delete",
        deleteConfirm: "Delete this update?",
        deleteSuccess: "Update deleted.",
        deleteError: "Delete failed. Please try again.",
        storeLabel: "Store",
      },
      notification: {
        title: "New updates",
        subtitle: "New internal updates were published since your last visit.",
        latestLabel: "Latest",
        close: "Got it",
        open: "Read",
      },
      loadError: "Updates could not be loaded. Please try again.",
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "ACCUEIL · 首页",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · AUJOURD'HUI · ACCUEIL",
    greetingPrefix: "Bonjour, ",
    greetingFallback: "partenaire ZHAO",
    greetingSuffix: ".",
    lede: "Bon retour chez ZHAO's Family. Choisissez une entrée pour commencer.",
    shortcutsHeading: "Entrées",
    shortcuts: [
      {
        id: "stores",
        index: "01",
        label: "Boutiques",
        title: "Opérations boutique",
        detail: "Vos boutiques, plannings et points du jour.",
      },
      {
        id: "training",
        index: "02",
        label: "Formation",
        title: "Espace formation",
        detail: "Derniers modules, standards de poste, actions concrètes.",
      },
      {
        id: "profile",
        index: "03",
        label: "Profil",
        title: "Profil personnel",
        detail: "Avatar, poste, coordonnées et sécurité du compte.",
      },
    ],
    gradeLeaderboard: {
      kicker: "NIVEAUX ABC DES BOUTIQUES",
      title: "Tableau des niveaux ABC",
      subtitle:
        "Niveaux A, B et C du dernier cycle publie. Les rapports d'inspection restent reserves au siege et au management.",
      cycleLabel: "Cycle d'inspection",
      previousCycle: "Voir le cycle plus récent",
      nextCycle: "Voir le cycle plus ancien",
      cyclePosition: (current, total) => `${current} / ${total}`,
    },
    newsModule: {
      kicker: "Internal Editorial · Newsroom",
      title: "Aujourd'hui",
      titleAccent: "actualites internes",
      subtitle:
        "La page dashboard conserve ses entrées actuelles et ajoute plus bas un flux editorial pour les annonces, les felicitations et les points d'attention operationnels.",
      boardLabel: "Rubriques d'actualités",
      tabs: {
        news: "Actualités",
        congrats: "Félicitations",
        issues: "Critiques",
      },
      overviewLabel: "Vue d'ensemble",
      stats: {
        total: "Total",
        news: "Nouvelles actualites",
        congrats: "Mises a l'honneur",
        issues: "Critiques",
      },
      filters: {
        search: "Recherche",
        searchPlaceholder: "Titre, auteur, tags",
        category: "Categorie",
        visibility: "Visibilite",
        sort: "Tri",
        reset: "Reinitialiser",
      },
      categories: {
        all: "Toutes sections",
        news: "Nouvelles actualites",
        congrats: "Mises a l'honneur",
        issues: "Critiques",
      },
      visibility: {
        all: "Toute visibilite",
        public: "Tous les employes",
        management: "Managers",
      },
      sort: {
        newest: "Plus recent",
        oldest: "Plus ancien",
        title: "Ordre alphabetique",
      },
      columns: {
        news: {
          index: "01",
          title: "Nouvelles actualites",
          subtitle: "Rythme des boutiques, cadence editoriale et synchronisation reseau.",
        },
        congrats: {
          index: "02",
          title: "Mises a l'honneur",
          subtitle: "Resultats d'equipe, capes franchis et points forts boutique.",
        },
        issues: {
          index: "03",
          title: "Critiques",
          subtitle:
            "Rendre les problemes visibles, clarifier les responsabilites et corriger.",
        },
      },
      cardsLabel: "elements",
      loading: "Chargement des actualites...",
      empty: "Aucun contenu ne correspond aux filtres actuels.",
      byLabel: "Par",
      dateLabel: "Date",
      attachmentLabel: "Piece jointe",
      openAttachment: "Voir la piece jointe",
      publish: {
        title: "Publier une actualite",
        subtitle:
          "Ecrivez un vrai contenu pour les equipes boutique. Il est enregistre et apparait ci-dessous.",
        titleLabel: "Titre",
        titlePlaceholder: "Exemple : rythme du service midi ajuste",
        summaryLabel: "Resume",
        summaryPlaceholder: "Expliquez en une phrase pourquoi c'est important",
        bodyLabel: "Texte",
        bodyPlaceholder:
          "Redigez le contenu avec des titres, listes, images et liens…",
        tagsLabel: "Tags",
        tagsPlaceholder: "Saisissez un tag puis Entrée, par exemple Service",
        tagsAdd: "Ajouter un tag",
        tagsLimit: "8 tags maximum · {count} ajoutes",
        tagsRemove: "Supprimer le tag",
        attachmentLabel: "Piece jointe",
        attachmentDropTitle: "Deposez un fichier ici ou cliquez pour choisir",
        attachmentHint:
          "PDF, image, video, Excel ou Word · un fichier de 50 Mo maximum.",
        attachmentRemove: "Retirer",
        attachmentSizeError: "La piece jointe ne doit pas depasser 50 Mo.",
        optional: "(optionnel)",
        bodyImageLabel: "Inserer image",
        bodyImageHint: "",
        bodyImageUploading: "Image en cours d'envoi",
        bodyImageError: "Envoi de l'image impossible. Reessayez plus tard.",
        visibilityDescriptions: {
          public: "Tous les membres de l'entreprise peuvent lire cette actualite",
          management: "Seuls le siege et les managers peuvent la lire",
        },
        editor: {
          toolbar: "Outils de mise en forme",
          undo: "Annuler",
          redo: "Rétablir",
          blockStyle: "Style de paragraphe",
          paragraph: "Paragraphe",
          subheading: "Sous-titre",
          heading: "Grand titre",
          quote: "Citation",
          callout: "Information",
          bold: "Gras",
          italic: "Italique",
          underline: "Souligner",
          bulletList: "Liste à puces",
          numberedList: "Liste numérotée",
          link: "Lien",
          linkPrompt: "Saisissez une adresse de lien",
          image: "Image",
          imageTooltip: "Importer une image à la position du curseur",
          divider: "Séparateur",
          clearFormat: "Effacer le format",
        },
        cancel: "Annuler",
        saveDraft: "Enregistrer le brouillon",
        preview: "Apercu",
        previewLabel: "Apercu avant publication",
        previewVisibility: "Visibilite",
        closePreview: "Fermer l'apercu",
        returnToEdit: "Modifier",
        confirmPublish: "Confirmer la publication",
        submit: "Publier l'actualite",
        submitting: "Envoi et publication",
        success: "Actualite publiee.",
        required: "Titre, resume et texte sont obligatoires.",
        error: "Publication impossible. Reessayez plus tard.",
        unsaved: "Modifications non enregistrees",
        draftSaved: "Brouillon enregistre sur cet appareil.",
        draftSavedWithoutAttachment:
          "Brouillon enregistre. La piece jointe devra etre choisie a nouveau.",
        draftRestored: "Brouillon restaure depuis cet appareil.",
        cancelTitle: "Abandonner cette actualite ?",
        cancelConfirm:
          "Le contenu actuel et le brouillon de cet appareil seront effaces.",
        cancelConfirmAction: "Abandonner",
        continueEditing: "Continuer",
      },
      reader: {
        title: "Lire l'actualite",
        close: "Fermer",
        open: "Lire",
        delete: "Supprimer",
        deleteConfirm: "Supprimer cette actualite ?",
        deleteSuccess: "Actualite supprimee.",
        deleteError: "Suppression impossible. Reessayez plus tard.",
        storeLabel: "Boutique",
      },
      notification: {
        title: "Nouvelles actualites",
        subtitle: "De nouvelles actualites internes ont ete publiees depuis votre derniere visite.",
        latestLabel: "Plus recent",
        close: "Compris",
        open: "Lire",
      },
      loadError: "Les actualites n'ont pas pu charger. Reessayez plus tard.",
    },
    footer: "Since 2011 — ZHAO's Family Holding",
  },
};

export const DASHBOARD_LANGUAGES = [
  { value: "zh", label: "ZH" },
  { value: "en", label: "EN" },
  { value: "fr", label: "FR" },
];

export const DASHBOARD_SHORTCUT_HREFS = {
  stores: "/dashboard/stores",
  training: "/dashboard/training",
  profile: "/dashboard/profile",
};

// Visibilité des cartes raccourcis de l'accueil — alignée sur DASHBOARD_NAV.
// Une entrée absente = visible par tous.
export const DASHBOARD_SHORTCUT_RULES = {
  stores: { visibleForJobRoles: STORE_MANAGEMENT_JOB_ROLES },
};
