import { StyleSheet } from "react-native";
import { scaleStyles } from "@/lib/responsive";
import { authControlStyles } from "@/features/auth/AuthFormControls";

export const orderStyles = StyleSheet.create(scaleStyles({
  dateInput: {
    borderBottomColor: authControlStyles.colors.ink,
    borderBottomWidth: 1,
    color: authControlStyles.colors.ink,
    fontFamily: "monospace",
    fontSize: 15,
    minHeight: 44,
    paddingVertical: 8,
  },
  datePreview: {
    color: authControlStyles.colors.ink60,
    fontFamily: "monospace",
    fontSize: 13,
  },
  disabledButton: {
    opacity: 0.55,
  },
  errorText: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  filterToggle: {
    alignItems: "center",
    borderColor: "rgba(193, 22, 22, 0.26)",
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  filterToggleText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  header: {
    gap: 8,
  },
  imagePlaceholder: {
    alignItems: "center",
    backgroundColor: "rgba(193, 22, 22, 0.08)",
    justifyContent: "center",
  },
  imagePlaceholderText: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 22,
    fontWeight: "500",
  },
  historySupplierButton: {
    alignItems: "center",
    borderColor: "rgba(193, 22, 22, 0.24)",
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: 14,
  },
  historySupplierButtonActive: {
    backgroundColor: authControlStyles.colors.red,
    borderColor: authControlStyles.colors.red,
  },
  historySupplierRow: {
    gap: 8,
    paddingRight: 2,
  },
  historySupplierScroller: {
    marginRight: -2,
  },
  historySupplierText: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 14,
  },
  historySupplierTextActive: {
    color: authControlStyles.colors.paper,
  },
  module: {
    gap: 18,
    paddingTop: 22,
  },
  modeRow: {
    borderColor: "rgba(193, 22, 22, 0.22)",
    borderWidth: 1,
    flexDirection: "row",
  },
  modeButton: {
    alignItems: "center",
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  modeButtonActive: {
    backgroundColor: authControlStyles.colors.red,
  },
  modeText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  modeTextActive: {
    color: authControlStyles.colors.paper,
  },
  nodeDot: {
    borderColor: authControlStyles.colors.ink40,
    borderWidth: 1,
    height: 14,
    width: 14,
  },
  nodeDotActive: {
    backgroundColor: authControlStyles.colors.red,
    borderColor: authControlStyles.colors.red,
  },
  nodeList: {
    gap: 10,
  },
  nodeRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  nodeText: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 15,
  },
  optionButton: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  optionButtonActive: {
    borderColor: authControlStyles.colors.red,
  },
  optionGrid: {
    gap: 8,
  },
  optionText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 15,
  },
  optionTextActive: {
    color: authControlStyles.colors.red,
  },
  supplierRow: {
    alignItems: "center",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 58,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  supplierRowActive: {
    backgroundColor: "rgba(193, 22, 22, 0.05)",
    borderColor: authControlStyles.colors.red,
  },
  supplierRowText: {
    color: authControlStyles.colors.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 16,
    marginRight: 12,
  },
  supplierRowTextActive: {
    color: authControlStyles.colors.red,
    fontWeight: "600",
  },
  orderCard: {
    borderColor: "rgba(193, 22, 22, 0.16)",
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  orderCardActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 4,
  },
  orderCardAction: {
    alignItems: "center",
    borderColor: "rgba(193, 22, 22, 0.3)",
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: 12,
  },
  orderCardActionDanger: {
    borderColor: authControlStyles.colors.red,
  },
  orderCardActionPrimary: {
    backgroundColor: authControlStyles.colors.red,
    borderColor: authControlStyles.colors.red,
  },
  orderCardActionText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  orderCardActionTextPrimary: {
    color: authControlStyles.colors.paper,
  },
  orderCardLocked: {
    opacity: 0.58,
  },
  orderCardMeta: {
    color: authControlStyles.colors.ink60,
    fontFamily: "monospace",
    fontSize: 11,
    lineHeight: 17,
  },
  orderCardTitle: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 17,
    fontWeight: "500",
  },
  orderHistoryList: {
    gap: 10,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: authControlStyles.colors.red,
    minHeight: 48,
    justifyContent: "center",
    marginTop: 2,
  },
  primaryButtonText: {
    color: authControlStyles.colors.paper,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  productCard: {
    borderColor: "rgba(193, 22, 22, 0.16)",
    borderWidth: 1,
    gap: 10,
    minWidth: "47%",
    padding: 12,
    width: "47%",
  },
  productHeader: {
    gap: 8,
  },
  productImage: {
    height: 92,
    width: "100%",
  },
  productImageFrame: {
    borderColor: "rgba(193, 22, 22, 0.16)",
    borderWidth: 1,
    height: 92,
    overflow: "hidden",
    width: "100%",
  },
  productInfo: {
    gap: 5,
  },
  productList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  productMeta: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 11,
  },
  productName: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 18,
  },
  stockStatus: {
    alignSelf: "flex-start",
    borderRadius: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  stockStatusInStock: {
    backgroundColor: "rgba(25, 122, 61, 0.14)",
  },
  stockStatusOutOfStock: {
    backgroundColor: "rgba(193, 22, 22, 0.14)",
  },
  stockStatusText: {
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
  },
  stockStatusTextInStock: {
    color: authControlStyles.colors.success,
  },
  stockStatusTextOutOfStock: {
    color: authControlStyles.colors.red,
  },
  returnField: {
    gap: 8,
  },
  returnFieldLabel: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  returnInput: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  returnNotesInput: {
    minHeight: 76,
    textAlignVertical: "top",
  },
  returnItem: {
    alignItems: "center",
    borderBottomColor: "rgba(193, 22, 22, 0.1)",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingVertical: 10,
  },
  returnItemInfo: {
    flex: 1,
    gap: 4,
  },
  returnItemList: {
    borderTopColor: "rgba(193, 22, 22, 0.16)",
    borderTopWidth: 1,
  },
  returnItemMeta: {
    color: authControlStyles.colors.ink60,
    fontFamily: "monospace",
    fontSize: 11,
    lineHeight: 16,
  },
  returnPanel: {
    borderColor: "rgba(193, 22, 22, 0.22)",
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  progressFill: {
    backgroundColor: authControlStyles.colors.red,
    height: 6,
  },
  progressRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  progressText: {
    color: authControlStyles.colors.ink,
    fontFamily: "monospace",
    fontSize: 13,
    width: 42,
  },
  progressTrack: {
    backgroundColor: authControlStyles.colors.ink10,
    flex: 1,
    height: 6,
  },
  quantityInput: {
    color: authControlStyles.colors.ink,
    fontFamily: "monospace",
    fontSize: 14,
    minHeight: 42,
    minWidth: 30,
    paddingHorizontal: 2,
    textAlign: "center",
  },
  quantityStepper: {
    alignItems: "stretch",
    alignSelf: "flex-start",
    borderColor: authControlStyles.colors.ink20,
    borderWidth: 1,
    flexDirection: "row",
    overflow: "hidden",
  },
  stepperButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    width: 26,
  },
  stepperButtonPressed: {
    backgroundColor: authControlStyles.colors.ink05,
  },
  stepperButtonLeft: {
    borderRightColor: authControlStyles.colors.ink10,
    borderRightWidth: 1,
  },
  stepperButtonRight: {
    borderLeftColor: authControlStyles.colors.ink10,
    borderLeftWidth: 1,
  },
  stepperButtonText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 19,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: authControlStyles.colors.red,
    borderWidth: 1,
    minHeight: 48,
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  section: {
    gap: 14,
  },
  searchInput: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  segmentButton: {
    alignItems: "center",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  segmentButtonActive: {
    borderColor: authControlStyles.colors.red,
  },
  segmentRow: {
    flexDirection: "row",
    gap: 8,
  },
  segmentText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
  },
  segmentTextActive: {
    color: authControlStyles.colors.red,
  },
  selectedLine: {
    borderBottomColor: "rgba(193, 22, 22, 0.1)",
    borderBottomWidth: 1,
    gap: 4,
    paddingVertical: 10,
  },
  selectedList: {
    borderTopColor: "rgba(193, 22, 22, 0.16)",
    borderTopWidth: 1,
  },
  selectedMeta: {
    color: authControlStyles.colors.ink60,
    fontFamily: "monospace",
    fontSize: 12,
  },
  selectedName: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 16,
  },
  stateRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  stateText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  subtitle: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 15,
    lineHeight: 22,
  },
  summaryBox: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  summaryLabel: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    width: 104,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
  },
  summaryValue: {
    color: authControlStyles.colors.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 15,
    lineHeight: 20,
  },
  title: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 28,
    fontWeight: "500",
    lineHeight: 34,
  },
  variantRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  variantText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "monospace",
    fontSize: 10,
    lineHeight: 14,
  },
  unitText: {
    color: authControlStyles.colors.ink60,
    flexShrink: 1,
    fontFamily: "monospace",
    fontSize: 9,
    marginLeft: 4,
    textAlign: "left",
  },
}));
