export const ORDER_COPY = {
  zh: {
    title: "下单模块",
    subtitle: "选择供应商、配送日期和商品数量。",
    newTab: "新建",
    historyTab: "历史",
    orderHistory: "历史订单",
    allSuppliers: "全部",
    loadingOrders: "正在加载历史订单...",
    emptyOrders: "暂无历史订单。",
    editOrder: "修改订单",
    returnOrder: "退货",
    deleteOrder: "删除",
    deletingOrder: "删除中...",
    deletedOrder: "订单已删除",
    confirmDeleteTitle: "删除订单",
    confirmDeleteMessage: "确认删除订单 {number}？此操作不可撤销。",
    confirmDeleteCancel: "取消",
    confirmDeleteConfirm: "删除",
    editingOrder: "正在修改订单",
    updatedOrder: "订单已更新",
    backToHistory: "返回历史",
    returnedOrderLocked: "该订单已有退货记录，不能修改。",
    returnTitle: "创建退货",
    loadingReturnDraft: "正在加载可退商品...",
    returnReason: "退货原因",
    returnNotes: "备注",
    returnQuantity: "退货数量",
    returnRemaining: "可退",
    submitReturn: "提交退货",
    submittingReturn: "提交中...",
    cancelReturn: "取消退货",
    returnCreated: "退货已提交",
    returnEmpty: "这张订单没有可退商品。",
    returnReasonRequired: "请填写退货原因。",
    returnItemRequired: "请至少选择一个退货商品。",
    returnSubmitError: "退货提交失败，请稍后重试。",
    deleteError: "订单删除失败，请稍后重试。",
    supplier: "供应商",
    loadingSuppliers: "正在加载供应商...",
    loadingProducts: "正在加载商品...",
    emptyProducts: "该供应商暂无商品。",
    backToSuppliers: "返回供应商",
    productFilter: "筛选商品",
    showFilters: "筛选",
    hideFilters: "收起筛选",
    filterPlaceholder: "搜索名称、编号、分类",
    allCategories: "全部分类",
    emptyFilteredProducts: "没有符合筛选的商品。",
    jumpTop: "顶部",
    jumpBottom: "底部",
    deliveryDate: "配送日期",
    today: "今天",
    tomorrow: "明天",
    otherDate: "其他时间",
    customDatePlaceholder: "YYYY-MM-DD",
    products: "商品数量",
    inStock: "有货",
    outOfStock: "没货",
    confirm: "进入确认页",
    submit: "提交订单",
    update: "更新订单",
    back: "返回修改",
    newOrder: "新建订单",
    sharePdf: "分享 PDF",
    shareAgain: "再次分享",
    preparingPdf: "正在准备 PDF...",
    noPdf: "后端暂未返回 PDF 链接。",
    shareReady: "PDF 链接已生成，可通过系统分享面板发送到微信。",
    shareDone: "分享面板已打开。",
    shareCancelled: "分享已取消，订单仍已创建。",
    loadError: "订单数据加载失败，请稍后重试。",
    submitError: "订单提交失败，请检查后重试。",
    updateError: "订单更新失败，请检查后重试。",
    shareError: "分享失败，请稍后再试。",
    selectSupplierError: "请先选择供应商。",
    dateError: "请输入有效的配送日期 YYYY-MM-DD。",
    quantityError: "请至少填写一个商品数量。",
    stockErrorPrefix: "库存不足",
    confirmation: "下单确认页",
    complete: "下单完成页",
    shareStep: "分享 PDF",
    orderNumber: "订单号",
    totalItems: "商品总数",
    estimatedTotal: "预估金额",
    pdfStatus: "PDF 状态",
  },
  en: {
    title: "Order module",
    subtitle: "Choose supplier, delivery date and product quantities.",
    newTab: "New",
    historyTab: "History",
    orderHistory: "Order history",
    allSuppliers: "All",
    loadingOrders: "Loading order history...",
    emptyOrders: "No previous orders.",
    editOrder: "Edit order",
    returnOrder: "Return",
    deleteOrder: "Delete",
    deletingOrder: "Deleting...",
    deletedOrder: "Order deleted",
    confirmDeleteTitle: "Delete order",
    confirmDeleteMessage: "Delete order {number}? This cannot be undone.",
    confirmDeleteCancel: "Cancel",
    confirmDeleteConfirm: "Delete",
    editingOrder: "Editing order",
    updatedOrder: "Order updated",
    backToHistory: "Back to history",
    returnedOrderLocked: "This order has returns and cannot be edited.",
    returnTitle: "Create return",
    loadingReturnDraft: "Loading returnable items...",
    returnReason: "Return reason",
    returnNotes: "Notes",
    returnQuantity: "Return quantity",
    returnRemaining: "Remaining",
    submitReturn: "Submit return",
    submittingReturn: "Submitting...",
    cancelReturn: "Cancel return",
    returnCreated: "Return submitted",
    returnEmpty: "This order has no returnable items.",
    returnReasonRequired: "Please enter a return reason.",
    returnItemRequired: "Please choose at least one return item.",
    returnSubmitError: "Return submission failed. Please try again.",
    deleteError: "Order could not be deleted. Please try again.",
    supplier: "Supplier",
    loadingSuppliers: "Loading suppliers...",
    loadingProducts: "Loading products...",
    emptyProducts: "No products for this supplier.",
    backToSuppliers: "Back to suppliers",
    productFilter: "Filter products",
    showFilters: "Filters",
    hideFilters: "Hide filters",
    filterPlaceholder: "Search name, reference, category",
    allCategories: "All categories",
    emptyFilteredProducts: "No products match this filter.",
    jumpTop: "Top",
    jumpBottom: "Bottom",
    deliveryDate: "Delivery date",
    today: "Today",
    tomorrow: "Tomorrow",
    otherDate: "Other date",
    customDatePlaceholder: "YYYY-MM-DD",
    products: "Products",
    inStock: "In stock",
    outOfStock: "Out of stock",
    confirm: "Review order",
    submit: "Submit order",
    update: "Update order",
    back: "Edit order",
    newOrder: "New order",
    sharePdf: "Share PDF",
    shareAgain: "Share again",
    preparingPdf: "Preparing PDF...",
    noPdf: "No PDF link returned yet.",
    shareReady: "PDF link is ready. Use system share to send it to WeChat.",
    shareDone: "Share panel opened.",
    shareCancelled: "Share cancelled. The order was still created.",
    loadError: "Order data could not load. Please try again.",
    submitError: "Order could not be submitted. Please try again.",
    updateError: "Order could not be updated. Please try again.",
    shareError: "Sharing failed. Please try again later.",
    selectSupplierError: "Choose a supplier first.",
    dateError: "Enter a valid delivery date as YYYY-MM-DD.",
    quantityError: "Enter at least one product quantity.",
    stockErrorPrefix: "Not enough stock",
    confirmation: "Order review",
    complete: "Order complete",
    shareStep: "Share PDF",
    orderNumber: "Order number",
    totalItems: "Total items",
    estimatedTotal: "Estimated total",
    pdfStatus: "PDF status",
  },
  fr: {
    title: "Module commande",
    subtitle: "Choisissez le fournisseur, la date et les quantites.",
    newTab: "Nouvelle",
    historyTab: "Historique",
    orderHistory: "Historique commandes",
    allSuppliers: "Toutes",
    loadingOrders: "Chargement des commandes...",
    emptyOrders: "Aucune commande precedente.",
    editOrder: "Modifier commande",
    returnOrder: "Retour",
    deleteOrder: "Supprimer",
    deletingOrder: "Suppression...",
    deletedOrder: "Commande supprimee",
    confirmDeleteTitle: "Supprimer commande",
    confirmDeleteMessage: "Supprimer la commande {number} ? Cette action est definitive.",
    confirmDeleteCancel: "Annuler",
    confirmDeleteConfirm: "Supprimer",
    editingOrder: "Modification commande",
    updatedOrder: "Commande mise a jour",
    backToHistory: "Retour historique",
    returnedOrderLocked: "Cette commande a des retours et ne peut pas etre modifiee.",
    returnTitle: "Creer un retour",
    loadingReturnDraft: "Chargement des articles retournables...",
    returnReason: "Motif du retour",
    returnNotes: "Notes",
    returnQuantity: "Quantite retour",
    returnRemaining: "Restant",
    submitReturn: "Envoyer retour",
    submittingReturn: "Envoi...",
    cancelReturn: "Annuler retour",
    returnCreated: "Retour envoye",
    returnEmpty: "Cette commande n'a aucun article retournable.",
    returnReasonRequired: "Renseignez le motif du retour.",
    returnItemRequired: "Choisissez au moins un article a retourner.",
    returnSubmitError: "Impossible d'envoyer le retour. Veuillez reessayer.",
    deleteError: "La commande n'a pas pu etre supprimee.",
    supplier: "Fournisseur",
    loadingSuppliers: "Chargement des fournisseurs...",
    loadingProducts: "Chargement des produits...",
    emptyProducts: "Aucun produit pour ce fournisseur.",
    backToSuppliers: "Retour fournisseurs",
    productFilter: "Filtrer les produits",
    showFilters: "Filtres",
    hideFilters: "Masquer filtres",
    filterPlaceholder: "Chercher nom, reference, categorie",
    allCategories: "Toutes categories",
    emptyFilteredProducts: "Aucun produit ne correspond au filtre.",
    jumpTop: "Haut",
    jumpBottom: "Bas",
    deliveryDate: "Date de livraison",
    today: "Aujourd'hui",
    tomorrow: "Demain",
    otherDate: "Autre date",
    customDatePlaceholder: "YYYY-MM-DD",
    products: "Produits",
    inStock: "En stock",
    outOfStock: "Rupture de stock",
    confirm: "Verifier la commande",
    submit: "Envoyer la commande",
    update: "Mettre a jour",
    back: "Modifier",
    newOrder: "Nouvelle commande",
    sharePdf: "Partager PDF",
    shareAgain: "Partager encore",
    preparingPdf: "Preparation du PDF...",
    noPdf: "Aucun lien PDF retourne pour le moment.",
    shareReady: "Le lien PDF est pret. Utilisez le partage systeme pour WeChat.",
    shareDone: "Le partage systeme est ouvert.",
    shareCancelled: "Partage annule. La commande est bien creee.",
    loadError: "Les donnees de commande n'ont pas pu charger.",
    submitError: "La commande n'a pas pu etre envoyee.",
    updateError: "La commande n'a pas pu etre mise a jour.",
    shareError: "Le partage a echoue. Reessayez plus tard.",
    selectSupplierError: "Choisissez d'abord un fournisseur.",
    dateError: "Saisissez une date valide YYYY-MM-DD.",
    quantityError: "Saisissez au moins une quantite.",
    stockErrorPrefix: "Stock insuffisant",
    confirmation: "Verification commande",
    complete: "Commande terminee",
    shareStep: "Partager PDF",
    orderNumber: "Numero",
    totalItems: "Total articles",
    estimatedTotal: "Total estime",
    pdfStatus: "Statut PDF",
  },
} as const;

export type OrderCopy = (typeof ORDER_COPY)[keyof typeof ORDER_COPY];
