export const SCREEN_SECURITY_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "屏幕安全审计 · SCREEN SECURITY",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 安全审计 · SCREEN",
    title: "屏幕安全审计。",
    lede:
      "查看员工截图与录屏事件，按事件类型、用户和日期范围筛选，便于总部核查敏感操作轨迹。",
    back: "返回首页",
    footer: "Since 2011 — ZHAO's Family Holding",
    loading: "加载中…",
    loadError: "加载失败，请稍后重试。",
    empty: "当前筛选条件下暂无屏幕安全事件。",
    unknownUser: "未命名成员",
    unknownScreen: "未记录页面",
    unknownDevice: "未记录设备信息",
    filters: {
      heading: "筛选",
      eventType: "事件类型",
      userId: "用户 ID",
      dateFrom: "开始日期",
      dateTo: "结束日期",
      userIdPlaceholder: "输入用户 ID",
    },
    eventTypes: {
      all: "全部",
      screenshot: "截图",
      recording: "录屏",
    },
    table: {
      date: "日期",
      user: "用户",
      eventType: "事件类型",
      screen: "页面",
      device: "设备",
      time: "时间",
    },
    pagination: {
      prev: "上一页",
      next: "下一页",
      pageInfo: "第 {page} / {pages} 页 · 共 {total} 条",
    },
    selection: {
      selectAll: "全选当前页",
      selectedCount: "已选择 {count} 条记录",
      deleteSelected: "删除所选",
      deleting: "删除中…",
      deleteConfirm: "确定要删除选中的 {count} 条记录吗？此操作不可撤销。",
      deleteSuccess: "已成功删除 {count} 条记录。",
      deleteError: "删除失败，请稍后重试。",
    },
  },
  en: {
    topFamily: "FAMILY",
    topStage: "SCREEN SECURITY · AUDIT",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · SECURITY AUDIT · SCREEN",
    title: "Screen security audit.",
    lede:
      "Review screenshot and screen recording events with direct filters for event type, user, and date range so HQ can trace sensitive actions quickly.",
    back: "Back to home",
    footer: "Since 2011 — ZHAO's Family Holding",
    loading: "Loading…",
    loadError: "Failed to load. Please retry.",
    empty: "No screen security events match the current filters.",
    unknownUser: "Unnamed member",
    unknownScreen: "Unknown screen",
    unknownDevice: "No device info",
    filters: {
      heading: "Filters",
      eventType: "Event type",
      userId: "User ID",
      dateFrom: "Date from",
      dateTo: "Date to",
      userIdPlaceholder: "Enter user ID",
    },
    eventTypes: {
      all: "All",
      screenshot: "Screenshot",
      recording: "Recording",
    },
    table: {
      date: "Date",
      user: "User",
      eventType: "Event type",
      screen: "Screen",
      device: "Device",
      time: "Time",
    },
    pagination: {
      prev: "Previous",
      next: "Next",
      pageInfo: "Page {page} / {pages} · {total} total",
    },
    selection: {
      selectAll: "Select all on page",
      selectedCount: "{count} record(s) selected",
      deleteSelected: "Delete selected",
      deleting: "Deleting…",
      deleteConfirm: "Are you sure you want to delete the {count} selected record(s)? This cannot be undone.",
      deleteSuccess: "Successfully deleted {count} record(s).",
      deleteError: "Failed to delete. Please retry.",
    },
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "AUDIT SÉCURITÉ ÉCRAN",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · AUDIT SÉCURITÉ · ÉCRAN",
    title: "Audit sécurité écran.",
    lede:
      "Consultez les événements de capture et d’enregistrement d’écran avec des filtres par type, utilisateur et plage de dates pour contrôler les actions sensibles.",
    back: "Retour à l'accueil",
    footer: "Since 2011 — ZHAO's Family Holding",
    loading: "Chargement…",
    loadError: "Échec du chargement. Réessayez.",
    empty: "Aucun événement de sécurité écran pour ce filtre.",
    unknownUser: "Membre non nommé",
    unknownScreen: "Écran inconnu",
    unknownDevice: "Aucune info appareil",
    filters: {
      heading: "Filtres",
      eventType: "Type d’événement",
      userId: "ID utilisateur",
      dateFrom: "Date de début",
      dateTo: "Date de fin",
      userIdPlaceholder: "Saisir l’ID utilisateur",
    },
    eventTypes: {
      all: "Tous",
      screenshot: "Capture",
      recording: "Enregistrement",
    },
    table: {
      date: "Date",
      user: "Utilisateur",
      eventType: "Type",
      screen: "Écran",
      device: "Appareil",
      time: "Heure",
    },
    pagination: {
      prev: "Précédent",
      next: "Suivant",
      pageInfo: "Page {page} / {pages} · {total} éléments",
    },
    selection: {
      selectAll: "Tout sélectionner sur la page",
      selectedCount: "{count} enregistrement(s) sélectionné(s)",
      deleteSelected: "Supprimer la sélection",
      deleting: "Suppression…",
      deleteConfirm: "Voulez-vous vraiment supprimer les {count} enregistrement(s) sélectionné(s) ? Cette action est irréversible.",
      deleteSuccess: "{count} enregistrement(s) supprimé(s) avec succès.",
      deleteError: "Échec de la suppression. Réessayez.",
    },
  },
};
