import type { TrainingCourseItem } from './training.types';

export const TRAINING_COURSE_CATALOG: TrainingCourseItem[] = [
  {
    id: 'm-safety-1',
    section: 'required',
    type: 'VIDEO',
    isRequired: true,
    titleCn: '安全与卫生基础',
    titleEn: 'Safety & Hygiene 101',
    durationLabel: '24 min',
    progressPercent: 55,
    status: 'in_progress',
    description: '个人防护、交叉污染预防、意外处置。入职 7 天内完成。',
    tags: ['必修', '入职'],
  },
  {
    id: 'm-greet-sop',
    section: 'required',
    type: 'PDF',
    isRequired: true,
    titleCn: '客人迎接 SOP',
    titleEn: 'Greeting standard SOP',
    durationLabel: '18 页',
    progressPercent: 100,
    status: 'completed',
    description: '前厅 7 秒法则、领位原则与菜单呈递。',
    tags: ['必修', 'SOP'],
  },
  {
    id: 'm-menu-1',
    section: 'required',
    type: 'VIDEO',
    isRequired: true,
    titleCn: '菜品知识 · 招牌篇',
    titleEn: 'Signature dishes walk-through',
    durationLabel: '32 min',
    progressPercent: 12,
    status: 'in_progress',
    description: '10 道招牌菜的故事、辣度、忌口与推荐搭配。',
    tags: ['必修', '菜单'],
  },
  {
    id: 'm-pos-1',
    section: 'required',
    type: 'VIDEO',
    isRequired: true,
    titleCn: '点单机 ZPOS 基础操作',
    titleEn: 'ZPOS basics',
    durationLabel: '18 min',
    progressPercent: 0,
    status: 'not_started',
    description: '开单、拆单、改单、退单的基础操作流程。',
    tags: ['必修', '系统'],
  },
  {
    id: 'm-quiz-1',
    section: 'required',
    type: 'QUIZ',
    isRequired: true,
    titleCn: '入职结业测验',
    titleEn: 'Onboarding final',
    durationLabel: '20 题',
    progressPercent: 0,
    status: 'not_started',
    description: '10 题必答，满分 100，≥ 85 颁发「基础认证」。',
    tags: ['考核'],
  },
  {
    id: 'm-fire-1',
    section: 'required',
    type: 'ARTICLE',
    isRequired: true,
    titleCn: '消防应急手册',
    titleEn: 'Fire emergency manual',
    durationLabel: '12 min read',
    progressPercent: 0,
    status: 'not_started',
    description: '灭火器位置、疏散路线与现场协作。',
    tags: ['必修', '安全'],
  },
  {
    id: 'm-wine-1',
    section: 'optional',
    type: 'VIDEO',
    isRequired: false,
    titleCn: '中式佐餐酒搭配',
    titleEn: 'Chinese food & wine pairing',
    durationLabel: '45 min',
    progressPercent: 0,
    status: 'not_started',
    description: '黄酒、白酒、茶与招牌菜的口感映射。',
    tags: ['进阶', '品鉴'],
  },
  {
    id: 'm-lang-1',
    section: 'optional',
    type: 'VIDEO',
    isRequired: false,
    titleCn: '客人英语速成 · 前厅',
    titleEn: 'Guest English for FOH',
    durationLabel: '28 min',
    progressPercent: 0,
    status: 'not_started',
    description: '50 句高频场景英语，含音频跟读。',
    tags: ['进阶', '英语'],
  },
  {
    id: 'm-wine-2',
    section: 'optional',
    type: 'QUIZ',
    isRequired: false,
    titleCn: '酒品盲品小测',
    titleEn: 'Wine blind-taste quiz',
    durationLabel: '10 题',
    progressPercent: 0,
    status: 'not_started',
    description: '黄酒、米酒、精酿的风味辨识。',
    tags: ['进阶'],
  },
];
