export const NEW_ORDER_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "下单 · ORDER",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 下单 · 流程",
    title: "开始一笔",
    titleEm: "新订单",
    titleSuffix: "。",
    lede: "按三个步骤完成下单：选择供应商、挑选产品、确认并提交。",
    editKicker: "ZHAO's · 订单 · 修改",
    editTitle: "修改一笔",
    editTitleEm: "历史订单",
    editTitleSuffix: "。",
    editLede: "正在修改订单 {number}。供应商保持不变，可调整数量与送达日期，保存后会重新生成 PDF。",
    back: "返回首页",
    steps: [
      {
        id: "supplier",
        label: "供应商",
        title: "选择供应商",
        hint: "本次向哪家供应商采购？",
      },
      {
        id: "products",
        label: "产品",
        title: "挑选产品与数量",
        hint: "填写需要的数量，0 表示不采购。",
      },
      {
        id: "review",
        label: "确认",
        title: "确认并提交",
        hint: "核对信息后提交订单。",
      },
    ],
    storeList: "门店列表",
    supplierList: "供应商列表",
    productList: "产品列表",
    orderNoticeLabel: "下单须知",
    productImage: "图片",
    productSpecification: "规格",
    productUnit: "单位",
    productPrice: "单价",
    caseSpecReference: "整箱规格参考",
    noPrice: "暂无价格",
    quantity: "数量",
    subtotal: "小计",
    productQuickToolsLabel: "商品快捷工具",
    productCategoryLabel: "类别",
    productAllCategories: "全部分类",
    productUncategorized: "未分类",
    productCategoryOrder: [
      "fresh",
      "frais",
      "legumes",
      "vegetables",
      "fruit",
      "fruits",
      "meat",
      "viande",
      "seafood",
      "poisson",
      "frozen",
      "surgele",
      "surgeles",
      "dry",
      "sec",
      "sauce",
      "sauces",
      "drink",
      "drinks",
      "boisson",
      "boissons",
      "cleaning",
      "other",
    ],
    productCategoryNames: {
      fresh: "蔬菜水果",
      frais: "蔬菜水果",
      vegetables: "蔬菜水果",
      legumes: "蔬菜水果",
      fruit: "蔬菜水果",
      fruits: "蔬菜水果",
      meat: "肉类海鲜",
      viande: "肉类海鲜",
      seafood: "肉类海鲜",
      poisson: "肉类海鲜",
      frozen: "冷冻冷藏",
      surgele: "冷冻冷藏",
      surgeles: "冷冻冷藏",
      dry: "干货粮油",
      sec: "干货粮油",
      sauce: "调料酱料",
      sauces: "调料酱料",
      drink: "饮料酒水",
      drinks: "饮料酒水",
      boisson: "饮料酒水",
      boissons: "饮料酒水",
      cleaning: "清洁用品",
      other: "其他",
    },
    scrollToTop: "回到顶部",
    scrollToBottom: "跳到底部",
    total: "合计",
    next: "下一步 →",
    prev: "← 上一步",
    submit: "提交订单",
    submitting: "提交中…",
    updateOrder: "保存修改",
    updating: "保存中…",
    reviewStoreLabel: "门店",
    reviewSupplierLabel: "供应商",
    reviewDeliveryDateLabel: "送达日期",
    reviewItemsLabel: "订单项",
    reviewTotalLabel: "合计金额",
    emptyProducts: "尚未选择任何产品。",
    emptyStores: "数据库里还没有门店。",
    emptySuppliers: "数据库里还没有供应商。",
    emptyProductCatalog: "这家供应商还没有可下单的商品。",
    loadingStores: "门店加载中...",
    loadingSuppliers: "供应商加载中...",
    loadingProducts: "商品加载中...",
    loadingEditOrder: "历史订单加载中...",
    loadStoresError: "门店加载失败，请检查 restaurants 接口或数据库连接。",
    loadSuppliersError: "供应商加载失败，请检查 suppliers 接口或数据库连接。",
    loadProductsError: "商品加载失败，请检查 products 接口或数据库连接。",
    supplierOrderLabel: "排序",
    supplierAllProductsLabel: "全量商品",
    toastTitle: "订单已提交",
    toastBody: "我们已记录这次下单，PDF 单据已生成。",
    updateToastTitle: "订单已更新",
    updateToastBody: "这张订单已更新，PDF 单据已重新生成。",
    toastClose: "关闭",
    orderNumberLabel: "订单编号",
    sharePromptTitle: "订单已可发送",
    sharePromptSubtitle: "直接分享 PDF 到微信，发送完成后会进入历史订单。",
    shareToWechatButton: "发送到微信",
    shareLaterButton: "稍后处理",
    sharingOrder: "准备分享…",
    footer: "Since 2011 — ZHAO's Family Holding",
    currencySymbol: "€",
    selectStoreFirst: "请先选择一家门店。",
    selectSupplierFirst: "请先选择一家供应商。",
    selectAtLeastOneProduct: "请至少选择一个产品。",
    selectDeliveryDate: "请选择送达日期。",
    submitError: "订单提交失败，请稍后重试。",
    loadEditOrderError: "历史订单加载失败，请返回历史订单后重试。",
    orderCannotEdit: "这张订单已有退货记录，不能直接修改。",
    pdfOpenError: "PDF 预览打开失败，请到历史订单中重新打开。",
    pdfShareError: "PDF 分享失败，请到历史订单中重新下载。",
    editSupplierLocked: "修改历史订单时供应商不可变更。",
    stockLabel: "库存",
    inStock: "有货",
    outOfStock: "缺货",
    stockExceeded: "{name} 库存不足（库存 {stock}）。",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "PLACE ORDER · 下单",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · ORDER · WORKFLOW",
    title: "Start a ",
    titleEm: "new order",
    titleSuffix: ".",
    lede: "Three steps: pick a supplier, choose products, review and submit.",
    editKicker: "ZHAO's · ORDER · EDIT",
    editTitle: "Edit an ",
    editTitleEm: "existing order",
    editTitleSuffix: ".",
    editLede:
      "Editing order {number}. The supplier stays locked; update quantities or delivery date, then regenerate the PDF.",
    back: "Back to home",
    steps: [
      {
        id: "supplier",
        label: "Supplier",
        title: "Pick a supplier",
        hint: "Who are we ordering from today?",
      },
      {
        id: "products",
        label: "Products",
        title: "Pick products and quantities",
        hint: "Enter the quantities you need. 0 means skip.",
      },
      {
        id: "review",
        label: "Review",
        title: "Review and submit",
        hint: "Double-check the details before submitting.",
      },
    ],
    storeList: "Store list",
    supplierList: "Supplier list",
    productList: "Product list",
    orderNoticeLabel: "Order notice",
    productImage: "Image",
    productSpecification: "Spec",
    productUnit: "Unit",
    productPrice: "Unit price",
    caseSpecReference: "Case spec (ref.)",
    noPrice: "No price",
    quantity: "Qty",
    subtotal: "Subtotal",
    productQuickToolsLabel: "Product quick tools",
    productCategoryLabel: "Category",
    productAllCategories: "All categories",
    productUncategorized: "Uncategorized",
    productCategoryOrder: [
      "fresh",
      "frais",
      "legumes",
      "vegetables",
      "fruit",
      "fruits",
      "meat",
      "viande",
      "seafood",
      "poisson",
      "frozen",
      "surgele",
      "surgeles",
      "dry",
      "sec",
      "sauce",
      "sauces",
      "drink",
      "drinks",
      "boisson",
      "boissons",
      "cleaning",
      "other",
    ],
    productCategoryNames: {
      fresh: "Vegetables & fruit",
      frais: "Vegetables & fruit",
      vegetables: "Vegetables & fruit",
      legumes: "Vegetables & fruit",
      fruit: "Vegetables & fruit",
      fruits: "Vegetables & fruit",
      meat: "Meat & seafood",
      viande: "Meat & seafood",
      seafood: "Meat & seafood",
      poisson: "Meat & seafood",
      frozen: "Frozen & chilled",
      surgele: "Frozen & chilled",
      surgeles: "Frozen & chilled",
      dry: "Dry goods & oil",
      sec: "Dry goods & oil",
      sauce: "Seasonings & sauces",
      sauces: "Seasonings & sauces",
      drink: "Drinks & alcohol",
      drinks: "Drinks & alcohol",
      boisson: "Drinks & alcohol",
      boissons: "Drinks & alcohol",
      cleaning: "Cleaning supplies",
      other: "Other",
    },
    scrollToTop: "Back to top",
    scrollToBottom: "Go to bottom",
    total: "Total",
    next: "Next →",
    prev: "← Back",
    submit: "Submit order",
    submitting: "Submitting…",
    updateOrder: "Save changes",
    updating: "Saving…",
    reviewStoreLabel: "Store",
    reviewSupplierLabel: "Supplier",
    reviewDeliveryDateLabel: "Delivery date",
    reviewItemsLabel: "Items",
    reviewTotalLabel: "Total amount",
    emptyProducts: "No products selected yet.",
    emptyStores: "No stores are available in the database yet.",
    emptySuppliers: "No suppliers are available in the database yet.",
    emptyProductCatalog: "This supplier does not have any products yet.",
    loadingStores: "Loading stores...",
    loadingSuppliers: "Loading suppliers...",
    loadingProducts: "Loading products...",
    loadingEditOrder: "Loading historical order...",
    loadStoresError: "Failed to load stores. Check the restaurants API or database connection.",
    loadSuppliersError: "Failed to load suppliers. Check the suppliers API or database connection.",
    loadProductsError: "Failed to load products. Check the products API or database connection.",
    supplierOrderLabel: "Order",
    supplierAllProductsLabel: "All products",
    toastTitle: "Order submitted",
    toastBody: "The order has been recorded and its PDF is ready.",
    updateToastTitle: "Order updated",
    updateToastBody: "The order was updated and the PDF was regenerated.",
    toastClose: "Close",
    orderNumberLabel: "Order number",
    sharePromptTitle: "Order ready to send",
    sharePromptSubtitle: "Share the PDF directly to WeChat. After sharing, you will move to order history.",
    shareToWechatButton: "Send to WeChat",
    shareLaterButton: "Later",
    sharingOrder: "Preparing share…",
    footer: "Since 2011 — ZHAO's Family Holding",
    currencySymbol: "€",
    selectStoreFirst: "Please pick a store first.",
    selectSupplierFirst: "Please pick a supplier first.",
    selectAtLeastOneProduct: "Please pick at least one product.",
    selectDeliveryDate: "Please choose a delivery date.",
    submitError: "Order submission failed. Please try again.",
    loadEditOrderError: "Failed to load the historical order. Go back to history and retry.",
    orderCannotEdit: "This order already has returns and cannot be edited directly.",
    pdfOpenError: "Failed to open the PDF preview. Reopen it from order history.",
    pdfShareError: "Failed to share the PDF. Download it again from order history.",
    editSupplierLocked: "The supplier cannot be changed when editing an existing order.",
    stockLabel: "Stock",
    inStock: "In stock",
    outOfStock: "Out of stock",
    stockExceeded: "{name} exceeds available stock ({stock}).",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "COMMANDE · 下单",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · COMMANDE · PARCOURS",
    title: "Passer une ",
    titleEm: "nouvelle commande",
    titleSuffix: ".",
    lede: "Trois étapes : choisir le fournisseur, les produits, puis valider.",
    editKicker: "ZHAO's · COMMANDE · MODIFICATION",
    editTitle: "Modifier une ",
    editTitleEm: "commande existante",
    editTitleSuffix: ".",
    editLede:
      "Modification de la commande {number}. Le fournisseur reste verrouillé ; ajustez les quantités ou la date, puis regénérez le PDF.",
    back: "Retour à l'accueil",
    steps: [
      {
        id: "supplier",
        label: "Fournisseur",
        title: "Choisir un fournisseur",
        hint: "Chez qui commande-t-on aujourd'hui ?",
      },
      {
        id: "products",
        label: "Produits",
        title: "Choisir produits et quantités",
        hint: "Saisissez les quantités. 0 signifie ignorer le produit.",
      },
      {
        id: "review",
        label: "Validation",
        title: "Vérifier et envoyer",
        hint: "Vérifiez les informations avant d'envoyer.",
      },
    ],
    storeList: "Liste des boutiques",
    supplierList: "Liste des fournisseurs",
    productList: "Liste des produits",
    orderNoticeLabel: "Consignes de commande",
    productImage: "Image",
    productSpecification: "Format",
    productUnit: "Unité",
    productPrice: "Prix unitaire",
    caseSpecReference: "Format du carton",
    noPrice: "Prix indisponible",
    quantity: "Qté",
    subtotal: "Sous-total",
    productQuickToolsLabel: "Outils rapides produits",
    productCategoryLabel: "Catégorie",
    productAllCategories: "Toutes les catégories",
    productUncategorized: "Sans catégorie",
    productCategoryOrder: [
      "fresh",
      "frais",
      "legumes",
      "vegetables",
      "fruit",
      "fruits",
      "meat",
      "viande",
      "seafood",
      "poisson",
      "frozen",
      "surgele",
      "surgeles",
      "dry",
      "sec",
      "sauce",
      "sauces",
      "drink",
      "drinks",
      "boisson",
      "boissons",
      "cleaning",
      "other",
    ],
    productCategoryNames: {
      fresh: "Légumes et fruits",
      frais: "Légumes et fruits",
      vegetables: "Légumes et fruits",
      legumes: "Légumes et fruits",
      fruit: "Légumes et fruits",
      fruits: "Légumes et fruits",
      meat: "Viandes et produits de la mer",
      viande: "Viandes et produits de la mer",
      seafood: "Viandes et produits de la mer",
      poisson: "Viandes et produits de la mer",
      frozen: "Surgelés et frais",
      surgele: "Surgelés et frais",
      surgeles: "Surgelés et frais",
      dry: "Épicerie sèche et huiles",
      sec: "Épicerie sèche et huiles",
      sauce: "Assaisonnements et sauces",
      sauces: "Assaisonnements et sauces",
      drink: "Boissons et alcools",
      drinks: "Boissons et alcools",
      boisson: "Boissons et alcools",
      boissons: "Boissons et alcools",
      cleaning: "Produits d'entretien",
      other: "Autres",
    },
    scrollToTop: "Retour en haut",
    scrollToBottom: "Aller en bas",
    total: "Total",
    next: "Suivant →",
    prev: "← Retour",
    submit: "Valider la commande",
    submitting: "Envoi en cours…",
    updateOrder: "Enregistrer",
    updating: "Enregistrement…",
    reviewStoreLabel: "Boutique",
    reviewSupplierLabel: "Fournisseur",
    reviewDeliveryDateLabel: "Date de livraison",
    reviewItemsLabel: "Articles",
    reviewTotalLabel: "Montant total",
    emptyProducts: "Aucun produit sélectionné.",
    emptyStores: "Aucune boutique n'est encore disponible en base.",
    emptySuppliers: "Aucun fournisseur n'est encore disponible en base.",
    emptyProductCatalog: "Ce fournisseur n'a pas encore de produits commandables.",
    loadingStores: "Chargement des boutiques...",
    loadingSuppliers: "Chargement des fournisseurs...",
    loadingProducts: "Chargement des produits...",
    loadingEditOrder: "Chargement de la commande historique...",
    loadStoresError:
      "Impossible de charger les boutiques. Vérifiez l'API restaurants ou la connexion base de données.",
    loadSuppliersError:
      "Impossible de charger les fournisseurs. Vérifiez l'API suppliers ou la connexion base de données.",
    loadProductsError:
      "Impossible de charger les produits. Vérifiez l'API products ou la connexion base de données.",
    supplierOrderLabel: "Ordre",
    supplierAllProductsLabel: "Tous les produits",
    toastTitle: "Commande envoyée",
    toastBody: "La commande est enregistree et le PDF est pret.",
    updateToastTitle: "Commande mise à jour",
    updateToastBody: "La commande a été mise à jour et le PDF a été regénéré.",
    toastClose: "Fermer",
    orderNumberLabel: "Numero de commande",
    sharePromptTitle: "Commande prete a envoyer",
    sharePromptSubtitle:
      "Partagez directement le PDF sur WeChat. Apres l'envoi, vous passerez a l'historique.",
    shareToWechatButton: "Envoyer sur WeChat",
    shareLaterButton: "Plus tard",
    sharingOrder: "Preparation du partage…",
    footer: "Since 2011 — ZHAO's Family Holding",
    currencySymbol: "€",
    selectStoreFirst: "Choisissez d'abord une boutique.",
    selectSupplierFirst: "Choisissez d'abord un fournisseur.",
    selectAtLeastOneProduct: "Choisissez au moins un produit.",
    selectDeliveryDate: "Choisissez une date de livraison.",
    submitError: "Impossible d'envoyer la commande. Veuillez reessayer.",
    loadEditOrderError:
      "Impossible de charger la commande historique. Revenez à l'historique puis réessayez.",
    orderCannotEdit:
      "Cette commande contient déjà un retour et ne peut pas être modifiée directement.",
    pdfOpenError: "Impossible d'ouvrir l'aperçu PDF. Rouvrez-le depuis l'historique.",
    pdfShareError:
      "Impossible de partager le PDF. Telechargez-le depuis l'historique.",
    editSupplierLocked: "Le fournisseur ne peut pas être modifié lors de l'édition d'une commande.",
    stockLabel: "Stock",
    inStock: "En stock",
    outOfStock: "En rupture",
    stockExceeded: "{name} dépasse le stock disponible ({stock}).",
  },
};

export const MOCK_SUPPLIERS = [
  {
    id: "metro-france",
    name: { zh: "Metro 法国", en: "Metro France", fr: "Metro France" },
    city: { zh: "巴黎", en: "Paris", fr: "Paris" },
    specialty: { zh: "综合食材", en: "General groceries", fr: "Épicerie générale" },
  },
  {
    id: "sino-market",
    name: { zh: "巴黎中华批发", en: "Sino Market", fr: "Sino Market" },
    city: { zh: "巴黎", en: "Paris", fr: "Paris" },
    specialty: { zh: "亚洲食材", en: "Asian groceries", fr: "Épicerie asiatique" },
  },
  {
    id: "transgourmet",
    name: { zh: "Transgourmet", en: "Transgourmet", fr: "Transgourmet" },
    city: { zh: "里昂", en: "Lyon", fr: "Lyon" },
    specialty: { zh: "生鲜与肉类", en: "Fresh & meat", fr: "Frais & viande" },
  },
  {
    id: "bio-sud",
    name: { zh: "南方有机", en: "Bio-Sud", fr: "Bio-Sud" },
    city: { zh: "马赛", en: "Marseille", fr: "Marseille" },
    specialty: { zh: "有机蔬果", en: "Organic produce", fr: "Fruits & légumes bio" },
  },
];

export const MOCK_PRODUCTS = {
  "metro-france": [
    {
      id: "oil-5l",
      name: { zh: "葵花籽油 5L", en: "Sunflower oil 5L", fr: "Huile de tournesol 5L" },
      unit: { zh: "桶", en: "can", fr: "bidon" },
      price: 18.5,
    },
    {
      id: "rice-25kg",
      name: { zh: "泰国香米 25kg", en: "Thai rice 25kg", fr: "Riz thaï 25kg" },
      unit: { zh: "袋", en: "bag", fr: "sac" },
      price: 42.0,
    },
    {
      id: "napkins",
      name: { zh: "餐巾纸 箱", en: "Napkins (box)", fr: "Serviettes (carton)" },
      unit: { zh: "箱", en: "box", fr: "carton" },
      price: 24.9,
    },
    {
      id: "foil-trays",
      name: { zh: "外卖铝盒 500", en: "Foil trays x500", fr: "Barquettes alu x500" },
      unit: { zh: "箱", en: "box", fr: "carton" },
      price: 58.0,
    },
  ],
  "sino-market": [
    {
      id: "soy-sauce",
      name: { zh: "生抽 5L", en: "Light soy sauce 5L", fr: "Sauce soja claire 5L" },
      unit: { zh: "桶", en: "can", fr: "bidon" },
      price: 22.0,
    },
    {
      id: "sichuan-peppercorn",
      name: { zh: "青花椒 1kg", en: "Sichuan peppercorn 1kg", fr: "Poivre du Sichuan 1kg" },
      unit: { zh: "袋", en: "bag", fr: "sachet" },
      price: 36.0,
    },
    {
      id: "noodles",
      name: { zh: "手工拉面 5kg", en: "Hand-pulled noodles 5kg", fr: "Nouilles main 5kg" },
      unit: { zh: "箱", en: "box", fr: "carton" },
      price: 28.5,
    },
  ],
  transgourmet: [
    {
      id: "pork-belly",
      name: { zh: "五花肉 kg", en: "Pork belly (kg)", fr: "Poitrine de porc (kg)" },
      unit: { zh: "公斤", en: "kg", fr: "kg" },
      price: 9.2,
    },
    {
      id: "chicken-thigh",
      name: {
        zh: "去骨鸡腿 kg",
        en: "Boneless chicken thigh (kg)",
        fr: "Cuisse de poulet désossée (kg)",
      },
      unit: { zh: "公斤", en: "kg", fr: "kg" },
      price: 7.8,
    },
    {
      id: "beef-flank",
      name: { zh: "牛腩 kg", en: "Beef flank (kg)", fr: "Plat de côte de bœuf (kg)" },
      unit: { zh: "公斤", en: "kg", fr: "kg" },
      price: 14.5,
    },
  ],
  "bio-sud": [
    {
      id: "tomato",
      name: { zh: "有机番茄 kg", en: "Organic tomato (kg)", fr: "Tomate bio (kg)" },
      unit: { zh: "公斤", en: "kg", fr: "kg" },
      price: 3.8,
    },
    {
      id: "bok-choy",
      name: { zh: "有机青菜 kg", en: "Organic bok choy (kg)", fr: "Pak choï bio (kg)" },
      unit: { zh: "公斤", en: "kg", fr: "kg" },
      price: 4.2,
    },
    {
      id: "ginger",
      name: { zh: "生姜 kg", en: "Ginger (kg)", fr: "Gingembre (kg)" },
      unit: { zh: "公斤", en: "kg", fr: "kg" },
      price: 6.0,
    },
  ],
};
