export const FLOATING_ASSET_ITEMS = [
  {
    src: "/assets/svg/IMG_9713.PNG",
    alt: "",
    width: 116,
    left: "4%",
    delay: "-22s",
    duration: "26s",
    drift: "8vw",
    rotateStart: "-12deg",
    rotateEnd: "180deg",
    startY: "-26vh",
  },
  {
    src: "/assets/svg/IMG_9722.PNG",
    alt: "",
    width: 76,
    left: "12%",
    delay: "-7s",
    duration: "26s",
    drift: "-6vw",
    rotateStart: "8deg",
    rotateEnd: "-160deg",
    startY: "-14vh",
  },
  {
    src: "/assets/svg/IMG_9723.PNG",
    alt: "",
    width: 72,
    left: "19%",
    delay: "-16s",
    duration: "26s",
    drift: "5vw",
    rotateStart: "-8deg",
    rotateEnd: "150deg",

    startY: "-30vh",
  },
  {
    src: "/assets/svg/IMG_9724.PNG",
    alt: "",
    width: 86,
    left: "27%",
    delay: "-3s",
    duration: "26s",
    drift: "-8vw",
    rotateStart: "6deg",
    rotateEnd: "-170deg",

    startY: "-8vh",
  },
  {
    src: "/assets/svg/IMG_9725.PNG",
    alt: "",
    width: 66,
    left: "35%",
    delay: "-19s",
    duration: "26s",
    drift: "6vw",
    rotateStart: "-6deg",
    rotateEnd: "155deg",

    startY: "-22vh",
  },
  {
    src: "/assets/svg/IMG_9726.PNG",
    alt: "",
    width: 62,
    left: "43%",
    delay: "-12s",
    duration: "26s",
    drift: "-5vw",
    rotateStart: "7deg",
    rotateEnd: "-145deg",

    startY: "-12vh",
  },
  {
    src: "/assets/svg/IMG_9727.PNG",
    alt: "",
    width: 60,
    left: "51%",
    delay: "-26s",
    duration: "26s",
    drift: "7vw",
    rotateStart: "-10deg",
    rotateEnd: "185deg",

    startY: "-34vh",
  },
  {
    src: "/assets/svg/IMG_9728.PNG",
    alt: "",
    width: 96,
    left: "59%",
    delay: "-35s",
    duration: "26s",
    drift: "-7vw",
    rotateStart: "10deg",
    rotateEnd: "-180deg",

    startY: "-18vh",
  },
  {
    src: "/assets/svg/IMG_9729.PNG",
    alt: "",
    width: 108,
    left: "68%",
    delay: "-28s",
    duration: "26s",
    drift: "9vw",
    rotateStart: "-12deg",
    rotateEnd: "190deg",

    startY: "-36vh",
  },
  {
    src: "/assets/svg/IMG_9733.PNG",
    alt: "",
    width: 102,
    left: "76%",
    delay: "-9s",
    duration: "26s",
    drift: "-8vw",
    rotateStart: "9deg",
    rotateEnd: "-170deg",

    startY: "-10vh",
  },
  {
    src: "/assets/svg/IMG_9734.PNG",
    alt: "",
    width: 82,
    left: "84%",
    delay: "-21s",
    duration: "26s",
    drift: "5vw",
    rotateStart: "-7deg",
    rotateEnd: "150deg",

    startY: "-24vh",
  },
  {
    src: "/assets/svg/IMG_9735.PNG",
    alt: "",
    width: 74,
    left: "91%",
    delay: "-14s",
    duration: "26s",
    drift: "-6vw",
    rotateStart: "7deg",
    rotateEnd: "-160deg",

    startY: "-16vh",
  },
];
