import { StyleSheet } from "react-native";

import { authControlStyles } from "@/features/auth/AuthFormControls";
import { scaleStyles } from "@/lib/responsive";

export const dashboardNewsBoardStyles = StyleSheet.create(
  scaleStyles({
    articleBody: {
      color: authControlStyles.colors.ink60,
      fontSize: 16,
      lineHeight: 26,
    },
    articleBodyWithSummary: {
      marginTop: 14,
    },
    articleContent: {
      borderBottomColor: "rgba(193, 22, 22, 0.16)",
      borderBottomWidth: 1,
      paddingHorizontal: 4,
      paddingVertical: 22,
    },
    articleControls: {
      alignItems: "center",
      flexDirection: "row",
      gap: 12,
      justifyContent: "space-between",
      marginTop: 20,
    },
    articleFooter: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 20,
    },
    articleHeader: {
      paddingHorizontal: 4,
      paddingTop: 24,
    },
    articleKicker: {
      color: authControlStyles.colors.red,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1.8,
      textTransform: "uppercase",
    },
    articleKickerRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    articleMeta: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      letterSpacing: 0.8,
      lineHeight: 16,
      marginTop: 12,
    },
    articleStore: {
      color: authControlStyles.colors.ink40,
      fontFamily: "serif",
      fontSize: 13,
    },
    articleSummary: {
      color: authControlStyles.colors.ink,
      fontSize: 18,
      fontWeight: "600",
      lineHeight: 28,
    },
    articleTitle: {
      color: authControlStyles.colors.ink,
      fontSize: 34,
      fontWeight: "600",
      letterSpacing: -0.5,
      lineHeight: 40,
      marginTop: 16,
    },
    board: {
      marginTop: 26,
    },
    featureFallback: {
      alignItems: "center",
      backgroundColor: authControlStyles.colors.red,
      gap: 18,
      height: 280,
      justifyContent: "center",
    },
    featureFallbackSeal: {
      height: 112,
      opacity: 0.92,
      width: 112,
    },
    featureFallbackText: {
      color: "#ffffff",
      fontFamily: "monospace",
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 2,
    },
    featureImage: {
      backgroundColor: "#ffffff",
      height: 280,
      width: "100%",
    },
    featureMedia: {
      backgroundColor: authControlStyles.colors.ink,
      borderColor: authControlStyles.colors.ink,
      borderWidth: 2,
      height: 284,
      marginTop: 20,
      overflow: "hidden",
    },
    featurePdf: {
      backgroundColor: "#ffffff",
      flex: 1,
      width: "100%",
    },
    featurePdfFrame: {
      height: 280,
      width: "100%",
    },
    featureVideo: {
      backgroundColor: authControlStyles.colors.ink,
      height: 280,
      width: "100%",
    },
    pager: {
      alignItems: "center",
      alignSelf: "flex-start",
      borderColor: "rgba(193, 22, 22, 0.18)",
      borderWidth: 1,
      flexDirection: "row",
      flexShrink: 0,
      marginLeft: "auto",
    },
    pagerButton: {
      alignItems: "center",
      height: 44,
      justifyContent: "center",
      width: 48,
    },
    pagerDisabled: {
      opacity: 0.28,
    },
    pagerPosition: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
      minWidth: 94,
      textAlign: "center",
    },
    search: {
      alignItems: "center",
      borderColor: authControlStyles.colors.ink10,
      borderWidth: 1,
      flexDirection: "row",
      gap: 10,
      marginTop: 22,
      minHeight: 50,
      paddingHorizontal: 14,
    },
    searchInput: {
      color: authControlStyles.colors.ink,
      flex: 1,
      fontFamily: "serif",
      fontSize: 15,
      minHeight: 48,
      paddingVertical: 0,
    },
    state: {
      minHeight: 160,
      justifyContent: "center",
    },
    stateText: {
      color: authControlStyles.colors.ink60,
      fontFamily: "serif",
      fontSize: 15,
      lineHeight: 24,
      paddingVertical: 28,
      textAlign: "center",
    },
    tab: {
      alignItems: "center",
      borderBottomColor: "transparent",
      borderBottomWidth: 2,
      flex: 1,
      flexDirection: "row",
      gap: 8,
      justifyContent: "space-between",
      minHeight: 52,
      paddingHorizontal: 12,
    },
    tabActive: {
      borderBottomColor: authControlStyles.colors.red,
    },
    tabCount: {
      color: authControlStyles.colors.ink40,
      fontFamily: "monospace",
      fontSize: 10,
    },
    tabLabel: {
      color: authControlStyles.colors.ink60,
      fontFamily: "monospace",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    tabLabelActive: {
      color: authControlStyles.colors.red,
    },
    tabs: {
      borderBottomColor: authControlStyles.colors.ink10,
      borderBottomWidth: 1,
      borderTopColor: authControlStyles.colors.ink20,
      borderTopWidth: 1,
      flexDirection: "row",
    },
    tag: {
      borderColor: "rgba(193, 22, 22, 0.18)",
      borderWidth: 1,
      color: authControlStyles.colors.red,
      fontSize: 12,
      paddingHorizontal: 9,
      paddingVertical: 6,
    },
    tags: {
      flex: 1,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    visibility: {
      borderColor: "rgba(16, 126, 86, 0.42)",
      borderRadius: 999,
      borderWidth: 1,
      color: "#107e56",
      fontFamily: "monospace",
      fontSize: 9,
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
  }),
);
