export const SUPPLIERS_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "供应商 · SUPPLIERS",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 供应商 · 管理",
    title: "供应商",
    titleEm: "管理",
    titleSuffix: "。",
    lede: "维护你的供应商清单与商品目录。所有字段可编辑、删除或新增。",
    back: "返回首页",
    backToList: "← 返回供应商列表",
    footer: "Since 2011 — ZHAO's Family Holding",

    loading: "加载中…",
    loadError: "加载失败，请重试。",
    saving: "保存中…",
    deleting: "删除中…",
    saveError: "保存失败，请重试。",
    deleteError: "删除失败，请重试。",

    listHeading: "供应商列表",
    count: "家供应商",
    addSupplier: "+ 添加供应商",
    newSupplierTitle: "新增供应商",
    metricSuppliers: "供应商",
    metricProducts: "商品",
    metricDefaultAll: "默认全商品",
    searchPlaceholder: "搜索供应商名称、排序或 ID",
    clearSearch: "清空",
    noSuppliers: "没有匹配的供应商。",

    fieldName: "名称",
    fieldSortOrder: "排序",
    fieldIncludeAll: "默认全部商品",

    namePlaceholder: "如：Metro 法国",

    save: "保存",
    cancel: "取消",
    edit: "编辑",
    deleteBtn: "删除",
    open: "打开",

    confirmDeleteSupplier:
      "确认删除供应商「{name}」吗？该供应商下的所有商品也会一并删除。",
    confirmDeleteProduct: "确认删除商品「{name}」吗？",
    yes: "确认删除",
    no: "取消",

    detailInfoHeading: "基础信息",
    detailInfoHint: "这里的信息会在下单流程中显示。",
    editInfo: "编辑",
    editing: "编辑中",

    productsHeading: "商品目录",
    productsHint: "所有字段可编辑；行尾的按钮用于保存、取消或删除。",
    productsCount: "件商品",
    addProduct: "+ 添加商品",
    noProducts: "还没有商品，点击上方按钮添加第一个。",

    colReference: "编号",
    colSupplier: "供应商",
    colCategory: "类别 *",
    colNameCn: "中文名 *",
    colDesignationFr: "法文名",
    colUnit: "单位",
    colPrice: "单价",
    colSpecification: "规格",
    colImage: "图片 URL",
    colActions: "操作",

    referencePlaceholder: "REF-XXX",
    categoryPlaceholder: "类别",
    pricePlaceholder: "0.00",
    unitPlaceholder: "袋 / 箱 / 公斤",
    imagePlaceholder: "https://…",
    productSearchPlaceholder: "搜索编号、名称、规格或单位",
    categoryFilter: "类别筛选",
    allCategories: "全部类别",
    noMatchedProducts: "没有匹配的商品。",

    validation: {
      nameRequired: "名称不能为空。",
      categoryRequired: "类别不能为空。",
      nameCnRequired: "中文名不能为空。",
      priceInvalid: "单价必须为数字。",
    },
    currencySymbol: "€",
    truePill: "是",
    falsePill: "否",
    notFound: "找不到该供应商。",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "SUPPLIERS · 供应商",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · SUPPLIERS · MANAGEMENT",
    title: "Supplier ",
    titleEm: "management",
    titleSuffix: ".",
    lede: "Manage your supplier list and product catalog. Every field can be edited, deleted or added.",
    back: "Back to home",
    backToList: "← Back to supplier list",
    footer: "Since 2011 — ZHAO's Family Holding",

    loading: "Loading…",
    loadError: "Failed to load. Please retry.",
    saving: "Saving…",
    deleting: "Deleting…",
    saveError: "Save failed. Please retry.",
    deleteError: "Delete failed. Please retry.",

    listHeading: "Supplier list",
    count: "suppliers",
    addSupplier: "+ Add supplier",
    newSupplierTitle: "New supplier",
    metricSuppliers: "Suppliers",
    metricProducts: "Products",
    metricDefaultAll: "Default all",
    searchPlaceholder: "Search supplier name, order or ID",
    clearSearch: "Clear",
    noSuppliers: "No matching suppliers.",

    fieldName: "Name",
    fieldSortOrder: "Sort order",
    fieldIncludeAll: "Include all products",

    namePlaceholder: "e.g., Metro France",

    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    deleteBtn: "Delete",
    open: "Open",

    confirmDeleteSupplier:
      'Delete supplier "{name}"? All its products will also be removed.',
    confirmDeleteProduct: 'Delete product "{name}"?',
    yes: "Confirm delete",
    no: "Cancel",

    detailInfoHeading: "Basic info",
    detailInfoHint: "These fields are shown during the order flow.",
    editInfo: "Edit",
    editing: "Editing",

    productsHeading: "Product catalog",
    productsHint:
      "Every field is editable; the trailing buttons save, cancel or delete the row.",
    productsCount: "products",
    addProduct: "+ Add product",
    noProducts: "No products yet. Click the button above to add the first one.",

    colReference: "Reference",
    colSupplier: "Supplier",
    colCategory: "Category *",
    colNameCn: "Chinese name *",
    colDesignationFr: "French name",
    colUnit: "Unit",
    colPrice: "Unit price",
    colSpecification: "Specification",
    colImage: "Image URL",
    colActions: "Actions",

    referencePlaceholder: "REF-XXX",
    categoryPlaceholder: "Category",
    pricePlaceholder: "0.00",
    unitPlaceholder: "bag / box / kg",
    imagePlaceholder: "https://…",
    productSearchPlaceholder: "Search reference, name, spec or unit",
    categoryFilter: "Category filter",
    allCategories: "All categories",
    noMatchedProducts: "No matching products.",

    validation: {
      nameRequired: "Name is required.",
      categoryRequired: "Category is required.",
      nameCnRequired: "Chinese name is required.",
      priceInvalid: "Price must be a number.",
    },
    currencySymbol: "€",
    truePill: "Yes",
    falsePill: "No",
    notFound: "Supplier not found.",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "FOURNISSEURS · 供应商",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · FOURNISSEURS · GESTION",
    title: "Gestion des ",
    titleEm: "fournisseurs",
    titleSuffix: ".",
    lede: "Gérez votre liste de fournisseurs et catalogue produits. Tous les champs sont éditables, supprimables ou ajoutables.",
    back: "Retour à l'accueil",
    backToList: "← Retour à la liste",
    footer: "Since 2011 — ZHAO's Family Holding",

    loading: "Chargement…",
    loadError: "Échec du chargement. Réessayez.",
    saving: "Enregistrement…",
    deleting: "Suppression…",
    saveError: "Échec de l'enregistrement. Réessayez.",
    deleteError: "Échec de la suppression. Réessayez.",

    listHeading: "Liste des fournisseurs",
    count: "fournisseurs",
    addSupplier: "+ Ajouter un fournisseur",
    newSupplierTitle: "Nouveau fournisseur",
    metricSuppliers: "Fournisseurs",
    metricProducts: "Produits",
    metricDefaultAll: "Tous par défaut",
    searchPlaceholder: "Rechercher nom, ordre ou ID",
    clearSearch: "Effacer",
    noSuppliers: "Aucun fournisseur correspondant.",

    fieldName: "Nom",
    fieldSortOrder: "Ordre",
    fieldIncludeAll: "Tous les produits par défaut",

    namePlaceholder: "ex. Metro France",

    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    deleteBtn: "Supprimer",
    open: "Ouvrir",

    confirmDeleteSupplier:
      "Supprimer le fournisseur «{name}» ? Tous ses produits seront également supprimés.",
    confirmDeleteProduct: "Supprimer le produit «{name}» ?",
    yes: "Confirmer la suppression",
    no: "Annuler",

    detailInfoHeading: "Informations générales",
    detailInfoHint: "Ces champs sont affichés dans le parcours de commande.",
    editInfo: "Modifier",
    editing: "Édition",

    productsHeading: "Catalogue produits",
    productsHint:
      "Tous les champs sont éditables ; les boutons en fin de ligne enregistrent, annulent ou suppriment.",
    productsCount: "produits",
    addProduct: "+ Ajouter un produit",
    noProducts:
      "Aucun produit pour l'instant. Cliquez sur le bouton pour en ajouter un.",

    colReference: "Référence",
    colSupplier: "Fournisseur",
    colCategory: "Catégorie *",
    colNameCn: "Nom chinois *",
    colDesignationFr: "Nom français",
    colUnit: "Unité",
    colPrice: "Prix unitaire",
    colSpecification: "Spécification",
    colImage: "URL image",
    colActions: "Actions",

    referencePlaceholder: "REF-XXX",
    categoryPlaceholder: "Catégorie",
    pricePlaceholder: "0.00",
    unitPlaceholder: "sac / carton / kg",
    imagePlaceholder: "https://…",
    productSearchPlaceholder: "Rechercher référence, nom, spec ou unité",
    categoryFilter: "Filtre catégorie",
    allCategories: "Toutes catégories",
    noMatchedProducts: "Aucun produit correspondant.",

    validation: {
      nameRequired: "Le nom est obligatoire.",
      categoryRequired: "La catégorie est obligatoire.",
      nameCnRequired: "Le nom chinois est obligatoire.",
      priceInvalid: "Le prix doit être un nombre.",
    },
    currencySymbol: "€",
    truePill: "Oui",
    falsePill: "Non",
    notFound: "Fournisseur introuvable.",
  },
};
