import { StyleSheet } from "react-native";

import { authControlStyles } from "@/features/auth/AuthFormControls";
import { scaleStyles } from "@/lib/responsive";

const { colors } = authControlStyles;

export const recipeStyles = StyleSheet.create(scaleStyles({
  backButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    minHeight: 44,
  },
  backButtonText: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  categoryButton: {
    alignItems: "center",
    borderColor: colors.ink20,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 15,
  },
  categoryButtonActive: {
    backgroundColor: colors.red,
    borderColor: colors.red,
  },
  categoryRow: {
    gap: 8,
    paddingRight: 20,
  },
  categoryScroller: {
    marginHorizontal: -20,
    marginTop: -2,
  },
  categoryText: {
    color: colors.ink60,
    fontFamily: "serif",
    fontSize: 13,
  },
  categoryTextActive: {
    color: colors.paper,
  },
  detailIntro: {
    gap: 12,
  },
  detailTitle: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 30,
    fontWeight: "500",
    letterSpacing: -0.6,
    lineHeight: 38,
  },
  emptyDetail: {
    color: colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  emptyState: {
    borderColor: colors.ink20,
    borderWidth: 1,
    gap: 10,
    padding: 20,
  },
  emptyTitle: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 20,
    fontWeight: "500",
  },
  favoriteButton: {
    alignSelf: "flex-start",
    borderColor: colors.red,
    borderWidth: 1,
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  favoriteButtonText: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  featuredAction: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.7,
  },
  featuredBody: {
    gap: 14,
    padding: 16,
  },
  featuredImage: {
    height: 178,
    width: "100%",
  },
  featuredKicker: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 8,
  },
  featuredMeta: {
    color: colors.ink60,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 0.3,
    marginTop: 8,
  },
  featuredRecipe: {
    borderColor: colors.ink,
    borderWidth: 1,
  },
  featuredTitle: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 26,
    fontWeight: "500",
    letterSpacing: -0.5,
  },
  heroImage: {
    height: 196,
    width: "100%",
  },
  ingredientAmount: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 13,
  },
  ingredientName: {
    color: colors.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 16,
  },
  ingredientRow: {
    alignItems: "center",
    borderBottomColor: colors.ink10,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 46,
  },
  ingredientUnit: {
    color: colors.ink40,
    fontFamily: "monospace",
    fontSize: 11,
    minWidth: 26,
  },
  libraryCount: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  libraryHeader: {
    alignItems: "baseline",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  libraryTitle: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 22,
    fontWeight: "500",
  },
  meta: {
    color: colors.ink60,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 0.3,
    lineHeight: 16,
  },
  module: {
    gap: 20,
    paddingBottom: 104,
    paddingTop: 18,
  },
  noteText: {
    color: colors.ink60,
    fontFamily: "serif",
    fontSize: 15,
    lineHeight: 23,
  },
  pageIntro: {
    gap: 10,
  },
  recipeCount: {
    alignItems: "center",
    backgroundColor: colors.red,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  recipeCountText: {
    color: colors.paper,
    fontFamily: "monospace",
    fontSize: 12,
    fontWeight: "700",
  },
  recipeList: {
    gap: 0,
    paddingBottom: 12,
  },
  recipeRow: {
    borderBottomColor: colors.ink20,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 13,
    paddingVertical: 14,
  },
  recipeRowBody: {
    flex: 1,
    gap: 7,
    paddingVertical: 2,
  },
  recipeRowImage: {
    height: 88,
    width: 92,
  },
  recipeRowTitle: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 19,
    fontWeight: "500",
    lineHeight: 25,
  },
  roleCaption: {
    color: colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  scaleControl: {
    alignItems: "center",
    borderColor: colors.ink20,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
    paddingHorizontal: 9,
  },
  scaleNumber: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 19,
    fontWeight: "600",
    textAlign: "center",
  },
  scaleText: {
    color: colors.ink60,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 0.5,
  },
  scaleToggle: {
    alignItems: "center",
    backgroundColor: colors.red,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  scaleToggleText: {
    color: colors.paper,
    fontFamily: "monospace",
    fontSize: 19,
  },
  search: {
    borderBottomColor: colors.ink,
    borderBottomWidth: 1,
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 2,
  },
  section: {
    gap: 12,
  },
  searchEmptyState: {
    alignItems: "center",
    borderColor: colors.ink20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    minHeight: 72,
    marginTop: 8,
    paddingHorizontal: 16,
  },
  searchEmptyText: {
    color: colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
  },
  sectionKicker: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.1,
  },
  stepCheck: {
    alignItems: "center",
    borderColor: colors.ink40,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    marginTop: 1,
    width: 24,
  },
  stepCheckDone: {
    backgroundColor: colors.red,
    borderColor: colors.red,
  },
  stepItem: {
    alignItems: "flex-start",
    borderBottomColor: colors.ink10,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingVertical: 13,
  },
  stepNumber: {
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    paddingTop: 4,
    width: 22,
  },
  stepText: {
    color: colors.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 16,
    lineHeight: 24,
  },
  stepTextDone: {
    color: colors.ink40,
    textDecorationLine: "line-through",
  },
  tag: {
    backgroundColor: "rgba(193, 22, 22, 0.08)",
    color: colors.red,
    fontFamily: "monospace",
    fontSize: 10,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  title: {
    color: colors.ink,
    fontFamily: "serif",
    fontSize: 34,
    fontWeight: "500",
    letterSpacing: -0.9,
    lineHeight: 41,
  },
  titleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
}));
