import { StyleSheet } from "react-native";
import { isTablet, scaleStyles } from "@/lib/responsive";
import { authControlStyles } from "@/features/auth/AuthFormControls";

export const storeStyles = StyleSheet.create(scaleStyles({
  actionButton: {
    alignItems: "center",
    borderColor: "rgba(193, 22, 22, 0.34)",
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  actionButtonDanger: {
    borderColor: "rgba(10, 10, 10, 0.16)",
  },
  actionButtonPrimary: {
    backgroundColor: authControlStyles.colors.red,
  },
  actionButtonText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  actionButtonTextPrimary: {
    color: "#ffffff",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
  },
  backButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: "rgba(193, 22, 22, 0.28)",
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: 12,
  },
  backButtonText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  card: {
    backgroundColor: "#ffffff",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  cardBody: {
    gap: 8,
  },
  cardImage: {
    alignItems: "center",
    backgroundColor: "rgba(193, 22, 22, 0.08)",
    // On tablets the photo gets an extra bump on top of the global 1.25x
    // scale (final ~500pt) so it reads larger in the wider layout.
    height: isTablet ? 400 : 118,
    justifyContent: "center",
    overflow: "hidden",
  },
  cardImageMedia: {
    height: "100%",
    width: "100%",
  },
  cardImageText: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 2,
  },
  cardMeta: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 13,
    lineHeight: 19,
  },
  cardName: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 22,
    fontWeight: "600",
    lineHeight: 27,
  },
  cardStats: {
    borderTopColor: authControlStyles.colors.ink10,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingTop: 12,
  },
  container: {
    gap: 18,
    paddingTop: 22,
  },
  contractAddPill: {
    borderStyle: "dashed",
    opacity: 0.6,
  },
  contractCard: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  contractCardTitle: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 14,
    fontWeight: "700",
  },
  contractChip: {
    alignItems: "center",
    borderColor: "rgba(193, 22, 22, 0.38)",
    borderWidth: 1,
    flexDirection: "row",
    paddingLeft: 10,
  },
  contractChipInput: {
    borderLeftColor: authControlStyles.colors.ink10,
    borderLeftWidth: 1,
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 15,
    marginLeft: 10,
    minHeight: 38,
    textAlign: "center",
    width: 50,
  },
  contractChipLabel: {
    color: authControlStyles.colors.red,
    fontFamily: "monospace",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  contractChipToggle: {
    paddingVertical: 9,
  },
  contractRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detailHero: {
    backgroundColor: "#ffffff",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  detailTitle: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 28,
    fontWeight: "600",
    lineHeight: 33,
  },
  detailActionCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "rgba(193, 22, 22, 0.22)",
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    minHeight: 88,
    padding: 16,
  },
  detailActionContent: {
    flex: 1,
    gap: 6,
  },
  detailActionCount: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 30,
    fontWeight: "700",
  },
  detailActionLabel: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 21,
    fontWeight: "700",
    lineHeight: 26,
  },
  emptyText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  filterPill: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  filterPillActive: {
    backgroundColor: authControlStyles.colors.red,
    borderColor: authControlStyles.colors.red,
  },
  filterPillText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 13,
  },
  filterPillTextActive: {
    color: "#ffffff",
    fontWeight: "700",
  },
  filterScroller: {
    flexGrow: 0,
    marginHorizontal: -2,
  },
  filterScrollerContent: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 2,
  },
  header: {
    gap: 8,
  },
  hint: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 15,
    lineHeight: 22,
  },
  list: {
    gap: 12,
  },
  message: {
    color: authControlStyles.colors.red,
    fontFamily: "serif",
    fontSize: 14,
    lineHeight: 21,
  },
  searchInput: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 15,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  roleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  rolePill: {
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  rolePillActive: {
    backgroundColor: "rgba(193, 22, 22, 0.08)",
    borderColor: "rgba(193, 22, 22, 0.38)",
  },
  rolePillText: {
    color: authControlStyles.colors.ink60,
    fontFamily: "serif",
    fontSize: 13,
  },
  rolePillTextActive: {
    color: authControlStyles.colors.red,
    fontWeight: "700",
  },
  roleSelectPanel: {
    borderColor: authControlStyles.colors.ink10,
    borderRadius: 18,
    borderWidth: 1,
    maxHeight: 240,
    paddingHorizontal: 16,
  },
  roleSwitch: {
    transform: [{ scaleX: 0.78 }, { scaleY: 0.78 }],
  },
  roleSwitchRow: {
    alignItems: "center",
    borderTopColor: authControlStyles.colors.ink10,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
    paddingVertical: 6,
  },
  roleSwitchLabel: {
    color: authControlStyles.colors.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 15,
    fontWeight: "500",
    marginRight: 12,
  },
  roleSwitchLabelActive: {
    color: authControlStyles.colors.red,
    fontWeight: "700",
  },
  section: {
    gap: 12,
  },
  sectionHeader: {
    alignItems: "center",
    borderBottomColor: "rgba(193, 22, 22, 0.18)",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 10,
  },
  sectionTitle: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 21,
    fontWeight: "600",
  },
  statsList: {
    backgroundColor: "#ffffff",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
  },
  statsRow: {
    alignItems: "center",
    borderBottomColor: authControlStyles.colors.ink10,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
    paddingHorizontal: 14,
  },
  statsRowLast: {
    borderBottomWidth: 0,
  },
  stat: {
    flex: 1,
    gap: 4,
  },
  statLabel: {
    color: authControlStyles.colors.ink40,
    fontFamily: "monospace",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  statValue: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 22,
    fontWeight: "600",
  },
  title: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 34,
    fontWeight: "500",
    lineHeight: 39,
  },
  titleAccent: {
    color: authControlStyles.colors.red,
    fontStyle: "italic",
    fontWeight: "400",
  },
  teamCardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  teamCardIdentity: {
    flex: 1,
  },
  teamDeleteButton: {
    alignItems: "center",
    borderColor: "rgba(193, 22, 22, 0.34)",
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 14,
  },
  userCard: {
    backgroundColor: "#ffffff",
    borderColor: authControlStyles.colors.ink10,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  userEmail: {
    color: authControlStyles.colors.ink40,
    fontFamily: "serif",
    fontSize: 13,
    lineHeight: 18,
  },
  userName: {
    color: authControlStyles.colors.ink,
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 23,
  },
}));
