import type { AuthLanguage } from "@/features/auth/authCopy";
import type { StoreJobRoleOption } from "@/features/stores/storeTypes";

// Line-staff roles a store manager is allowed to assign — must stay in sync
// with the backend's MANAGEABLE_JOB_ROLE_VALUES (permissions.service.ts).
// Anything outside this set is rejected (403) for non-holding viewers.
export const STORE_ASSIGNABLE_JOB_ROLE_VALUES = [
  "front-host",
  "front-cashier",
  "front-server",
  "front-packer",
  "front-bar",
  "back-dishwasher",
  "back-noodle",
  "back-hot-appetizer",
  "back-cold-appetizer",
  "back-rice",
];

export const STORE_JOB_ROLE_OPTIONS: Record<AuthLanguage, StoreJobRoleOption[]> = {
  zh: [
    { value: "holding", label: "总部" },
    { value: "regional-manager", label: "区域经理" },
    { value: "store-manager", label: "店长" },
    { value: "front-manager", label: "前厅经理" },
    { value: "back-manager", label: "后厨经理" },
    { value: "front-assistant", label: "前厅助理" },
    { value: "back-assistant", label: "后厨助理" },
    { value: "front-of-house", label: "前厅" },
    { value: "back-of-house", label: "后厨" },
    { value: "front-host", label: "迎宾" },
    { value: "front-cashier", label: "收银" },
    { value: "front-server", label: "服务生" },
    { value: "front-packer", label: "打包" },
    { value: "front-bar", label: "吧台" },
    { value: "back-dishwasher", label: "洗碗" },
    { value: "back-noodle", label: "打面" },
    { value: "back-hot-appetizer", label: "热前菜" },
    { value: "back-cold-appetizer", label: "冷前菜" },
    { value: "back-rice", label: "饭" },
  ],
  en: [
    { value: "holding", label: "Holding" },
    { value: "regional-manager", label: "Regional manager" },
    { value: "store-manager", label: "Store manager" },
    { value: "front-manager", label: "Front manager" },
    { value: "back-manager", label: "Kitchen manager" },
    { value: "front-assistant", label: "Front assistant" },
    { value: "back-assistant", label: "Kitchen assistant" },
    { value: "front-of-house", label: "Front of house" },
    { value: "back-of-house", label: "Kitchen" },
    { value: "front-host", label: "Host" },
    { value: "front-cashier", label: "Cashier" },
    { value: "front-server", label: "Server" },
    { value: "front-packer", label: "Packer" },
    { value: "front-bar", label: "Bar" },
    { value: "back-dishwasher", label: "Dishwasher" },
    { value: "back-noodle", label: "Noodle station" },
    { value: "back-hot-appetizer", label: "Hot appetizer" },
    { value: "back-cold-appetizer", label: "Cold appetizer" },
    { value: "back-rice", label: "Rice station" },
  ],
  fr: [
    { value: "holding", label: "Holding" },
    { value: "regional-manager", label: "Manager régional" },
    { value: "store-manager", label: "Gérant" },
    { value: "front-manager", label: "Responsable salle" },
    { value: "back-manager", label: "Responsable cuisine" },
    { value: "front-assistant", label: "Assistant salle" },
    { value: "back-assistant", label: "Assistant cuisine" },
    { value: "front-of-house", label: "Salle" },
    { value: "back-of-house", label: "Cuisine" },
    { value: "front-host", label: "Accueil" },
    { value: "front-cashier", label: "Caisse" },
    { value: "front-server", label: "Serveur" },
    { value: "front-packer", label: "Emballage" },
    { value: "front-bar", label: "Bar" },
    { value: "back-dishwasher", label: "Plonge" },
    { value: "back-noodle", label: "Nouilles" },
    { value: "back-hot-appetizer", label: "Entrée chaude" },
    { value: "back-cold-appetizer", label: "Entrée froide" },
    { value: "back-rice", label: "Riz" },
  ],
};

export const STORE_COPY = {
  zh: {
    address: "地址",
    appliedRole: "申请岗位",
    approve: "通过",
    backToList: "返回门店",
    backToStore: "返回门店详情",
    deleteCancel: "取消",
    deleteConfirm: "删除",
    deleteEmployee: "删除员工",
    deleteEmployeeBody: "该员工将无法登录，并从当前团队列表移除。",
    deleteEmployeeTitle: "删除这个员工？",
    employeeDeleted: "员工已删除。",
    employeeDeleteError: "删除员工失败。",
    empty: "暂无可管理门店。",
    error: "门店数据加载失败。",
    filterAll: "全部岗位",
    imageFallback: "ZHAO",
    listCardHint: "审核新注册员工",
    listHint: "查看门店团队、待审批员工和岗位信息。",
    listTitle: "门店",
    loading: "正在加载门店...",
    noPending: "暂无待审批员工。",
    noSearchResult: "没有匹配的员工。",
    noTeam: "暂无已通过员工。",
    pending: "待审批",
    pendingCardHint: "待处理申请",
    reject: "拒绝",
    reviewing: "处理中...",
    roleSaved: "岗位已更新。",
    roleSaveError: "岗位保存失败。",
    saveRole: "保存岗位",
    searchPlaceholder: "搜索姓名或邮箱",
    selectRole: "选择岗位",
    stats: "人员统计",
    statsCardHint: "查看岗位人数",
    statusApproved: "已通过",
    statusPending: "待审批",
    statusRejected: "已拒绝",
    storeCode: "编号",
    team: "团队",
    teamCardHint: "管理岗位与员工",
    totalMembers: "总人数",
    titleKicker: "ZHAO · STORES",
    unavailable: "当前账号没有门店管理权限。",
    updateError: "操作失败，请稍后重试。",
  },
  en: {
    address: "Address",
    appliedRole: "Applied position",
    approve: "Approve",
    backToList: "Back to stores",
    backToStore: "Back to store",
    deleteCancel: "Cancel",
    deleteConfirm: "Delete",
    deleteEmployee: "Delete employee",
    deleteEmployeeBody: "This employee will no longer be able to sign in and will be removed from the team list.",
    deleteEmployeeTitle: "Delete this employee?",
    employeeDeleted: "Employee deleted.",
    employeeDeleteError: "Employee could not be deleted.",
    empty: "No manageable stores.",
    error: "Store data could not be loaded.",
    filterAll: "All positions",
    imageFallback: "ZHAO",
    listCardHint: "Review new registrations",
    listHint: "Review store teams, pending employees and positions.",
    listTitle: "Stores",
    loading: "Loading stores...",
    noPending: "No pending employees.",
    noSearchResult: "No matching employees.",
    noTeam: "No approved employees yet.",
    pending: "Pending",
    pendingCardHint: "Requests to review",
    reject: "Reject",
    reviewing: "Saving...",
    roleSaved: "Position updated.",
    roleSaveError: "Position could not be saved.",
    saveRole: "Save position",
    searchPlaceholder: "Search name or email",
    selectRole: "Select position",
    stats: "People stats",
    statsCardHint: "View position counts",
    statusApproved: "Approved",
    statusPending: "Pending",
    statusRejected: "Rejected",
    storeCode: "Code",
    team: "Team",
    teamCardHint: "Manage positions and people",
    totalMembers: "Total people",
    titleKicker: "ZHAO · STORES",
    unavailable: "This account cannot manage stores.",
    updateError: "Action failed. Please try again.",
  },
  fr: {
    address: "Adresse",
    appliedRole: "Poste demandé",
    approve: "Valider",
    backToList: "Retour aux boutiques",
    backToStore: "Retour boutique",
    deleteCancel: "Annuler",
    deleteConfirm: "Supprimer",
    deleteEmployee: "Supprimer",
    deleteEmployeeBody: "Cet employé ne pourra plus se connecter et sera retiré de l'équipe.",
    deleteEmployeeTitle: "Supprimer cet employé ?",
    employeeDeleted: "Employé supprimé.",
    employeeDeleteError: "Impossible de supprimer l'employé.",
    empty: "Aucune boutique gérable.",
    error: "Impossible de charger les boutiques.",
    filterAll: "Tous les postes",
    imageFallback: "ZHAO",
    listCardHint: "Valider les inscriptions",
    listHint: "Consultez les équipes, employés en attente et postes.",
    listTitle: "Boutiques",
    loading: "Chargement des boutiques...",
    noPending: "Aucun employé en attente.",
    noSearchResult: "Aucun employé correspondant.",
    noTeam: "Aucun employé validé pour le moment.",
    pending: "En attente",
    pendingCardHint: "Demandes à traiter",
    reject: "Refuser",
    reviewing: "En cours...",
    roleSaved: "Poste mis à jour.",
    roleSaveError: "Impossible d'enregistrer le poste.",
    saveRole: "Enregistrer",
    searchPlaceholder: "Rechercher nom ou email",
    selectRole: "Choisir le poste",
    stats: "Statistiques",
    statsCardHint: "Voir les effectifs par poste",
    statusApproved: "Validé",
    statusPending: "En attente",
    statusRejected: "Refusé",
    storeCode: "Code",
    team: "Equipe",
    teamCardHint: "Gérer postes et employés",
    totalMembers: "Total équipe",
    titleKicker: "ZHAO · BOUTIQUES",
    unavailable: "Ce compte ne peut pas gérer les boutiques.",
    updateError: "Action impossible. Réessayez plus tard.",
  },
};
