export const PROFILE_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "个人资料 · PROFILE",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 个人 · 档案",
    title: "你的",
    titleEm: "档案",
    titleSuffix: "。",
    lede: "查看并完善你的个人资料、联系方式与账号安全。",
    back: "返回首页",
    footer: "Since 2011 — ZHAO's Family Holding",

    identityHeading: "身份",
    identityHint: "登录信息由管理员维护，如需更改请联系人事。",
    fieldName: "姓名",
    fieldEmail: "邮箱",
    fieldRole: "岗位",
    fieldStore: "门店",
    noValue: "未填写",

    certificationHeading: "认证墙",
    certificationHint: "已获得 {earned} / {total} 项认证",
    certificationEmpty: "尚未获得任何认证。完成培训课程即可解锁。",
    certificationInProgress: "进行中",
    certificationLevel: "Lv.",
    certificationLoading: "正在加载认证…",
    certificationError: "加载失败，请稍后重试。",

    contactHeading: "联系方式",
    contactHint: "用于紧急联系与运营通知。",
    fieldPhone: "电话",
    fieldAddress: "地址",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    saved: "已保存",

    preferencesHeading: "偏好",
    preferencesHint: "界面语言会保存到这台设备。",
    fieldLang: "界面语言",
    langOption: { zh: "中文", en: "English", fr: "Français" },

    securityHeading: "账号安全",
    securityHint: "密码每 90 天需要更新一次。",
    changePassword: "修改密码",
    passwordIntro: "修改密码后请使用新密码重新登录。",
    fieldCurrentPassword: "当前密码",
    fieldNewPassword: "新密码",
    fieldConfirmPassword: "确认新密码",
    passwordRule: "新密码至少 8 位。",
    passwordSubmit: "更新密码",
    passwordSubmitting: "正在更新…",
    passwordChanged: "✓ 密码已更新",
    passwordErrTooShort: "新密码至少 8 位。",
    passwordErrMismatch: "两次输入的新密码不一致。",
    passwordErrCurrentWrong: "当前密码不正确。",
    passwordErrGeneric: "更新失败，请稍后重试。",

    logoutHeading: "登出",
    logoutHint: "结束当前会话并返回登录页。",
    logout: "退出登录",
    loggingOut: "正在退出…",

    dangerHeading: "删除账号",
    dangerHint: "永久删除后无法恢复，你的个人信息将被匿名化。",
    deleteAccount: "删除我的账号",
    deleteWarning: "此操作不可撤销。确认后你的账号将被停用、个人信息将被匿名化，且你会立即退出登录。请输入当前密码以确认。",
    fieldDeletePassword: "当前密码",
    deleteConfirm: "永久删除账号",
    deleteSubmitting: "正在删除…",
    deleteErrCurrentWrong: "密码不正确。",
    deleteErrGeneric: "删除失败，请稍后重试。",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "PROFILE · 个人资料",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · PERSONAL · PROFILE",
    title: "Your ",
    titleEm: "profile",
    titleSuffix: ".",
    lede: "Review and complete your profile, contact info and account security.",
    back: "Back to home",
    footer: "Since 2011 — ZHAO's Family Holding",

    identityHeading: "Identity",
    identityHint: "Identity fields are managed by HR — contact them to update.",
    fieldName: "Name",
    fieldEmail: "Email",
    fieldRole: "Role",
    fieldStore: "Store",
    noValue: "Not set",

    certificationHeading: "Certifications",
    certificationHint: "{earned} / {total} certifications earned",
    certificationEmpty: "No certifications yet. Complete training courses to unlock them.",
    certificationInProgress: "In progress",
    certificationLevel: "Lv.",
    certificationLoading: "Loading certifications…",
    certificationError: "Failed to load, please try again later.",

    contactHeading: "Contact",
    contactHint: "Used for emergencies and operational notices.",
    fieldPhone: "Phone",
    fieldAddress: "Address",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    saved: "Saved",

    preferencesHeading: "Preferences",
    preferencesHint: "Interface language is saved on this device.",
    fieldLang: "Interface language",
    langOption: { zh: "中文", en: "English", fr: "Français" },

    securityHeading: "Account security",
    securityHint: "Password must be updated every 90 days.",
    changePassword: "Change password",
    passwordIntro: "After changing it, sign in again with your new password.",
    fieldCurrentPassword: "Current password",
    fieldNewPassword: "New password",
    fieldConfirmPassword: "Confirm new password",
    passwordRule: "New password must be at least 8 characters.",
    passwordSubmit: "Update password",
    passwordSubmitting: "Updating…",
    passwordChanged: "✓ Password updated",
    passwordErrTooShort: "New password must be at least 8 characters.",
    passwordErrMismatch: "The two new passwords don't match.",
    passwordErrCurrentWrong: "Current password is incorrect.",
    passwordErrGeneric: "Update failed, please try again later.",

    logoutHeading: "Sign out",
    logoutHint: "End this session and return to login.",
    logout: "Sign out",
    loggingOut: "Signing out…",

    dangerHeading: "Delete account",
    dangerHint: "Deletion is permanent and your personal data will be anonymized.",
    deleteAccount: "Delete my account",
    deleteWarning:
      "This action cannot be undone. Once confirmed, your account is deactivated, your personal data is anonymized, and you are signed out immediately. Enter your current password to confirm.",
    fieldDeletePassword: "Current password",
    deleteConfirm: "Permanently delete account",
    deleteSubmitting: "Deleting…",
    deleteErrCurrentWrong: "Password is incorrect.",
    deleteErrGeneric: "Deletion failed, please try again later.",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "PROFIL · 个人资料",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · PERSONNEL · PROFIL",
    title: "Votre ",
    titleEm: "profil",
    titleSuffix: ".",
    lede: "Consultez et complétez votre profil, vos coordonnées et la sécurité du compte.",
    back: "Retour à l'accueil",
    footer: "Since 2011 — ZHAO's Family Holding",

    identityHeading: "Identité",
    identityHint: "L'identité est gérée par les RH — contactez-les pour la modifier.",
    fieldName: "Nom",
    fieldEmail: "Email",
    fieldRole: "Poste",
    fieldStore: "Boutique",
    noValue: "Non renseigné",

    certificationHeading: "Certifications",
    certificationHint: "{earned} / {total} certifications obtenues",
    certificationEmpty: "Aucune certification pour le moment. Suivez des formations pour en débloquer.",
    certificationInProgress: "En cours",
    certificationLevel: "Nv.",
    certificationLoading: "Chargement des certifications…",
    certificationError: "Échec du chargement, réessayez plus tard.",

    contactHeading: "Coordonnées",
    contactHint: "Utilisées en cas d'urgence et pour les notifications d'exploitation.",
    fieldPhone: "Téléphone",
    fieldAddress: "Adresse",
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    saved: "Enregistré",

    preferencesHeading: "Préférences",
    preferencesHint: "La langue de l'interface est enregistrée sur cet appareil.",
    fieldLang: "Langue de l'interface",
    langOption: { zh: "中文", en: "English", fr: "Français" },

    securityHeading: "Sécurité du compte",
    securityHint: "Le mot de passe doit être renouvelé tous les 90 jours.",
    changePassword: "Changer le mot de passe",
    passwordIntro: "Après modification, reconnectez-vous avec votre nouveau mot de passe.",
    fieldCurrentPassword: "Mot de passe actuel",
    fieldNewPassword: "Nouveau mot de passe",
    fieldConfirmPassword: "Confirmer le nouveau mot de passe",
    passwordRule: "Le nouveau mot de passe doit comporter au moins 8 caractères.",
    passwordSubmit: "Mettre à jour le mot de passe",
    passwordSubmitting: "Mise à jour…",
    passwordChanged: "✓ Mot de passe mis à jour",
    passwordErrTooShort: "Le nouveau mot de passe doit comporter au moins 8 caractères.",
    passwordErrMismatch: "Les deux nouveaux mots de passe ne correspondent pas.",
    passwordErrCurrentWrong: "Le mot de passe actuel est incorrect.",
    passwordErrGeneric: "Échec de la mise à jour, réessayez plus tard.",

    logoutHeading: "Déconnexion",
    logoutHint: "Terminez cette session et retournez à la page de connexion.",
    logout: "Se déconnecter",
    loggingOut: "Déconnexion…",

    dangerHeading: "Supprimer le compte",
    dangerHint: "La suppression est définitive et vos données personnelles seront anonymisées.",
    deleteAccount: "Supprimer mon compte",
    deleteWarning:
      "Cette action est irréversible. Une fois confirmée, votre compte est désactivé, vos données personnelles sont anonymisées et vous êtes déconnecté immédiatement. Saisissez votre mot de passe actuel pour confirmer.",
    fieldDeletePassword: "Mot de passe actuel",
    deleteConfirm: "Supprimer définitivement le compte",
    deleteSubmitting: "Suppression…",
    deleteErrCurrentWrong: "Le mot de passe est incorrect.",
    deleteErrGeneric: "Échec de la suppression, réessayez plus tard.",
  },
};
