export const PROFILE_COPY = {
  zh: {
    topFamily: "FAMILY",
    topStage: "个人资料 · PROFILE",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · 个人 · 档案",
    title: "你的",
    titleEm: "档案",
    titleSuffix: "。",
    lede: "查看并完善你的个人资料、联系方式与账号安全。",
    back: "返回首页",
    footer: "Since 2011 — ZHAO's Family Holding",

    identityHeading: "身份",
    identityHint: "登录信息由管理员维护，如需更改请联系人事。",
    fieldName: "姓名",
    fieldEmail: "邮箱",
    fieldRole: "岗位",
    fieldStore: "门店",
    noValue: "未填写",

    contactHeading: "联系方式",
    contactHint: "用于紧急联系与运营通知。",
    fieldPhone: "电话",
    fieldAddress: "地址",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    saved: "已保存（模拟）",

    preferencesHeading: "偏好",
    preferencesHint: "界面语言仅影响本次浏览。",
    fieldLang: "界面语言",
    langOption: { zh: "中文", en: "English", fr: "Français" },

    securityHeading: "账号安全",
    securityHint: "密码每 90 天需要更新一次。",
    changePassword: "修改密码",
    passwordPlaceholder: "敬请期待（模拟占位）。",

    logoutHeading: "登出",
    logoutHint: "结束当前会话并返回登录页。",
    logout: "退出登录",
    loggingOut: "正在退出…",
  },
  en: {
    topFamily: "FAMILY",
    topStage: "PROFILE · 个人资料",
    topCycle: "WEEK 17 · 2026",
    kicker: "ZHAO's · PERSONAL · PROFILE",
    title: "Your ",
    titleEm: "profile",
    titleSuffix: ".",
    lede: "Review and complete your profile, contact info and account security.",
    back: "Back to home",
    footer: "Since 2011 — ZHAO's Family Holding",

    identityHeading: "Identity",
    identityHint: "Identity fields are managed by HR — contact them to update.",
    fieldName: "Name",
    fieldEmail: "Email",
    fieldRole: "Role",
    fieldStore: "Store",
    noValue: "Not set",

    contactHeading: "Contact",
    contactHint: "Used for emergencies and operational notices.",
    fieldPhone: "Phone",
    fieldAddress: "Address",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    saved: "Saved (mock)",

    preferencesHeading: "Preferences",
    preferencesHint: "Interface language applies to this session only.",
    fieldLang: "Interface language",
    langOption: { zh: "中文", en: "English", fr: "Français" },

    securityHeading: "Account security",
    securityHint: "Password must be updated every 90 days.",
    changePassword: "Change password",
    passwordPlaceholder: "Coming soon (mock placeholder).",

    logoutHeading: "Sign out",
    logoutHint: "End this session and return to login.",
    logout: "Sign out",
    loggingOut: "Signing out…",
  },
  fr: {
    topFamily: "FAMILY",
    topStage: "PROFIL · 个人资料",
    topCycle: "SEMAINE 17 · 2026",
    kicker: "ZHAO's · PERSONNEL · PROFIL",
    title: "Votre ",
    titleEm: "profil",
    titleSuffix: ".",
    lede: "Consultez et complétez votre profil, vos coordonnées et la sécurité du compte.",
    back: "Retour à l'accueil",
    footer: "Since 2011 — ZHAO's Family Holding",

    identityHeading: "Identité",
    identityHint: "L'identité est gérée par les RH — contactez-les pour la modifier.",
    fieldName: "Nom",
    fieldEmail: "Email",
    fieldRole: "Poste",
    fieldStore: "Boutique",
    noValue: "Non renseigné",

    contactHeading: "Coordonnées",
    contactHint: "Utilisées en cas d'urgence et pour les notifications d'exploitation.",
    fieldPhone: "Téléphone",
    fieldAddress: "Adresse",
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    saved: "Enregistré (simulation)",

    preferencesHeading: "Préférences",
    preferencesHint: "La langue de l'interface s'applique à cette session.",
    fieldLang: "Langue de l'interface",
    langOption: { zh: "中文", en: "English", fr: "Français" },

    securityHeading: "Sécurité du compte",
    securityHint: "Le mot de passe doit être renouvelé tous les 90 jours.",
    changePassword: "Changer le mot de passe",
    passwordPlaceholder: "Bientôt disponible (simulation).",

    logoutHeading: "Déconnexion",
    logoutHint: "Terminez cette session et retournez à la page de connexion.",
    logout: "Se déconnecter",
    loggingOut: "Déconnexion…",
  },
};
